In [ ]:
PivotTable,Reshaping,multindex

In [135]:
import pandas as pd

data = {
    "Month": ["Jan", "Jan", "Jan", "Feb", "Feb", "Feb",
              "Mar", "Mar", "Mar", "Apr", "Apr", "Apr"],

    "Department": ["IT", "HR", "Finance",
                   "IT", "HR", "Finance",
                   "IT", "HR", "Finance",
                   "IT", "HR", "Finance"],

    "Sales": [50000, 30000, 40000,
              60000, 35000, 45000,
              55000, 32000, 50000,
              70000, 40000, 55000],

    "Profit": [10000, 6000, 8000,
               12000, 7000, 9000,
               11000, 6500, 10000,
               15000, 8000, 12000],

    "Employees": [10, 8, 6,
                  11, 8, 7,
                  12, 9, 7,
                  13, 9, 8]
}

df = pd.DataFrame(data)

df

   Month Department  Sales  Profit  Employees
0    Jan         IT  50000   10000         10
1    Jan         HR  30000    6000          8
2    Jan    Finance  40000    8000          6
3    Feb         IT  60000   12000         11
4    Feb         HR  35000    7000          8
5    Feb    Finance  45000    9000          7
6    Mar         IT  55000   11000         12
7    Mar         HR  32000    6500          9
8    Mar    Finance  50000   10000          7
9    Apr         IT  70000   15000         13
10   Apr         HR  40000    8000          9
11   Apr    Finance  55000   12000          8

In [7]:
df.pivot(
    index="Month",
    columns="Department",
    values="Sales"
)

Department  Finance     HR     IT
Month
Apr           55000  40000  70000
Feb           45000  35000  60000
Jan           40000  30000  50000
Mar           50000  32000  55000

In [9]:
df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales",
    aggfunc="sum"
)

Department  Finance     HR     IT
Month
Apr           55000  40000  70000
Feb           45000  35000  60000
Jan           40000  30000  50000
Mar           50000  32000  55000

In [13]:
df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales",
    aggfunc="mean"
)

Department  Finance       HR       IT
Month
Apr         55000.0  40000.0  70000.0
Feb         45000.0  35000.0  60000.0
Jan         40000.0  30000.0  50000.0
Mar         50000.0  32000.0  55000.0

In [15]:
df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales",
    aggfunc="max"
)

Department  Finance     HR     IT
Month
Apr           55000  40000  70000
Feb           45000  35000  60000
Jan           40000  30000  50000
Mar           50000  32000  55000

In [17]:
df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales",
    aggfunc="count"
)

Department  Finance  HR  IT
Month
Apr               1   1   1
Feb               1   1   1
Jan               1   1   1
Mar               1   1   1

In [19]:
df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales",
    aggfunc=["sum","mean","max","count"]
)

               sum                   mean                       max         \
Department Finance     HR     IT  Finance       HR       IT Finance     HR
Month
Apr          55000  40000  70000  55000.0  40000.0  70000.0   55000  40000
Feb          45000  35000  60000  45000.0  35000.0  60000.0   45000  35000
Jan          40000  30000  50000  40000.0  30000.0  50000.0   40000  30000
Mar          50000  32000  55000  50000.0  32000.0  55000.0   50000  32000

                    count
Department     IT Finance HR IT
Month
Apr         70000       1  1  1
Feb         60000       1  1  1
Jan         50000       1  1  1
Mar         55000       1  1  1

In [21]:
df.pivot_table(
    index="Month",
    columns="Department",
    values=["Sales","Profit"],
    aggfunc="sum"
)

            Profit                Sales
Department Finance    HR     IT Finance     HR     IT
Month
Apr          12000  8000  15000   55000  40000  70000
Feb           9000  7000  12000   45000  35000  60000
Jan           8000  6000  10000   40000  30000  50000
Mar          10000  6500  11000   50000  32000  55000

In [23]:
df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales",
    aggfunc="sum",
    margins=True
)

Department  Finance      HR      IT     All
Month
Apr           55000   40000   70000  165000
Feb           45000   35000   60000  140000
Jan           40000   30000   50000  120000
Mar           50000   32000   55000  137000
All          190000  137000  235000  562000

In [25]:
df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales",
    aggfunc="sum",
    fill_value=0
)

Department  Finance     HR     IT
Month
Apr           55000  40000  70000
Feb           45000  35000  60000
Jan           40000  30000  50000
Mar           50000  32000  55000

In [ ]:
melt()-wide-long

In [27]:
wide_df = pd.DataFrame({
    "Month": ["Jan", "Feb", "Mar"],
    "IT": [50000, 60000, 55000],
    "HR": [30000, 35000, 32000],
    "Finance": [40000, 45000, 50000]
})

wide_df

  Month     IT     HR  Finance
0   Jan  50000  30000    40000
1   Feb  60000  35000    45000
2   Mar  55000  32000    50000

In [29]:
wide_df.melt(
    id_vars="Month",
    var_name="Department",
    value_name="Sales"
)

  Month Department  Sales
0   Jan         IT  50000
1   Feb         IT  60000
2   Mar         IT  55000
3   Jan         HR  30000
4   Feb         HR  35000
5   Mar         HR  32000
6   Jan    Finance  40000
7   Feb    Finance  45000
8   Mar    Finance  50000

In [ ]:
set_index()

In [31]:
df.set_index("Month")

      Department  Sales  Profit  Employees
Month
Jan           IT  50000   10000         10
Jan           HR  30000    6000          8
Jan      Finance  40000    8000          6
Feb           IT  60000   12000         11
Feb           HR  35000    7000          8
Feb      Finance  45000    9000          7
Mar           IT  55000   11000         12
Mar           HR  32000    6500          9
Mar      Finance  50000   10000          7
Apr           IT  70000   15000         13
Apr           HR  40000    8000          9
Apr      Finance  55000   12000          8

In [33]:
df.set_index(["Month","Department"])

                  Sales  Profit  Employees
Month Department
Jan   IT          50000   10000         10
      HR          30000    6000          8
      Finance     40000    8000          6
Feb   IT          60000   12000         11
      HR          35000    7000          8
      Finance     45000    9000          7
Mar   IT          55000   11000         12
      HR          32000    6500          9
      Finance     50000   10000          7
Apr   IT          70000   15000         13
      HR          40000    8000          9
      Finance     55000   12000          8

In [35]:
df.reset_index()

    index Month Department  Sales  Profit  Employees
0       0   Jan         IT  50000   10000         10
1       1   Jan         HR  30000    6000          8
2       2   Jan    Finance  40000    8000          6
3       3   Feb         IT  60000   12000         11
4       4   Feb         HR  35000    7000          8
5       5   Feb    Finance  45000    9000          7
6       6   Mar         IT  55000   11000         12
7       7   Mar         HR  32000    6500          9
8       8   Mar    Finance  50000   10000          7
9       9   Apr         IT  70000   15000         13
10     10   Apr         HR  40000    8000          9
11     11   Apr    Finance  55000   12000          8

In [ ]:
stack()-columns -index-hierracrachical

In [37]:
df_stack=df.pivot(
    index="Month",
    columns="Department",
    values="Sales"
)
df_stack.stack()

Month  Department
Apr    Finance       55000
       HR            40000
       IT            70000
Feb    Finance       45000
       HR            35000
       IT            60000
Jan    Finance       40000
       HR            30000
       IT            50000
Mar    Finance       50000
       HR            32000
       IT            55000
dtype: int64

In [ ]:
unstack()-index-column

In [39]:
df2=df.set_index(["Month","Department"])
df2.unstack()

             Sales                Profit              Employees
Department Finance     HR     IT Finance    HR     IT   Finance HR  IT
Month
Apr          55000  40000  70000   12000  8000  15000         8  9  13
Feb          45000  35000  60000    9000  7000  12000         7  8  11
Jan          40000  30000  50000    8000  6000  10000         6  8  10
Mar          50000  32000  55000   10000  6500  11000         7  9  12

In [ ]:
"Mujhe har month aur department ki total sales chahiye, saath mein grand total bhi.

In [41]:
df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales",
    aggfunc="sum",
    margins=True
)

Department  Finance      HR      IT     All
Month
Apr           55000   40000   70000  165000
Feb           45000   35000   60000  140000
Jan           40000   30000   50000  120000
Mar           50000   32000   55000  137000
All          190000  137000  235000  562000

In [ ]:
Q1. df ka Month column ko index banao.
Q2. Month aur Department ko MultiIndex banao.
Q3. MultiIndex ko wapas normal columns mein convert karo.
Q4. Month ko rows, Department ko columns aur Sales ko values rakhkar pivot() banao.
Q5. Same Q4 ko pivot_table() se solve karo.

In [ ]:
Q1. df ka Month column ko index banao.

In [45]:
df.set_index("Month")

      Department  Sales  Profit  Employees
Month
Jan           IT  50000   10000         10
Jan           HR  30000    6000          8
Jan      Finance  40000    8000          6
Feb           IT  60000   12000         11
Feb           HR  35000    7000          8
Feb      Finance  45000    9000          7
Mar           IT  55000   11000         12
Mar           HR  32000    6500          9
Mar      Finance  50000   10000          7
Apr           IT  70000   15000         13
Apr           HR  40000    8000          9
Apr      Finance  55000   12000          8

In [ ]:
Q2. Month aur Department ko MultiIndex banao.

In [47]:
df.set_index(["Month","Department"])

                  Sales  Profit  Employees
Month Department
Jan   IT          50000   10000         10
      HR          30000    6000          8
      Finance     40000    8000          6
Feb   IT          60000   12000         11
      HR          35000    7000          8
      Finance     45000    9000          7
Mar   IT          55000   11000         12
      HR          32000    6500          9
      Finance     50000   10000          7
Apr   IT          70000   15000         13
      HR          40000    8000          9
      Finance     55000   12000          8

In [ ]:
Q3. MultiIndex ko wapas normal columns mein convert karo.

In [49]:
df.reset_index()

    index Month Department  Sales  Profit  Employees
0       0   Jan         IT  50000   10000         10
1       1   Jan         HR  30000    6000          8
2       2   Jan    Finance  40000    8000          6
3       3   Feb         IT  60000   12000         11
4       4   Feb         HR  35000    7000          8
5       5   Feb    Finance  45000    9000          7
6       6   Mar         IT  55000   11000         12
7       7   Mar         HR  32000    6500          9
8       8   Mar    Finance  50000   10000          7
9       9   Apr         IT  70000   15000         13
10     10   Apr         HR  40000    8000          9
11     11   Apr    Finance  55000   12000          8

In [ ]:
Q4. Month ko rows, Department ko columns aur Sales ko values rakhkar pivot() banao.

In [51]:
df.pivot(
    index="Month",
    columns="Department",
    values="Sales"
)

Department  Finance     HR     IT
Month
Apr           55000  40000  70000
Feb           45000  35000  60000
Jan           40000  30000  50000
Mar           50000  32000  55000

In [ ]:
Q5. Same Q4 ko pivot_table() se solve karo.

In [53]:
df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales"
)

Department  Finance       HR       IT
Month
Apr         55000.0  40000.0  70000.0
Feb         45000.0  35000.0  60000.0
Jan         40000.0  30000.0  50000.0
Mar         50000.0  32000.0  55000.0

In [ ]:
Q6. Har month aur department ki total Sales nikalo.
Q7. Har month aur department ki average Sales nikalo.
Q8. Har month aur department ka maximum Sales nikalo.
Q9. Har month aur department mein kitne records hain, nikalo.
Q10. Sales aur Profit dono ka monthly-department-wise sum nikalo.

In [ ]:
Q6. Har month aur department ki total Sales nikalo.

In [55]:
df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales",
    aggfunc="sum"
)

Department  Finance     HR     IT
Month
Apr           55000  40000  70000
Feb           45000  35000  60000
Jan           40000  30000  50000
Mar           50000  32000  55000

In [ ]:
Q7. Har month aur department ki average Sales nikalo.

In [59]:
df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales",
    aggfunc="mean"
)

Department  Finance       HR       IT
Month
Apr         55000.0  40000.0  70000.0
Feb         45000.0  35000.0  60000.0
Jan         40000.0  30000.0  50000.0
Mar         50000.0  32000.0  55000.0

In [ ]:
8. Har month aur department ka maximum Sales nikalo.

In [63]:
df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales",
    aggfunc="max"
)

Department  Finance     HR     IT
Month
Apr           55000  40000  70000
Feb           45000  35000  60000
Jan           40000  30000  50000
Mar           50000  32000  55000

In [ ]:
Q9. Har month aur department mein kitne records hain, nikalo.

In [65]:
df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales",
    aggfunc="count"
)

Department  Finance  HR  IT
Month
Apr               1   1   1
Feb               1   1   1
Jan               1   1   1
Mar               1   1   1

In [ ]:
Q10. Sales aur Profit dono ka monthly-department-wise sum nikalo.

In [67]:
df.pivot_table(
    index="Month",
    columns="Department",
    values=["Sales","Profit"],
    aggfunc="sum"
)

            Profit                Sales
Department Finance    HR     IT Finance     HR     IT
Month
Apr          12000  8000  15000   55000  40000  70000
Feb           9000  7000  12000   45000  35000  60000
Jan           8000  6000  10000   40000  30000  50000
Mar          10000  6500  11000   50000  32000  55000

In [ ]:
Q11. Har month ka total Sales nikalo using pivot_table().
Q12. Har department ka total Sales nikalo.
Q13. Har month ka total Profit nikalo.
Q14. Har department ka average Profit nikalo.
Q15. Month × Department Sales report banao aur Grand Total bhi show karo.

In [ ]:
Q11. Har month ka total Sales nikalo using pivot_table().

In [71]:
df.pivot_table(
    index="Month",
    values="Sales",
    aggfunc="sum"
)

        Sales
Month
Apr    165000
Feb    140000
Jan    120000
Mar    137000

In [ ]:
Q12. Har department ka total Sales nikalo.

In [73]:
df.pivot_table(
    index="Department",
    values="Sales",
    aggfunc="sum"
)

             Sales
Department
Finance     190000
HR          137000
IT          235000

In [ ]:
Q13. Har month ka total Profit nikalo.

In [75]:
df.pivot_table(
    index="Month",
    values="Profit",
    aggfunc="sum"
)

       Profit
Month
Apr     35000
Feb     28000
Jan     24000
Mar     27500

In [ ]:
Q14. Har department ka average Profit nikalo.

In [77]:
df.pivot_table(
    index="Department",
    values="Profit",
    aggfunc="mean"
)

             Profit
Department
Finance      9750.0
HR           6875.0
IT          12000.0

In [ ]:
Q15. Month × Department Sales report banao aur Grand Total bhi show karo.

In [79]:
df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales",
    aggfunc="sum",
    margins=True
)

Department  Finance      HR      IT     All
Month
Apr           55000   40000   70000  165000
Feb           45000   35000   60000  140000
Jan           40000   30000   50000  120000
Mar           50000   32000   55000  137000
All          190000  137000  235000  562000

In [ ]:
Q16. pivot_table() se wide-format Sales report banao.
Q17. Us wide report ko melt() se long format mein convert karo.
Q18. wide_df ko melt() karke columns ka naam:
Month
Department
Sales

rakho.
Q19. df ko Month + Department MultiIndex mein convert karo aur sirf Sales select karo
Q20. MultiIndex Sales data par unstack() apply karo.

In [129]:
#Q16. pivot_table() se wide-format Sales report banao.
df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales"
)

Department  Finance       HR       IT
Month
Apr         55000.0  40000.0  70000.0
Feb         45000.0  35000.0  60000.0
Jan         40000.0  30000.0  50000.0
Mar         50000.0  32000.0  55000.0

In [127]:
wide_df = pd.DataFrame({
    "Month": ["Jan", "Feb", "Mar"],
    "IT": [50000, 60000, 55000],
    "HR": [30000, 35000, 32000],
    "Finance": [40000, 45000, 50000]
})

wide_df

  Month     IT     HR  Finance
0   Jan  50000  30000    40000
1   Feb  60000  35000    45000
2   Mar  55000  32000    50000

In [121]:
'''#Q17. Us wide report ko melt() se long format mein convert karo.
#Q18. wide_df ko melt() karke columns ka naam:
Month
Department
Sales

rakho.'''
wide_df.melt(
    id_vars="Month",
    var_name="Department",
    value_name="Sales"
)

  Month Department  Sales
0   Jan         IT  50000
1   Feb         IT  60000
2   Mar         IT  55000
3   Jan         HR  30000
4   Feb         HR  35000
5   Mar         HR  32000
6   Jan    Finance  40000
7   Feb    Finance  45000
8   Mar    Finance  50000

In [ ]:
Q19. df ko Month + Department MultiIndex mein convert karo aur sirf Sales select karo.

In [143]:
df3=df.set_index(["Month","Department"])[["Sales"]]
df3

                  Sales
Month Department
Jan   IT          50000
      HR          30000
      Finance     40000
Feb   IT          60000
      HR          35000
      Finance     45000
Mar   IT          55000
      HR          32000
      Finance     50000
Apr   IT          70000
      HR          40000
      Finance     55000

In [ ]:
20. MultiIndex Sales data par unstack() apply karo.

In [145]:
df3.unstack()

             Sales
Department Finance     HR     IT
Month
Apr          55000  40000  70000
Feb          45000  35000  60000
Jan          40000  30000  50000
Mar          50000  32000  55000

In [ ]:
Q21. Har month ka highest-selling department find karo.
Q22. Har department ka highest-sales month find karo.
Q23. Kaunsa department overall sabse zyada Sales generate karta hai?
Q24. Kaunsa month overall sabse zyada Sales generate karta hai?
Q25. Ek final business report banao jisme:
- Rows = Month
- Columns = Department
- Values = Sales
- Aggregation = sum
- Missing combinations = 0
- Grand Total = included

In [ ]:
Q21. Har month ka highest-selling department find karo.

In [147]:
df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales",
    aggfunc="max"
)

Department  Finance     HR     IT
Month
Apr           55000  40000  70000
Feb           45000  35000  60000
Jan           40000  30000  50000
Mar           50000  32000  55000

In [ ]:
Q22. Har department ka highest-sales month find karo.

In [149]:
df.pivot_table(
    index="Department",
    columns="Month",
    values="Sales",
    aggfunc="sum"
)

Month         Apr    Feb    Jan    Mar
Department
Finance     55000  45000  40000  50000
HR          40000  35000  30000  32000
IT          70000  60000  50000  55000

In [ ]:
Q23. Kaunsa department overall sabse zyada Sales generate karta hai

In [159]:
pivot_df=df.pivot_table(
    index="Department",
    columns="Month",
    values="Sales",
    aggfunc="sum"
)
pivot_df

Month         Apr    Feb    Jan    Mar
Department
Finance     55000  45000  40000  50000
HR          40000  35000  30000  32000
IT          70000  60000  50000  55000

In [161]:
pivot_df.sum(axis=1).idxmax()

'IT'

In [ ]:
Q24. Kaunsa month overall sabse zyada Sales generate karta hai?

In [165]:
pivot_dff=df.pivot_table(
    index="Month",
    columns="Department",
    values="Sales",
    aggfunc="sum"
)
pivot_dff

Department  Finance     HR     IT
Month
Apr           55000  40000  70000
Feb           45000  35000  60000
Jan           40000  30000  50000
Mar           50000  32000  55000

In [167]:
pivot_dff.sum(axis=1).idxmax()

'Apr'

In [ ]:
25. Ek final business report banao jisme:
- Rows = Month
- Columns = Department
- Values = Sales
- Aggregation = sum
- Missing combinations = 0
- Grand Total = included

In [ ]:
df.pivot_table(
    index="Month",
    columns="Department",
    values
)