In [3]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit", "Neha"],
    "Age": [25, 32, 28, 41],
    "Salary": [50000, 65000, 45000, 80000]
})
df

    Name  Age  Salary
0  Rahul   25   50000
1  Priya   32   65000
2   Amit   28   45000
3   Neha   41   80000

In [5]:
#assign()-It is especially useful when creating multiple columns or building a Pandas pipeline.
df.assign(
    Annual_Salary=df["Salary"]*12,
    Bonus=df["Salary"]*0.10
)

    Name  Age  Salary  Annual_Salary   Bonus
0  Rahul   25   50000         600000  5000.0
1  Priya   32   65000         780000  6500.0
2   Amit   28   45000         540000  4500.0
3   Neha   41   80000         960000  8000.0

In [11]:
#query()
df.query("Salary > 60000")

    Name  Age  Salary
1  Priya   32   65000
3   Neha   41   80000

In [13]:
#multiple conditions with query()
df.query("Salary>50000 and Age>30")

    Name  Age  Salary
1  Priya   32   65000
3   Neha   41   80000

In [22]:
#python variables with query()
minimum_salary=60000
df.query("Salary>@minimum_salary")

    Name  Age  Salary
1  Priya   32   65000
3   Neha   41   80000

In [24]:
#where()
df["Salary"].where(
    df["Salary"]>60000
)

0        NaN
1    65000.0
2        NaN
3    80000.0
Name: Salary, dtype: float64

In [26]:
df["Salary"].where(
    df["Salary"]>60000,
    0
)

0        0
1    65000
2        0
3    80000
Name: Salary, dtype: int64

In [28]:
#mask()-opposite of mask()
df["Salary"].mask(
    df["Salary"]>60000
)

0    50000.0
1        NaN
2    45000.0
3        NaN
Name: Salary, dtype: float64

In [ ]:
WHERE → "keep where condition is true"

MASK → "hide where condition is true"

In [30]:
#clip()-control extrem values
df = pd.DataFrame({
    "Salary": [30000, 45000, 60000, 80000, 150000]
})
df

   Salary
0   30000
1   45000
2   60000
3   80000
4  150000

In [36]:
df["Salary_Capped"]=df["Salary"].clip(upper=100000)
df

   Salary  Salary_Capped
0   30000          30000
1   45000          45000
2   60000          60000
3   80000          80000
4  150000         100000

In [40]:
df["Salary"].clip(lower=40000,
                 upper=100000)

0     40000
1     45000
2     60000
3     80000
4    100000
Name: Salary, dtype: int64

In [50]:
#astype()
import pandas as pd

df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit", "Neha"],
    "Age": [25, 32, 28, 41],
    "Salary": [50000, 65000, 45000, 80000],
    "Department":["IT","HR","IT","Finance"]
})
df
df["Age"].astype(float)

0    25.0
1    32.0
2    28.0
3    41.0
Name: Age, dtype: float64

In [52]:
df["Age"].astype(str)

0    25
1    32
2    28
3    41
Name: Age, dtype: object

In [54]:
#convert to category
df["Department"].astype("category")

0         IT
1         HR
2         IT
3    Finance
Name: Department, dtype: category
Categories (3, object): ['Finance', 'HR', 'IT']

In [58]:
#select_dtypes
df.select_dtypes(include="number")

   Age  Salary
0   25   50000
1   32   65000
2   28   45000
3   41   80000

In [60]:
df.select_dtypes(include="object")

    Name Department
0  Rahul         IT
1  Priya         HR
2   Amit         IT
3   Neha    Finance

In [62]:
df.select_dtypes(include=["number","object"])

    Name  Age  Salary Department
0  Rahul   25   50000         IT
1  Priya   32   65000         HR
2   Amit   28   45000         IT
3   Neha   41   80000    Finance

In [66]:
# A real data cleaning pipeline
df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit", "Neha"],
    "Age": [25, 32, 28, 150],
    "Salary": [50000, 65000, 45000, 200000],
    "Department": ["IT", "HR", "IT", "Finance"]
})
df

    Name  Age  Salary Department
0  Rahul   25   50000         IT
1  Priya   32   65000         HR
2   Amit   28   45000         IT
3   Neha  150  200000    Finance

In [68]:
df.describe()

              Age         Salary
count    4.000000       4.000000
mean    58.750000   90000.000000
std     60.900876   73824.115301
min     25.000000   45000.000000
25%     27.250000   48750.000000
50%     30.000000   57500.000000
75%     61.500000   98750.000000
max    150.000000  200000.000000

In [70]:
df["Age"].clip(upper=100)

0     25
1     32
2     28
3    100
Name: Age, dtype: int64

In [72]:
df["Salary"].clip(upper=100000)

0     50000
1     65000
2     45000
3    100000
Name: Salary, dtype: int64

In [78]:
df.assign(
    Annual_Sal=df["Salary"]*12
)

    Name  Age  Salary Department  Annual_Sal
0  Rahul   25   50000         IT      600000
1  Priya   32   65000         HR      780000
2   Amit   28   45000         IT      540000
3   Neha  150  200000    Finance     2400000

In [82]:
df.query(
    "Salary>6000"
)

    Name  Age  Salary Department
0  Rahul   25   50000         IT
1  Priya   32   65000         HR
2   Amit   28   45000         IT
3   Neha  150  200000    Finance

In [86]:
import pandas as pd
import numpy as np

data = {
    "Name": [
        "Rahul", "Priya", "Amit", "Neha",
        "Rohit", "Sneha", "Vikas", "Pooja"
    ],
    "Age": [25, 32, 28, 41, 24, 35, 29, 45],
    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "IT", "Finance", "HR"
    ],
    "Salary": [
        50000, 65000, 45000, 80000,
        40000, 70000, 60000, 55000
    ],
    "Experience": [
        2, 6, 3, 10, 1, 7, 5, 8
    ]
}

df = pd.DataFrame(data)
df

    Name  Age Department  Salary  Experience
0  Rahul   25         IT   50000           2
1  Priya   32         HR   65000           6
2   Amit   28         IT   45000           3
3   Neha   41    Finance   80000          10
4  Rohit   24         HR   40000           1
5  Sneha   35         IT   70000           7
6  Vikas   29    Finance   60000           5
7  Pooja   45         HR   55000           8

In [ ]:
Q1

Create Annual_Salary.

Salary × 12

Use assign().

Q2

Create:

Annual_Salary
Annual_Bonus

where:

Annual_Bonus = Annual_Salary × 10%

Use one assign().

Q3

Create:

Experience_Months

using:

Experience × 12
Q4

Create:

Salary_Lakh

Formula:

Salary / 100000
Q5

Using assign(), create both:

Annual_Salary
Salary_Lakh

In [88]:
'''Q1

Create Annual_Salary.

Salary × 12

Use assign().'''
df.assign(
    Annula_Salary=df["Salary"]*12
)

    Name  Age Department  Salary  Experience  Annula_Salary
0  Rahul   25         IT   50000           2         600000
1  Priya   32         HR   65000           6         780000
2   Amit   28         IT   45000           3         540000
3   Neha   41    Finance   80000          10         960000
4  Rohit   24         HR   40000           1         480000
5  Sneha   35         IT   70000           7         840000
6  Vikas   29    Finance   60000           5         720000
7  Pooja   45         HR   55000           8         660000

In [102]:
'''Q2

Create:

Annual_Salary
Annual_Bonus

where:

Annual_Bonus = Annual_Salary × 10%'''

df.assign(
    Annual_Salary=df["Salary"]*12,
    Annual_Bonus=lambda x :x["Annual_Salary"]*0.10
)

    Name  Age Department  Salary  Experience  Annual_Salary  Annual_Bonus
0  Rahul   25         IT   50000           2         600000       60000.0
1  Priya   32         HR   65000           6         780000       78000.0
2   Amit   28         IT   45000           3         540000       54000.0
3   Neha   41    Finance   80000          10         960000       96000.0
4  Rohit   24         HR   40000           1         480000       48000.0
5  Sneha   35         IT   70000           7         840000       84000.0
6  Vikas   29    Finance   60000           5         720000       72000.0
7  Pooja   45         HR   55000           8         660000       66000.0

In [104]:
'''Q3

Create:

Experience_Months

using:

Experience × 12'''
df.assign(
    Experience_Months=df["Experience"]*12
)

    Name  Age Department  Salary  Experience  Experience_Months
0  Rahul   25         IT   50000           2                 24
1  Priya   32         HR   65000           6                 72
2   Amit   28         IT   45000           3                 36
3   Neha   41    Finance   80000          10                120
4  Rohit   24         HR   40000           1                 12
5  Sneha   35         IT   70000           7                 84
6  Vikas   29    Finance   60000           5                 60
7  Pooja   45         HR   55000           8                 96

In [106]:
'''Q4

Create:

Salary_Lakh

Formula:

Salary / 100000'''
df.assign(
    Salary_Lakh=df["Salary"]/100000
)

    Name  Age Department  Salary  Experience  Salary_Lakh
0  Rahul   25         IT   50000           2         0.50
1  Priya   32         HR   65000           6         0.65
2   Amit   28         IT   45000           3         0.45
3   Neha   41    Finance   80000          10         0.80
4  Rohit   24         HR   40000           1         0.40
5  Sneha   35         IT   70000           7         0.70
6  Vikas   29    Finance   60000           5         0.60
7  Pooja   45         HR   55000           8         0.55

In [ ]:
Q6

Find employees with:

Salary > 60000

using query().

Q7

Find employees:

Age > 30
AND
Salary > 50000
Q8

Find employees from:

IT OR HR
Q9

Find employees with:

Experience >= 5
AND
Salary >= 60000
Q10

Create:

minimum_salary = 55000

Then use query() to find employees whose salary is greater than or equal to that variable.

In [108]:
'''Q6

Find employees with:

Salary > 60000

using query().'''
df.query(
    "Salary >60000"
)

    Name  Age Department  Salary  Experience
1  Priya   32         HR   65000           6
3   Neha   41    Finance   80000          10
5  Sneha   35         IT   70000           7

In [110]:
'''
Q7

Find employees:

Age > 30
AND
Salary > 50000'''
df.query(
    "Age >30 and Salary>50000"
)

    Name  Age Department  Salary  Experience
1  Priya   32         HR   65000           6
3   Neha   41    Finance   80000          10
5  Sneha   35         IT   70000           7
7  Pooja   45         HR   55000           8

In [114]:
'''Q8

Find employees from:

IT OR HR'''

df.query(
    "Department=='IT' or Department=='HR'"
)

    Name  Age Department  Salary  Experience
0  Rahul   25         IT   50000           2
1  Priya   32         HR   65000           6
2   Amit   28         IT   45000           3
4  Rohit   24         HR   40000           1
5  Sneha   35         IT   70000           7
7  Pooja   45         HR   55000           8

In [116]:
'''Q10

Create:

minimum_salary = 55000'''
minimum_salary = 55000
df.query("Salary>@minimum_salary")

    Name  Age Department  Salary  Experience
1  Priya   32         HR   65000           6
3   Neha   41    Finance   80000          10
5  Sneha   35         IT   70000           7
6  Vikas   29    Finance   60000           5

In [ ]:
Q11

Using where(), keep salaries >= 50000 and replace the others with 0.

Q12

Using mask(), replace salaries < 50000 with 0.

Q13

Using where(), keep employees whose experience is >= 5; replace others with NaN.

Q14

Using mask(), replace ages greater than 40 with NaN.

Q15 💡

Create:

Salary_Status

using where() so that:

Salary >= 60000 → original Salary
Salary < 60000  → 0

In [118]:
'''Q11

Using where(), keep salaries >= 50000 and replace the others with 0.
'''
df.where(
    df["Salary"]>=50000,
    0
)

    Name  Age Department  Salary  Experience
0  Rahul   25         IT   50000           2
1  Priya   32         HR   65000           6
2      0    0          0       0           0
3   Neha   41    Finance   80000          10
4      0    0          0       0           0
5  Sneha   35         IT   70000           7
6  Vikas   29    Finance   60000           5
7  Pooja   45         HR   55000           8

In [120]:
'''Q12

Using mask(), replace salaries < 50000 with 0.'''
df.where(
    df["Salary"]<50000,
    0
)

    Name  Age Department  Salary  Experience
0      0    0          0       0           0
1      0    0          0       0           0
2   Amit   28         IT   45000           3
3      0    0          0       0           0
4  Rohit   24         HR   40000           1
5      0    0          0       0           0
6      0    0          0       0           0
7      0    0          0       0           0

In [124]:
'''Q13

Using where(), keep employees whose experience is >= 5; replace others with NaN.'''
df.where(
    df["Experience"]>=5
)

    Name   Age Department   Salary  Experience
0    NaN   NaN        NaN      NaN         NaN
1  Priya  32.0         HR  65000.0         6.0
2    NaN   NaN        NaN      NaN         NaN
3   Neha  41.0    Finance  80000.0        10.0
4    NaN   NaN        NaN      NaN         NaN
5  Sneha  35.0         IT  70000.0         7.0
6  Vikas  29.0    Finance  60000.0         5.0
7  Pooja  45.0         HR  55000.0         8.0

In [126]:
'''14

Using mask(), replace ages greater than 40 with NaN.
'''
df.mask(
    df["Age"]>40
)

    Name   Age Department   Salary  Experience
0  Rahul  25.0         IT  50000.0         2.0
1  Priya  32.0         HR  65000.0         6.0
2   Amit  28.0         IT  45000.0         3.0
3    NaN   NaN        NaN      NaN         NaN
4  Rohit  24.0         HR  40000.0         1.0
5  Sneha  35.0         IT  70000.0         7.0
6  Vikas  29.0    Finance  60000.0         5.0
7    NaN   NaN        NaN      NaN         NaN

In [142]:
'''
Q15 💡

Create:

Salary_Status

using where() so that:

Salary >= 60000 → original Salary
Salary < 60000  → 0'''

df["Salary_Status"]=np.where(
    df["Salary"]>=60000,"original Salary",0
)
df

    Name  Age Department  Salary  Experience    Salary_Status
0  Rahul   25         IT   50000           2                0
1  Priya   32         HR   65000           6  original Salary
2   Amit   28         IT   45000           3                0
3   Neha   41    Finance   80000          10  original Salary
4  Rohit   24         HR   40000           1                0
5  Sneha   35         IT   70000           7  original Salary
6  Vikas   29    Finance   60000           5  original Salary
7  Pooja   45         HR   55000           8                0

In [ ]:
Q16

Cap Salary at:

70000

Create:

Salary_Capped
Q17

Set a salary range:

minimum = 45000
maximum = 75000

using clip().

Q18

Create:

Age_Capped

where age cannot exceed 40.

Q19

Create:

Experience_Capped

where experience cannot exceed 7.

Q20 💼

Explain why blindly using clip() on a suspicious value can be dangerous in real-world data analysis.

Think about:

Data validation
vs
Data manipulation

In [148]:
'''16

Cap Salary at:

70000

Create:

Salary_Capped'''
df["Salary_Capped"]=df["Salary"].clip(
    upper=70000
)
df

    Name  Age Department  Salary  Experience    Salary_Status  Salary_Capped
0  Rahul   25         IT   50000           2                0          50000
1  Priya   32         HR   65000           6  original Salary          65000
2   Amit   28         IT   45000           3                0          45000
3   Neha   41    Finance   80000          10  original Salary          70000
4  Rohit   24         HR   40000           1                0          40000
5  Sneha   35         IT   70000           7  original Salary          70000
6  Vikas   29    Finance   60000           5  original Salary          60000
7  Pooja   45         HR   55000           8                0          55000

In [154]:
'''Q17

Set a salary range:

minimum = 45000
maximum = 75000

using clip().'''

df["min_and_max_caped"]=df["Salary"].clip(
    lower=45000,
    upper=75000
)
df

,Name,Age,Department,Salary,Experience,Salary_Status,Salary_Capped,min_and_max_caped
0,Rahul,25,IT,50000,2,0,50000,50000
1,Priya,32,HR,65000,6,original Salary,65000,65000
2,Amit,28,IT,45000,3,0,45000,45000
3,Neha,41,Finance,80000,10,original Salary,70000,75000
4,Rohit,24,HR,40000,1,0,40000,45000
5,Sneha,35,IT,70000,7,original Salary,70000,70000
6,Vikas,29,Finance,60000,5,original Salary,60000,60000
7,Pooja,45,HR,55000,8,0,55000,55000

In [162]:
'''Q18

Create:

Age_Capped

where age cannot exceed 40.
'''
df["Age_caped"]=df["Age"].clip(
    upper=40
)
df

,Name,Age,Department,Salary,Experience,Salary_Status,Salary_Capped,min_and_max_caped,Age_caped
0,Rahul,25,IT,50000,2,0,50000,50000,25
1,Priya,32,HR,65000,6,original Salary,65000,65000,32
2,Amit,28,IT,45000,3,0,45000,45000,28
3,Neha,41,Finance,80000,10,original Salary,70000,75000,40
4,Rohit,24,HR,40000,1,0,40000,45000,24
5,Sneha,35,IT,70000,7,original Salary,70000,70000,35
6,Vikas,29,Finance,60000,5,original Salary,60000,60000,29
7,Pooja,45,HR,55000,8,0,55000,55000,40

In [168]:
'''Q19

Create:

Experience_Capped

where experience cannot exceed 7.
'''
df["Experience_Capped"]=df["Experience"].clip(
    upper=7
)
df

,Name,Age,Department,Salary,Experience,Salary_Status,Salary_Capped,min_and_max_caped,Age_caped,Experience_Capped
0,Rahul,25,IT,50000,2,0,50000,50000,25,2
1,Priya,32,HR,65000,6,original Salary,65000,65000,32,6
2,Amit,28,IT,45000,3,0,45000,45000,28,3
3,Neha,41,Finance,80000,10,original Salary,70000,75000,40,7
4,Rohit,24,HR,40000,1,0,40000,45000,24,1
5,Sneha,35,IT,70000,7,original Salary,70000,70000,35,7
6,Vikas,29,Finance,60000,5,original Salary,60000,60000,29,5
7,Pooja,45,HR,55000,8,0,55000,55000,40,7

In [ ]:
Q21

Display the numeric columns using:

select_dtypes()
Q22

Display only the object/text columns.

Q23

Convert Department to:

category

using astype().

Q24

Convert Age to:

float

using astype().

In [174]:
'''Q21

Display the numeric columns using:

select_dtypes()'''
df.select_dtypes(include="number")

,Age,Salary,Experience,Salary_Capped,min_and_max_caped,Age_caped,Experience_Capped
0,25,50000,2,50000,50000,25,2
1,32,65000,6,65000,65000,32,6
2,28,45000,3,45000,45000,28,3
3,41,80000,10,70000,75000,40,7
4,24,40000,1,40000,45000,24,1
5,35,70000,7,70000,70000,35,7
6,29,60000,5,60000,60000,29,5
7,45,55000,8,55000,55000,40,7

In [176]:
'''Q22

Display only the object/text columns.'''
df.select_dtypes(include="object")

    Name Department    Salary_Status
0  Rahul         IT                0
1  Priya         HR  original Salary
2   Amit         IT                0
3   Neha    Finance  original Salary
4  Rohit         HR                0
5  Sneha         IT  original Salary
6  Vikas    Finance  original Salary
7  Pooja         HR                0

In [188]:
'''Q23

Convert Department to:

category

using astype().
'''
df["Category"]=df["Department"].astype("category")
df

,Name,Age,Department,Salary,Experience,Salary_Status,Salary_Capped,min_and_max_caped,Age_caped,Experience_Capped,Category
0,Rahul,25,IT,50000,2,0,50000,50000,25,2,IT
1,Priya,32,HR,65000,6,original Salary,65000,65000,32,6,HR
2,Amit,28,IT,45000,3,0,45000,45000,28,3,IT
3,Neha,41,Finance,80000,10,original Salary,70000,75000,40,7,Finance
4,Rohit,24,HR,40000,1,0,40000,45000,24,1,HR
5,Sneha,35,IT,70000,7,original Salary,70000,70000,35,7,IT
6,Vikas,29,Finance,60000,5,original Salary,60000,60000,29,5,Finance
7,Pooja,45,HR,55000,8,0,55000,55000,40,7,HR

In [190]:
'''Q24

Convert Age to:

float

using astype().'''
df["Age"].astype(float)

0    25.0
1    32.0
2    28.0
3    41.0
4    24.0
5    35.0
6    29.0
7    45.0
Name: Age, dtype: float64