In [286]:
#datetime and time series

In [288]:
import pandas as pd

data = {
    "Order_ID": [
        1001, 1002, 1003, 1004, 1005,
        1006, 1007, 1008, 1009, 1010,
        1011, 1012
    ],

    "Order_Date": [
        "2026-01-05",
        "2026-01-12",
        "2026-01-20",
        "2026-02-03",
        "2026-02-15",
        "2026-02-28",
        "2026-03-05",
        "2026-03-12",
        "2026-03-25",
        "2026-04-02",
        "2026-04-15",
        "2026-04-28"
    ],

    "Customer": [
        "Rahul", "Priya", "Amit", "Neha",
        "Rohit", "Sneha", "Vikas", "Pooja",
        "Karan", "Anjali", "Manish", "Kavita"
    ],

    "Category": [
        "Laptop", "Mobile", "Laptop", "Tablet",
        "Mobile", "Laptop", "Tablet", "Mobile",
        "Laptop", "Mobile", "Tablet", "Laptop"
    ],

    "Sales": [
        50000, 25000, 55000, 30000,
        28000, 60000, 32000, 27000,
        65000, 30000, 35000, 70000
    ],

    "Quantity": [
        1, 2, 1, 1,
        2, 1, 2, 1,
        1, 2, 1, 1
    ]
}

df = pd.DataFrame(data)
df

    Order_ID  Order_Date Customer Category  Sales  Quantity
0       1001  2026-01-05    Rahul   Laptop  50000         1
1       1002  2026-01-12    Priya   Mobile  25000         2
2       1003  2026-01-20     Amit   Laptop  55000         1
3       1004  2026-02-03     Neha   Tablet  30000         1
4       1005  2026-02-15    Rohit   Mobile  28000         2
5       1006  2026-02-28    Sneha   Laptop  60000         1
6       1007  2026-03-05    Vikas   Tablet  32000         2
7       1008  2026-03-12    Pooja   Mobile  27000         1
8       1009  2026-03-25    Karan   Laptop  65000         1
9       1010  2026-04-02   Anjali   Mobile  30000         2
10      1011  2026-04-15   Manish   Tablet  35000         1
11      1012  2026-04-28   Kavita   Laptop  70000         1

In [290]:
df["Order_Date"].dtypes

dtype('O')

In [292]:
df["Order_Date"]=pd.to_datetime(df["Order_Date"])
df

    Order_ID Order_Date Customer Category  Sales  Quantity
0       1001 2026-01-05    Rahul   Laptop  50000         1
1       1002 2026-01-12    Priya   Mobile  25000         2
2       1003 2026-01-20     Amit   Laptop  55000         1
3       1004 2026-02-03     Neha   Tablet  30000         1
4       1005 2026-02-15    Rohit   Mobile  28000         2
5       1006 2026-02-28    Sneha   Laptop  60000         1
6       1007 2026-03-05    Vikas   Tablet  32000         2
7       1008 2026-03-12    Pooja   Mobile  27000         1
8       1009 2026-03-25    Karan   Laptop  65000         1
9       1010 2026-04-02   Anjali   Mobile  30000         2
10      1011 2026-04-15   Manish   Tablet  35000         1
11      1012 2026-04-28   Kavita   Laptop  70000         1

In [ ]:
extract year

In [294]:
df["Year"]=df["Order_Date"].dt.year
df

    Order_ID Order_Date Customer Category  Sales  Quantity  Year
0       1001 2026-01-05    Rahul   Laptop  50000         1  2026
1       1002 2026-01-12    Priya   Mobile  25000         2  2026
2       1003 2026-01-20     Amit   Laptop  55000         1  2026
3       1004 2026-02-03     Neha   Tablet  30000         1  2026
4       1005 2026-02-15    Rohit   Mobile  28000         2  2026
5       1006 2026-02-28    Sneha   Laptop  60000         1  2026
6       1007 2026-03-05    Vikas   Tablet  32000         2  2026
7       1008 2026-03-12    Pooja   Mobile  27000         1  2026
8       1009 2026-03-25    Karan   Laptop  65000         1  2026
9       1010 2026-04-02   Anjali   Mobile  30000         2  2026
10      1011 2026-04-15   Manish   Tablet  35000         1  2026
11      1012 2026-04-28   Kavita   Laptop  70000         1  2026

In [ ]:
#extract month

In [296]:
df["Month"]=df["Order_Date"].dt.month
df

    Order_ID Order_Date Customer Category  Sales  Quantity  Year  Month
0       1001 2026-01-05    Rahul   Laptop  50000         1  2026      1
1       1002 2026-01-12    Priya   Mobile  25000         2  2026      1
2       1003 2026-01-20     Amit   Laptop  55000         1  2026      1
3       1004 2026-02-03     Neha   Tablet  30000         1  2026      2
4       1005 2026-02-15    Rohit   Mobile  28000         2  2026      2
5       1006 2026-02-28    Sneha   Laptop  60000         1  2026      2
6       1007 2026-03-05    Vikas   Tablet  32000         2  2026      3
7       1008 2026-03-12    Pooja   Mobile  27000         1  2026      3
8       1009 2026-03-25    Karan   Laptop  65000         1  2026      3
9       1010 2026-04-02   Anjali   Mobile  30000         2  2026      4
10      1011 2026-04-15   Manish   Tablet  35000         1  2026      4
11      1012 2026-04-28   Kavita   Laptop  70000         1  2026      4

In [ ]:
month_name()

In [298]:
df["Month_Name"]=df["Order_Date"].dt.month_name()
df

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name
0,1001,2026-01-05,Rahul,Laptop,50000,1,2026,1,January
1,1002,2026-01-12,Priya,Mobile,25000,2,2026,1,January
2,1003,2026-01-20,Amit,Laptop,55000,1,2026,1,January
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April

In [ ]:
day

In [300]:
df["Day"]=df["Order_Date"].dt.day
df

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day
0,1001,2026-01-05,Rahul,Laptop,50000,1,2026,1,January,5
1,1002,2026-01-12,Priya,Mobile,25000,2,2026,1,January,12
2,1003,2026-01-20,Amit,Laptop,55000,1,2026,1,January,20
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,3
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,15
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,28
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,5
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,12
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,25
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April,2
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April,15
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April,28

In [ ]:
day_name()

In [302]:
df["Day_Name"]=df["Order_Date"].dt.day_name()
df

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day,Day_Name
0,1001,2026-01-05,Rahul,Laptop,50000,1,2026,1,January,5,Monday
1,1002,2026-01-12,Priya,Mobile,25000,2,2026,1,January,12,Monday
2,1003,2026-01-20,Amit,Laptop,55000,1,2026,1,January,20,Tuesday
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,3,Tuesday
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,15,Sunday
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,28,Saturday
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,5,Thursday
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,12,Thursday
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,25,Wednesday
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April,2,Thursday
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April,15,Wednesday
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April,28,Tuesday

In [ ]:
Quarter

In [304]:
df["Quarter"]=df["Order_Date"].dt.quarter
df

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day,Day_Name,Quarter
0,1001,2026-01-05,Rahul,Laptop,50000,1,2026,1,January,5,Monday,1
1,1002,2026-01-12,Priya,Mobile,25000,2,2026,1,January,12,Monday,1
2,1003,2026-01-20,Amit,Laptop,55000,1,2026,1,January,20,Tuesday,1
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,3,Tuesday,1
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,15,Sunday,1
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,28,Saturday,1
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,5,Thursday,1
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,12,Thursday,1
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,25,Wednesday,1
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April,2,Thursday,2
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April,15,Wednesday,2
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April,28,Tuesday,2

In [ ]:
week number-reporing for weekly

In [306]:
df["Week_Number"]=df["Order_Date"].dt.isocalendar().week
df

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day,Day_Name,Quarter,Week_Number
0,1001,2026-01-05,Rahul,Laptop,50000,1,2026,1,January,5,Monday,1,2
1,1002,2026-01-12,Priya,Mobile,25000,2,2026,1,January,12,Monday,1,3
2,1003,2026-01-20,Amit,Laptop,55000,1,2026,1,January,20,Tuesday,1,4
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,3,Tuesday,1,6
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,15,Sunday,1,7
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,28,Saturday,1,9
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,5,Thursday,1,10
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,12,Thursday,1,11
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,25,Wednesday,1,13
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April,2,Thursday,2,14
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April,15,Wednesday,2,16
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April,28,Tuesday,2,18

In [ ]:
date filtering-Suppose we want orders after March 1:

In [308]:
df[
df["Order_Date"]>'2026-03-01'
]

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day,Day_Name,Quarter,Week_Number
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,5,Thursday,1,10
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,12,Thursday,1,11
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,25,Wednesday,1,13
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April,2,Thursday,2,14
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April,15,Wednesday,2,16
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April,28,Tuesday,2,18

In [ ]:
filter between two dates

In [310]:
df[
(df["Order_Date"]>='2026-02-01') &
(df["Order_Date"]<='2026-03-31')
]

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day,Day_Name,Quarter,Week_Number
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,3,Tuesday,1,6
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,15,Sunday,1,7
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,28,Saturday,1,9
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,5,Thursday,1,10
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,12,Thursday,1,11
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,25,Wednesday,1,13

In [ ]:
between()

In [312]:
df[
df["Order_Date"].between(
    '2026-02-01',
    '2026-03-31'
)
]

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day,Day_Name,Quarter,Week_Number
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,3,Tuesday,1,6
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,15,Sunday,1,7
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,28,Saturday,1,9
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,5,Thursday,1,10
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,12,Thursday,1,11
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,25,Wednesday,1,13

In [ ]:
sort values

In [314]:
df.sort_values("Order_Date")

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day,Day_Name,Quarter,Week_Number
0,1001,2026-01-05,Rahul,Laptop,50000,1,2026,1,January,5,Monday,1,2
1,1002,2026-01-12,Priya,Mobile,25000,2,2026,1,January,12,Monday,1,3
2,1003,2026-01-20,Amit,Laptop,55000,1,2026,1,January,20,Tuesday,1,4
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,3,Tuesday,1,6
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,15,Sunday,1,7
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,28,Saturday,1,9
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,5,Thursday,1,10
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,12,Thursday,1,11
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,25,Wednesday,1,13
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April,2,Thursday,2,14
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April,15,Wednesday,2,16
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April,28,Tuesday,2,18

In [316]:
df.sort_values("Order_Date",ascending=False)

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day,Day_Name,Quarter,Week_Number
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April,28,Tuesday,2,18
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April,15,Wednesday,2,16
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April,2,Thursday,2,14
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,25,Wednesday,1,13
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,12,Thursday,1,11
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,5,Thursday,1,10
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,28,Saturday,1,9
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,15,Sunday,1,7
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,3,Tuesday,1,6
2,1003,2026-01-20,Amit,Laptop,55000,1,2026,1,January,20,Tuesday,1,4
1,1002,2026-01-12,Priya,Mobile,25000,2,2026,1,January,12,Monday,1,3
0,1001,2026-01-05,Rahul,Laptop,50000,1,2026,1,January,5,Monday,1,2

In [ ]:
date difference

In [318]:
df["Delivery_Date"] = pd.to_datetime([
    "2026-01-08",
    "2026-01-16",
    "2026-01-25",
    "2026-02-06",
    "2026-02-18",
    "2026-03-03",
    "2026-03-09",
    "2026-03-15",
    "2026-03-29",
    "2026-04-05",
    "2026-04-19",
    "2026-05-02"
])
df

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day,Day_Name,Quarter,Week_Number,Delivery_Date
0,1001,2026-01-05,Rahul,Laptop,50000,1,2026,1,January,5,Monday,1,2,2026-01-08
1,1002,2026-01-12,Priya,Mobile,25000,2,2026,1,January,12,Monday,1,3,2026-01-16
2,1003,2026-01-20,Amit,Laptop,55000,1,2026,1,January,20,Tuesday,1,4,2026-01-25
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,3,Tuesday,1,6,2026-02-06
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,15,Sunday,1,7,2026-02-18
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,28,Saturday,1,9,2026-03-03
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,5,Thursday,1,10,2026-03-09
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,12,Thursday,1,11,2026-03-15
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,25,Wednesday,1,13,2026-03-29
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April,2,Thursday,2,14,2026-04-05
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April,15,Wednesday,2,16,2026-04-19
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April,28,Tuesday,2,18,2026-05-02

In [320]:
df["Delivery_Days"]=(df["Delivery_Date"]-df["Order_Date"]).dt.days
df

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day,Day_Name,Quarter,Week_Number,Delivery_Date,Delivery_Days
0,1001,2026-01-05,Rahul,Laptop,50000,1,2026,1,January,5,Monday,1,2,2026-01-08,3
1,1002,2026-01-12,Priya,Mobile,25000,2,2026,1,January,12,Monday,1,3,2026-01-16,4
2,1003,2026-01-20,Amit,Laptop,55000,1,2026,1,January,20,Tuesday,1,4,2026-01-25,5
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,3,Tuesday,1,6,2026-02-06,3
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,15,Sunday,1,7,2026-02-18,3
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,28,Saturday,1,9,2026-03-03,3
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,5,Thursday,1,10,2026-03-09,4
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,12,Thursday,1,11,2026-03-15,3
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,25,Wednesday,1,13,2026-03-29,4
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April,2,Thursday,2,14,2026-04-05,3
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April,15,Wednesday,2,16,2026-04-19,4
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April,28,Tuesday,2,18,2026-05-02,4

In [ ]:
find fastest delivery

In [322]:
df["Delivery_Days"].min()

3

In [ ]:
find slowest delivery

In [324]:
df["Delivery_Days"].max()

5

In [ ]:
average delivery time

In [326]:
df["Delivery_Days"].mean()

3.5833333333333335

In [ ]:
monthly sales

In [328]:
df["Month"]=df["Order_Date"].dt.month

In [330]:
df.groupby("Month")["Sales"].sum()

Month
1    130000
2    118000
3    124000
4    135000
Name: Sales, dtype: int64

In [ ]:
monthly sales using resaample()-times based grouping

In [332]:
df=df.set_index("Order_Date")

In [334]:
df["Monthly_Sales"]=df["Sales"].resample("ME").sum()
df

,Order_ID,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day,Day_Name,Quarter,Week_Number,Delivery_Date,Delivery_Days,Monthly_Sales
Order_Date,,,,,,,,,,,,,,,
2026-01-05,1001,Rahul,Laptop,50000,1,2026,1,January,5,Monday,1,2,2026-01-08,3,NaN
2026-01-12,1002,Priya,Mobile,25000,2,2026,1,January,12,Monday,1,3,2026-01-16,4,NaN
2026-01-20,1003,Amit,Laptop,55000,1,2026,1,January,20,Tuesday,1,4,2026-01-25,5,NaN
2026-02-03,1004,Neha,Tablet,30000,1,2026,2,February,3,Tuesday,1,6,2026-02-06,3,NaN
2026-02-15,1005,Rohit,Mobile,28000,2,2026,2,February,15,Sunday,1,7,2026-02-18,3,NaN
2026-02-28,1006,Sneha,Laptop,60000,1,2026,2,February,28,Saturday,1,9,2026-03-03,3,118000.0
2026-03-05,1007,Vikas,Tablet,32000,2,2026,3,March,5,Thursday,1,10,2026-03-09,4,NaN
2026-03-12,1008,Pooja,Mobile,27000,1,2026,3,March,12,Thursday,1,11,2026-03-15,3,NaN
2026-03-25,1009,Karan,Laptop,65000,1,2026,3,March,25,Wednesday,1,13,2026-03-29,4,NaN
2026-04-02,1010,Anjali,Mobile,30000,2,2026,4,April,2,Thursday,2,14,2026-04-05,3,NaN
2026-04-15,1011,Manish,Tablet,35000,1,2026,4,April,15,Wednesday,2,16,2026-04-19,4,NaN
2026-04-28,1012,Kavita,Laptop,70000,1,2026,4,April,28,Tuesday,2,18,2026-05-02,4,NaN

In [ ]:
monthly average sales

In [336]:
df["Monthly_Avg_Sales"]=df["Sales"].resample("ME").mean()
df

,Order_ID,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day,Day_Name,Quarter,Week_Number,Delivery_Date,Delivery_Days,Monthly_Sales,Monthly_Avg_Sales
Order_Date,,,,,,,,,,,,,,,,
2026-01-05,1001,Rahul,Laptop,50000,1,2026,1,January,5,Monday,1,2,2026-01-08,3,NaN,NaN
2026-01-12,1002,Priya,Mobile,25000,2,2026,1,January,12,Monday,1,3,2026-01-16,4,NaN,NaN
2026-01-20,1003,Amit,Laptop,55000,1,2026,1,January,20,Tuesday,1,4,2026-01-25,5,NaN,NaN
2026-02-03,1004,Neha,Tablet,30000,1,2026,2,February,3,Tuesday,1,6,2026-02-06,3,NaN,NaN
2026-02-15,1005,Rohit,Mobile,28000,2,2026,2,February,15,Sunday,1,7,2026-02-18,3,NaN,NaN
2026-02-28,1006,Sneha,Laptop,60000,1,2026,2,February,28,Saturday,1,9,2026-03-03,3,118000.0,39333.333333
2026-03-05,1007,Vikas,Tablet,32000,2,2026,3,March,5,Thursday,1,10,2026-03-09,4,NaN,NaN
2026-03-12,1008,Pooja,Mobile,27000,1,2026,3,March,12,Thursday,1,11,2026-03-15,3,NaN,NaN
2026-03-25,1009,Karan,Laptop,65000,1,2026,3,March,25,Wednesday,1,13,2026-03-29,4,NaN,NaN
2026-04-02,1010,Anjali,Mobile,30000,2,2026,4,April,2,Thursday,2,14,2026-04-05,3,NaN,NaN
2026-04-15,1011,Manish,Tablet,35000,1,2026,4,April,15,Wednesday,2,16,2026-04-19,4,NaN,NaN
2026-04-28,1012,Kavita,Laptop,70000,1,2026,4,April,28,Tuesday,2,18,2026-05-02,4,NaN,NaN

In [ ]:
Rolling Average -daily sales

In [338]:
df["Rolling_3"]=df["Sales"].rolling(3).mean()
df

,Order_ID,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day,Day_Name,Quarter,Week_Number,Delivery_Date,Delivery_Days,Monthly_Sales,Monthly_Avg_Sales,Rolling_3
Order_Date,,,,,,,,,,,,,,,,,
2026-01-05,1001,Rahul,Laptop,50000,1,2026,1,January,5,Monday,1,2,2026-01-08,3,NaN,NaN,NaN
2026-01-12,1002,Priya,Mobile,25000,2,2026,1,January,12,Monday,1,3,2026-01-16,4,NaN,NaN,NaN
2026-01-20,1003,Amit,Laptop,55000,1,2026,1,January,20,Tuesday,1,4,2026-01-25,5,NaN,NaN,43333.333333
2026-02-03,1004,Neha,Tablet,30000,1,2026,2,February,3,Tuesday,1,6,2026-02-06,3,NaN,NaN,36666.666667
2026-02-15,1005,Rohit,Mobile,28000,2,2026,2,February,15,Sunday,1,7,2026-02-18,3,NaN,NaN,37666.666667
2026-02-28,1006,Sneha,Laptop,60000,1,2026,2,February,28,Saturday,1,9,2026-03-03,3,118000.0,39333.333333,39333.333333
2026-03-05,1007,Vikas,Tablet,32000,2,2026,3,March,5,Thursday,1,10,2026-03-09,4,NaN,NaN,40000.000000
2026-03-12,1008,Pooja,Mobile,27000,1,2026,3,March,12,Thursday,1,11,2026-03-15,3,NaN,NaN,39666.666667
2026-03-25,1009,Karan,Laptop,65000,1,2026,3,March,25,Wednesday,1,13,2026-03-29,4,NaN,NaN,41333.333333
2026-04-02,1010,Anjali,Mobile,30000,2,2026,4,April,2,Thursday,2,14,2026-04-05,3,NaN,NaN,40666.666667
2026-04-15,1011,Manish,Tablet,35000,1,2026,4,April,15,Wednesday,2,16,2026-04-19,4,NaN,NaN,43333.333333
2026-04-28,1012,Kavita,Laptop,70000,1,2026,4,April,28,Tuesday,2,18,2026-05-02,4,NaN,NaN,45000.000000

In [ ]:
shift() -

In [340]:
Monthly_Sales["Previous_Sales"]=Monthly_Sales.shift(1)

In [ ]:
df["Monthly_Sales"["Growth_%"]]=Monthly_Sales.pct_change()*100 # monthly growth

In [ ]:
grouping by month +category

In [ ]:
Which product category performs best each month?

In [345]:
df["Month_Name"]=df.index.month_name()

In [347]:
df.groupby(
    ["Month_Name","Category"]
)["Sales"].sum()

Month_Name  Category
April       Laptop       70000
            Mobile       30000
            Tablet       35000
February    Laptop       60000
            Mobile       28000
            Tablet       30000
January     Laptop      105000
            Mobile       25000
March       Laptop       65000
            Mobile       27000
            Tablet       32000
Name: Sales, dtype: int64

In [140]:
import pandas as pd

data = {
    "Order_ID": [
        1001, 1002, 1003, 1004, 1005,
        1006, 1007, 1008, 1009, 1010,
        1011, 1012
    ],

    "Order_Date": [
        "2026-01-05",
        "2026-01-12",
        "2026-01-20",
        "2026-02-03",
        "2026-02-15",
        "2026-02-28",
        "2026-03-05",
        "2026-03-12",
        "2026-03-25",
        "2026-04-02",
        "2026-04-15",
        "2026-04-28"
    ],

    "Customer": [
        "Rahul", "Priya", "Amit", "Neha",
        "Rohit", "Sneha", "Vikas", "Pooja",
        "Karan", "Anjali", "Manish", "Kavita"
    ],

    "Category": [
        "Laptop", "Mobile", "Laptop", "Tablet",
        "Mobile", "Laptop", "Tablet", "Mobile",
        "Laptop", "Mobile", "Tablet", "Laptop"
    ],

    "Sales": [
        50000, 25000, 55000, 30000,
        28000, 60000, 32000, 27000,
        65000, 30000, 35000, 70000
    ],

    "Quantity": [
        1, 2, 1, 1,
        2, 1, 2, 1,
        1, 2, 1, 1
    ]
}

df = pd.DataFrame(data)
df

    Order_ID  Order_Date Customer Category  Sales  Quantity
0       1001  2026-01-05    Rahul   Laptop  50000         1
1       1002  2026-01-12    Priya   Mobile  25000         2
2       1003  2026-01-20     Amit   Laptop  55000         1
3       1004  2026-02-03     Neha   Tablet  30000         1
4       1005  2026-02-15    Rohit   Mobile  28000         2
5       1006  2026-02-28    Sneha   Laptop  60000         1
6       1007  2026-03-05    Vikas   Tablet  32000         2
7       1008  2026-03-12    Pooja   Mobile  27000         1
8       1009  2026-03-25    Karan   Laptop  65000         1
9       1010  2026-04-02   Anjali   Mobile  30000         2
10      1011  2026-04-15   Manish   Tablet  35000         1
11      1012  2026-04-28   Kavita   Laptop  70000         1

In [ ]:
Q1
Convert Order_Date into datetime.
Q2
Create a Year column.
Q3
Create a numeric Month column.
Q4
Create a Month_Name column.
Q5
Create a Day_Name column.

In [ ]:
Q1
Convert Order_Date into datetime.

In [142]:
df["Order_Date"]=pd.to_datetime(df["Order_Date"])
df

    Order_ID Order_Date Customer Category  Sales  Quantity
0       1001 2026-01-05    Rahul   Laptop  50000         1
1       1002 2026-01-12    Priya   Mobile  25000         2
2       1003 2026-01-20     Amit   Laptop  55000         1
3       1004 2026-02-03     Neha   Tablet  30000         1
4       1005 2026-02-15    Rohit   Mobile  28000         2
5       1006 2026-02-28    Sneha   Laptop  60000         1
6       1007 2026-03-05    Vikas   Tablet  32000         2
7       1008 2026-03-12    Pooja   Mobile  27000         1
8       1009 2026-03-25    Karan   Laptop  65000         1
9       1010 2026-04-02   Anjali   Mobile  30000         2
10      1011 2026-04-15   Manish   Tablet  35000         1
11      1012 2026-04-28   Kavita   Laptop  70000         1

In [144]:
df.dtypes

Order_ID               int64
Order_Date    datetime64[ns]
Customer              object
Category              object
Sales                  int64
Quantity               int64
dtype: object

In [ ]:
Q2
Create a Year column.

In [146]:
df["Year"]=df["Order_Date"].dt.year
df

    Order_ID Order_Date Customer Category  Sales  Quantity  Year
0       1001 2026-01-05    Rahul   Laptop  50000         1  2026
1       1002 2026-01-12    Priya   Mobile  25000         2  2026
2       1003 2026-01-20     Amit   Laptop  55000         1  2026
3       1004 2026-02-03     Neha   Tablet  30000         1  2026
4       1005 2026-02-15    Rohit   Mobile  28000         2  2026
5       1006 2026-02-28    Sneha   Laptop  60000         1  2026
6       1007 2026-03-05    Vikas   Tablet  32000         2  2026
7       1008 2026-03-12    Pooja   Mobile  27000         1  2026
8       1009 2026-03-25    Karan   Laptop  65000         1  2026
9       1010 2026-04-02   Anjali   Mobile  30000         2  2026
10      1011 2026-04-15   Manish   Tablet  35000         1  2026
11      1012 2026-04-28   Kavita   Laptop  70000         1  2026

In [ ]:
Q3
Create a numeric Month column.

In [148]:
df["Month"]=df["Order_Date"].dt.month
df

    Order_ID Order_Date Customer Category  Sales  Quantity  Year  Month
0       1001 2026-01-05    Rahul   Laptop  50000         1  2026      1
1       1002 2026-01-12    Priya   Mobile  25000         2  2026      1
2       1003 2026-01-20     Amit   Laptop  55000         1  2026      1
3       1004 2026-02-03     Neha   Tablet  30000         1  2026      2
4       1005 2026-02-15    Rohit   Mobile  28000         2  2026      2
5       1006 2026-02-28    Sneha   Laptop  60000         1  2026      2
6       1007 2026-03-05    Vikas   Tablet  32000         2  2026      3
7       1008 2026-03-12    Pooja   Mobile  27000         1  2026      3
8       1009 2026-03-25    Karan   Laptop  65000         1  2026      3
9       1010 2026-04-02   Anjali   Mobile  30000         2  2026      4
10      1011 2026-04-15   Manish   Tablet  35000         1  2026      4
11      1012 2026-04-28   Kavita   Laptop  70000         1  2026      4

In [ ]:
Q4
Create a Month_Name column.

In [150]:
df["Month_Name"]=df["Order_Date"].dt.month_name()
df

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name
0,1001,2026-01-05,Rahul,Laptop,50000,1,2026,1,January
1,1002,2026-01-12,Priya,Mobile,25000,2,2026,1,January
2,1003,2026-01-20,Amit,Laptop,55000,1,2026,1,January
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April

In [ ]:
Q5
Create a Day_Name column.

In [152]:
df["Day_Name"]=df["Order_Date"].dt.day_name()
df

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day_Name
0,1001,2026-01-05,Rahul,Laptop,50000,1,2026,1,January,Monday
1,1002,2026-01-12,Priya,Mobile,25000,2,2026,1,January,Monday
2,1003,2026-01-20,Amit,Laptop,55000,1,2026,1,January,Tuesday
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,Tuesday
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,Sunday
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,Saturday
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,Thursday
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,Thursday
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,Wednesday
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April,Thursday
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April,Wednesday
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April,Tuesday

In [ ]:
Q6
Create a Quarter column.
Q7
Create a Week column using ISO week number.
Q8
Find all orders placed after:
2026-03-01

Q9
Find all orders between:
2026-02-01
2026-03-31

Q10
Sort the DataFrame from oldest order to newest order.

In [ ]:
Q6
Create a Quarter column.

In [154]:
df["Quarter"]=df["Order_Date"].dt.quarter
df

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day_Name,Quarter
0,1001,2026-01-05,Rahul,Laptop,50000,1,2026,1,January,Monday,1
1,1002,2026-01-12,Priya,Mobile,25000,2,2026,1,January,Monday,1
2,1003,2026-01-20,Amit,Laptop,55000,1,2026,1,January,Tuesday,1
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,Tuesday,1
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,Sunday,1
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,Saturday,1
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,Thursday,1
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,Thursday,1
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,Wednesday,1
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April,Thursday,2
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April,Wednesday,2
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April,Tuesday,2

In [ ]:
Q7
Create a Week column using ISO week number.

In [156]:
df["Week"]=df["Order_Date"].dt.isocalendar().week
df

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day_Name,Quarter,Week
0,1001,2026-01-05,Rahul,Laptop,50000,1,2026,1,January,Monday,1,2
1,1002,2026-01-12,Priya,Mobile,25000,2,2026,1,January,Monday,1,3
2,1003,2026-01-20,Amit,Laptop,55000,1,2026,1,January,Tuesday,1,4
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,Tuesday,1,6
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,Sunday,1,7
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,Saturday,1,9
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,Thursday,1,10
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,Thursday,1,11
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,Wednesday,1,13
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April,Thursday,2,14
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April,Wednesday,2,16
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April,Tuesday,2,18

In [ ]:
Q8
Find all orders placed after:
2026-03-01

In [158]:
df[
df["Order_Date"]>'2026-03-01'
]

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day_Name,Quarter,Week
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,Thursday,1,10
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,Thursday,1,11
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,Wednesday,1,13
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April,Thursday,2,14
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April,Wednesday,2,16
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April,Tuesday,2,18

In [ ]:
Q9
Find all orders between:
2026-02-01
2026-03-31

In [160]:
df[
(df["Order_Date"]>='2026-02-01') &
(df["Order_Date"]<='2026-03-31')
]

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day_Name,Quarter,Week
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,Tuesday,1,6
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,Sunday,1,7
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,Saturday,1,9
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,Thursday,1,10
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,Thursday,1,11
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,Wednesday,1,13

In [ ]:
Q10
Sort the DataFrame from oldest order to newest order

In [162]:
df.sort_values("Order_Date",ascending=False)

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day_Name,Quarter,Week
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April,Tuesday,2,18
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April,Wednesday,2,16
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April,Thursday,2,14
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,Wednesday,1,13
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,Thursday,1,11
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,Thursday,1,10
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,Saturday,1,9
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,Sunday,1,7
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,Tuesday,1,6
2,1003,2026-01-20,Amit,Laptop,55000,1,2026,1,January,Tuesday,1,4
1,1002,2026-01-12,Priya,Mobile,25000,2,2026,1,January,Monday,1,3
0,1001,2026-01-05,Rahul,Laptop,50000,1,2026,1,January,Monday,1,2

In [ ]:
First add the Delivery_Date column from the example above.
Q11
Calculate Delivery_Days.
Q12
Find the fastest delivery.
Q13
Find the slowest delivery.
Q14
Calculate average delivery time.
Q15
Find all orders that took more than 5 days to deliver.

In [190]:
df["Delivery_Date"] = pd.to_datetime([
    "2026-01-08",
    "2026-01-16",
    "2026-01-25",
    "2026-02-06",
    "2026-02-18",
    "2026-03-03",
    "2026-03-09",
    "2026-03-15",
    "2026-03-29",
    "2026-04-05",
    "2026-04-19",
    "2026-05-02"
])
df

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day_Name,Quarter,Week,Delivery_Date,Delivery_Days
0,1001,2026-01-05,Rahul,Laptop,50000,1,2026,1,January,Monday,1,2,2026-01-08,0
1,1002,2026-01-12,Priya,Mobile,25000,2,2026,1,January,Monday,1,3,2026-01-16,0
2,1003,2026-01-20,Amit,Laptop,55000,1,2026,1,January,Tuesday,1,4,2026-01-25,0
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,Tuesday,1,6,2026-02-06,0
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,Sunday,1,7,2026-02-18,0
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,Saturday,1,9,2026-03-03,0
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,Thursday,1,10,2026-03-09,0
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,Thursday,1,11,2026-03-15,0
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,Wednesday,1,13,2026-03-29,0
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April,Thursday,2,14,2026-04-05,0
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April,Wednesday,2,16,2026-04-19,0
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April,Tuesday,2,18,2026-05-02,0

In [ ]:
Q11
Calculate Delivery_Days.

In [188]:
df["Delivery_Days"]=(df["Delivery_Date"]-df["Order_Date"]).dt.days
df

,Order_ID,Order_Date,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day_Name,Quarter,Week,Delivery_Date,Delivery_Days
0,1001,2026-01-05,Rahul,Laptop,50000,1,2026,1,January,Monday,1,2,2026-01-05,0
1,1002,2026-01-12,Priya,Mobile,25000,2,2026,1,January,Monday,1,3,2026-01-12,0
2,1003,2026-01-20,Amit,Laptop,55000,1,2026,1,January,Tuesday,1,4,2026-01-20,0
3,1004,2026-02-03,Neha,Tablet,30000,1,2026,2,February,Tuesday,1,6,2026-02-03,0
4,1005,2026-02-15,Rohit,Mobile,28000,2,2026,2,February,Sunday,1,7,2026-02-15,0
5,1006,2026-02-28,Sneha,Laptop,60000,1,2026,2,February,Saturday,1,9,2026-02-28,0
6,1007,2026-03-05,Vikas,Tablet,32000,2,2026,3,March,Thursday,1,10,2026-03-05,0
7,1008,2026-03-12,Pooja,Mobile,27000,1,2026,3,March,Thursday,1,11,2026-03-12,0
8,1009,2026-03-25,Karan,Laptop,65000,1,2026,3,March,Wednesday,1,13,2026-03-25,0
9,1010,2026-04-02,Anjali,Mobile,30000,2,2026,4,April,Thursday,2,14,2026-04-02,0
10,1011,2026-04-15,Manish,Tablet,35000,1,2026,4,April,Wednesday,2,16,2026-04-15,0
11,1012,2026-04-28,Kavita,Laptop,70000,1,2026,4,April,Tuesday,2,18,2026-04-28,0

In [ ]:
Q12
Find the fastest delivery.

In [186]:
df["Delivery_Days"].min()

0

In [ ]:
Q13
Find the slowest delivery.

In [192]:
df["Delivery_Days"].max()

0

In [ ]:
Q14
Calculate average delivery time.

In [194]:
df["Delivery_Days"].mean()

0.0

In [ ]:

Q15
Find all orders that took more than 5 days to deliver.

In [198]:
df["Delivery_Days"]>5

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
Name: Delivery_Days, dtype: bool

In [ ]:
Q16
Calculate total sales for each month using:
groupby()


Q17
Calculate monthly average sales.
Q18
Set Order_Date as the index and calculate monthly sales using:
resample()


Q19
Calculate the previous month's sales.
Q20
Calculate month-over-month sales growth percentage.

In [ ]:
Q16
Calculate total sales for each month using:
groupby()

In [200]:
df["Month"]=df["Order_Date"].dt.month

In [202]:
df.groupby("Month")["Sales"].sum()

Month
1    130000
2    118000
3    124000
4    135000
Name: Sales, dtype: int64

In [ ]:

Q17
Calculate monthly average sales.

In [204]:
df.groupby("Month")["Sales"].mean()

Month
1    43333.333333
2    39333.333333
3    41333.333333
4    45000.000000
Name: Sales, dtype: float64

In [ ]:
Q18
Set Order_Date as the index and calculate monthly sales using:
resample()

In [206]:
df=df.set_index("Order_Date")

In [210]:
df["Monthly_Sales"]=df["Sales"].resample("ME").sum()
df

,Order_ID,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day_Name,Quarter,Week,Delivery_Date,Delivery_Days,Monthly_Sales
Order_Date,,,,,,,,,,,,,,
2026-01-05,1001,Rahul,Laptop,50000,1,2026,1,January,Monday,1,2,2026-01-08,0,NaN
2026-01-12,1002,Priya,Mobile,25000,2,2026,1,January,Monday,1,3,2026-01-16,0,NaN
2026-01-20,1003,Amit,Laptop,55000,1,2026,1,January,Tuesday,1,4,2026-01-25,0,NaN
2026-02-03,1004,Neha,Tablet,30000,1,2026,2,February,Tuesday,1,6,2026-02-06,0,NaN
2026-02-15,1005,Rohit,Mobile,28000,2,2026,2,February,Sunday,1,7,2026-02-18,0,NaN
2026-02-28,1006,Sneha,Laptop,60000,1,2026,2,February,Saturday,1,9,2026-03-03,0,118000.0
2026-03-05,1007,Vikas,Tablet,32000,2,2026,3,March,Thursday,1,10,2026-03-09,0,NaN
2026-03-12,1008,Pooja,Mobile,27000,1,2026,3,March,Thursday,1,11,2026-03-15,0,NaN
2026-03-25,1009,Karan,Laptop,65000,1,2026,3,March,Wednesday,1,13,2026-03-29,0,NaN
2026-04-02,1010,Anjali,Mobile,30000,2,2026,4,April,Thursday,2,14,2026-04-05,0,NaN
2026-04-15,1011,Manish,Tablet,35000,1,2026,4,April,Wednesday,2,16,2026-04-19,0,NaN
2026-04-28,1012,Kavita,Laptop,70000,1,2026,4,April,Tuesday,2,18,2026-05-02,0,NaN

In [ ]:
Q19
Calculate the previous month's sales.

In [220]:
df["Previous_Month"]=df["Sales"].shift(1)
df

,Order_ID,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day_Name,Quarter,Week,Delivery_Date,Delivery_Days,Monthly_Sales,Previous_Month
Order_Date,,,,,,,,,,,,,,,
2026-01-05,1001,Rahul,Laptop,50000,1,2026,1,January,Monday,1,2,2026-01-08,0,NaN,NaN
2026-01-12,1002,Priya,Mobile,25000,2,2026,1,January,Monday,1,3,2026-01-16,0,NaN,50000.0
2026-01-20,1003,Amit,Laptop,55000,1,2026,1,January,Tuesday,1,4,2026-01-25,0,NaN,25000.0
2026-02-03,1004,Neha,Tablet,30000,1,2026,2,February,Tuesday,1,6,2026-02-06,0,NaN,55000.0
2026-02-15,1005,Rohit,Mobile,28000,2,2026,2,February,Sunday,1,7,2026-02-18,0,NaN,30000.0
2026-02-28,1006,Sneha,Laptop,60000,1,2026,2,February,Saturday,1,9,2026-03-03,0,118000.0,28000.0
2026-03-05,1007,Vikas,Tablet,32000,2,2026,3,March,Thursday,1,10,2026-03-09,0,NaN,60000.0
2026-03-12,1008,Pooja,Mobile,27000,1,2026,3,March,Thursday,1,11,2026-03-15,0,NaN,32000.0
2026-03-25,1009,Karan,Laptop,65000,1,2026,3,March,Wednesday,1,13,2026-03-29,0,NaN,27000.0
2026-04-02,1010,Anjali,Mobile,30000,2,2026,4,April,Thursday,2,14,2026-04-05,0,NaN,65000.0
2026-04-15,1011,Manish,Tablet,35000,1,2026,4,April,Wednesday,2,16,2026-04-19,0,NaN,30000.0
2026-04-28,1012,Kavita,Laptop,70000,1,2026,4,April,Tuesday,2,18,2026-05-02,0,NaN,35000.0

In [ ]:
Q20
Calculate month-over-month sales growth percentage.

In [226]:
df["Growth_%"]=df["Sales"].pct_change()*100
df

,Order_ID,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day_Name,Quarter,Week,Delivery_Date,Delivery_Days,Monthly_Sales,Previous_Month,Monthly_Avg_Sales,Growth_%
Order_Date,,,,,,,,,,,,,,,,,
2026-01-05,1001,Rahul,Laptop,50000,1,2026,1,January,Monday,1,2,2026-01-08,0,NaN,NaN,NaN,NaN
2026-01-12,1002,Priya,Mobile,25000,2,2026,1,January,Monday,1,3,2026-01-16,0,NaN,50000.0,NaN,-50.000000
2026-01-20,1003,Amit,Laptop,55000,1,2026,1,January,Tuesday,1,4,2026-01-25,0,NaN,25000.0,NaN,120.000000
2026-02-03,1004,Neha,Tablet,30000,1,2026,2,February,Tuesday,1,6,2026-02-06,0,NaN,55000.0,NaN,-45.454545
2026-02-15,1005,Rohit,Mobile,28000,2,2026,2,February,Sunday,1,7,2026-02-18,0,NaN,30000.0,NaN,-6.666667
2026-02-28,1006,Sneha,Laptop,60000,1,2026,2,February,Saturday,1,9,2026-03-03,0,118000.0,28000.0,39333.333333,114.285714
2026-03-05,1007,Vikas,Tablet,32000,2,2026,3,March,Thursday,1,10,2026-03-09,0,NaN,60000.0,NaN,-46.666667
2026-03-12,1008,Pooja,Mobile,27000,1,2026,3,March,Thursday,1,11,2026-03-15,0,NaN,32000.0,NaN,-15.625000
2026-03-25,1009,Karan,Laptop,65000,1,2026,3,March,Wednesday,1,13,2026-03-29,0,NaN,27000.0,NaN,140.740741
2026-04-02,1010,Anjali,Mobile,30000,2,2026,4,April,Thursday,2,14,2026-04-05,0,NaN,65000.0,NaN,-53.846154
2026-04-15,1011,Manish,Tablet,35000,1,2026,4,April,Wednesday,2,16,2026-04-19,0,NaN,30000.0,NaN,16.666667
2026-04-28,1012,Kavita,Laptop,70000,1,2026,4,April,Tuesday,2,18,2026-05-02,0,NaN,35000.0,NaN,100.000000

In [ ]:
Q21
Calculate a 3-period rolling average of sales.
Q22
Find which month has the highest total sales.
Q23
Find total sales by:
Month + Category

Q24 💼
Management asks:
"Which category generated the highest sales?"

Calculate total sales by category and identify the top category.

In [ ]:
Q21
Calculate a 3-period rolling average of sales.

In [259]:
df["Rolling_3"]=df["Sales"].rolling(3).mean()
df

,Order_ID,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day_Name,Quarter,Week,Delivery_Date,Delivery_Days,Monthly_Sales,Previous_Month,Monthly_Avg_Sales,Growth_%,Rolling_3
Order_Date,,,,,,,,,,,,,,,,,,
2026-01-05,1001,Rahul,Laptop,50000,1,2026,1,January,Monday,1,2,2026-01-08,0,NaN,NaN,NaN,NaN,NaN
2026-01-12,1002,Priya,Mobile,25000,2,2026,1,January,Monday,1,3,2026-01-16,0,NaN,50000.0,NaN,-50.000000,NaN
2026-01-20,1003,Amit,Laptop,55000,1,2026,1,January,Tuesday,1,4,2026-01-25,0,NaN,25000.0,NaN,120.000000,43333.333333
2026-02-03,1004,Neha,Tablet,30000,1,2026,2,February,Tuesday,1,6,2026-02-06,0,NaN,55000.0,NaN,-45.454545,36666.666667
2026-02-15,1005,Rohit,Mobile,28000,2,2026,2,February,Sunday,1,7,2026-02-18,0,NaN,30000.0,NaN,-6.666667,37666.666667
2026-02-28,1006,Sneha,Laptop,60000,1,2026,2,February,Saturday,1,9,2026-03-03,0,118000.0,28000.0,39333.333333,114.285714,39333.333333
2026-03-05,1007,Vikas,Tablet,32000,2,2026,3,March,Thursday,1,10,2026-03-09,0,NaN,60000.0,NaN,-46.666667,40000.000000
2026-03-12,1008,Pooja,Mobile,27000,1,2026,3,March,Thursday,1,11,2026-03-15,0,NaN,32000.0,NaN,-15.625000,39666.666667
2026-03-25,1009,Karan,Laptop,65000,1,2026,3,March,Wednesday,1,13,2026-03-29,0,NaN,27000.0,NaN,140.740741,41333.333333
2026-04-02,1010,Anjali,Mobile,30000,2,2026,4,April,Thursday,2,14,2026-04-05,0,NaN,65000.0,NaN,-53.846154,40666.666667
2026-04-15,1011,Manish,Tablet,35000,1,2026,4,April,Wednesday,2,16,2026-04-19,0,NaN,30000.0,NaN,16.666667,43333.333333
2026-04-28,1012,Kavita,Laptop,70000,1,2026,4,April,Tuesday,2,18,2026-05-02,0,NaN,35000.0,NaN,100.000000,45000.000000

In [ ]:
Q22
Find which month has the highest total sales.

In [255]:
df.reset_index(drop=True)

,Order_ID,Customer,Category,Sales,Quantity,Year,Month,Month_Name,Day_Name,Quarter,Week,Delivery_Date,Delivery_Days,Monthly_Sales,Previous_Month,Monthly_Avg_Sales,Growth_%,Rolling_3
0,1001,Rahul,Laptop,50000,1,2026,1,January,Monday,1,2,2026-01-08,0,NaN,NaN,NaN,NaN,NaN
1,1002,Priya,Mobile,25000,2,2026,1,January,Monday,1,3,2026-01-16,0,NaN,50000.0,NaN,-50.000000,NaN
2,1003,Amit,Laptop,55000,1,2026,1,January,Tuesday,1,4,2026-01-25,0,NaN,25000.0,NaN,120.000000,43333.333333
3,1004,Neha,Tablet,30000,1,2026,2,February,Tuesday,1,6,2026-02-06,0,NaN,55000.0,NaN,-45.454545,36666.666667
4,1005,Rohit,Mobile,28000,2,2026,2,February,Sunday,1,7,2026-02-18,0,NaN,30000.0,NaN,-6.666667,37666.666667
5,1006,Sneha,Laptop,60000,1,2026,2,February,Saturday,1,9,2026-03-03,0,118000.0,28000.0,39333.333333,114.285714,39333.333333
6,1007,Vikas,Tablet,32000,2,2026,3,March,Thursday,1,10,2026-03-09,0,NaN,60000.0,NaN,-46.666667,40000.000000
7,1008,Pooja,Mobile,27000,1,2026,3,March,Thursday,1,11,2026-03-15,0,NaN,32000.0,NaN,-15.625000,39666.666667
8,1009,Karan,Laptop,65000,1,2026,3,March,Wednesday,1,13,2026-03-29,0,NaN,27000.0,NaN,140.740741,41333.333333
9,1010,Anjali,Mobile,30000,2,2026,4,April,Thursday,2,14,2026-04-05,0,NaN,65000.0,NaN,-53.846154,40666.666667
10,1011,Manish,Tablet,35000,1,2026,4,April,Wednesday,2,16,2026-04-19,0,NaN,30000.0,NaN,16.666667,43333.333333
11,1012,Kavita,Laptop,70000,1,2026,4,April,Tuesday,2,18,2026-05-02,0,NaN,35000.0,NaN,100.000000,45000.000000

In [270]:
Monthly_Sales=df["Sales"].resample("ME").sum()
higest_sales_month=Monthly_Sales.idxmax()
highest_sales=Monthly_Sales.max()
highest_sales

135000

In [ ]:
Q23
Find total sales by:
Month + Category

In [274]:
df["Month"]=df.index.month_name()

In [276]:
df.groupby(
    ["Month","Category"]
)["Sales"].sum()

Month     Category
April     Laptop       70000
          Mobile       30000
          Tablet       35000
February  Laptop       60000
          Mobile       28000
          Tablet       30000
January   Laptop      105000
          Mobile       25000
March     Laptop       65000
          Mobile       27000
          Tablet       32000
Name: Sales, dtype: int64

In [ ]:
Q24 💼
Management asks:
"Which category generated the highest sales?"

Calculate total sales by category and identify the top category.

In [284]:
df.groupby("Category")["Sales"].sum().idxmax()

'Laptop'