In [1]:
import pandas as pd

data = {
    "Employee": [
        "Rahul", "Priya", "Amit", "Neha",
        "Rohit", "Sneha", "Vikas", "Pooja",
        "Karan", "Anjali"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "IT", "Finance", "HR",
        "IT", "Finance"
    ],

    "Month": [
        "Jan", "Jan", "Jan", "Jan",
        "Feb", "Feb", "Feb", "Feb",
        "Mar", "Mar"
    ],

    "Salary": [
        50000, 65000, 45000, 80000,
        40000, 70000, 60000, 55000,
        75000, 48000
    ],

    "Sales": [
        5000, 7000, 4500, 9000,
        6000, 8000, 5500, 7500,
        6500, 8500
    ]
}

df = pd.DataFrame(data)
df

  Employee Department Month  Salary  Sales
0    Rahul         IT   Jan   50000   5000
1    Priya         HR   Jan   65000   7000
2     Amit         IT   Jan   45000   4500
3     Neha    Finance   Jan   80000   9000
4    Rohit         HR   Feb   40000   6000
5    Sneha         IT   Feb   70000   8000
6    Vikas    Finance   Feb   60000   5500
7    Pooja         HR   Feb   55000   7500
8    Karan         IT   Mar   75000   6500
9   Anjali    Finance   Mar   48000   8500

In [ ]:
How does each employee's salary compare with the average salary of their department?

In [7]:
df["Dept_Avg_Sal"]=df.groupby("Department")["Salary"].transform("mean")
df

  Employee Department Month  Salary  Sales  Dept_Avg_Sal
0    Rahul         IT   Jan   50000   5000  60000.000000
1    Priya         HR   Jan   65000   7000  53333.333333
2     Amit         IT   Jan   45000   4500  60000.000000
3     Neha    Finance   Jan   80000   9000  62666.666667
4    Rohit         HR   Feb   40000   6000  53333.333333
5    Sneha         IT   Feb   70000   8000  60000.000000
6    Vikas    Finance   Feb   60000   5500  62666.666667
7    Pooja         HR   Feb   55000   7500  53333.333333
8    Karan         IT   Mar   75000   6500  60000.000000
9   Anjali    Finance   Mar   48000   8500  62666.666667

In [ ]:
Suppose we want total departmental sales on every employee's row:

In [11]:
df["Dept_Total_Sales"]=df.groupby("Department")["Sales"].transform("sum")
df

  Employee Department Month  Salary  Sales  Dept_Avg_Sal  Dept_Total_Sales
0    Rahul         IT   Jan   50000   5000  60000.000000             24000
1    Priya         HR   Jan   65000   7000  53333.333333             20500
2     Amit         IT   Jan   45000   4500  60000.000000             24000
3     Neha    Finance   Jan   80000   9000  62666.666667             23000
4    Rohit         HR   Feb   40000   6000  53333.333333             20500
5    Sneha         IT   Feb   70000   8000  60000.000000             24000
6    Vikas    Finance   Feb   60000   5500  62666.666667             23000
7    Pooja         HR   Feb   55000   7500  53333.333333             20500
8    Karan         IT   Mar   75000   6500  60000.000000             24000
9   Anjali    Finance   Mar   48000   8500  62666.666667             23000

In [15]:
df["Sal_vs_Dept"]=df["Salary"]-df["Dept_Avg_Sal"]
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Sal,Dept_Total_Sales,Sal_vs_Dept
0,Rahul,IT,Jan,50000,5000,60000.000000,24000,-10000.000000
1,Priya,HR,Jan,65000,7000,53333.333333,20500,11666.666667
2,Amit,IT,Jan,45000,4500,60000.000000,24000,-15000.000000
3,Neha,Finance,Jan,80000,9000,62666.666667,23000,17333.333333
4,Rohit,HR,Feb,40000,6000,53333.333333,20500,-13333.333333
5,Sneha,IT,Feb,70000,8000,60000.000000,24000,10000.000000
6,Vikas,Finance,Feb,60000,5500,62666.666667,23000,-2666.666667
7,Pooja,HR,Feb,55000,7500,53333.333333,20500,1666.666667
8,Karan,IT,Mar,75000,6500,60000.000000,24000,15000.000000
9,Anjali,Finance,Mar,48000,8500,62666.666667,23000,-14666.666667

In [ ]:
Create a Percentage of Department Sales

In [19]:
df["Sales_Percentage"]=(df["Sales"]/df["Dept_Total_Sales"] * 100)
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Sal,Dept_Total_Sales,Sal_vs_Dept,Sales_Percentage
0,Rahul,IT,Jan,50000,5000,60000.000000,24000,-10000.000000,20.833333
1,Priya,HR,Jan,65000,7000,53333.333333,20500,11666.666667,34.146341
2,Amit,IT,Jan,45000,4500,60000.000000,24000,-15000.000000,18.750000
3,Neha,Finance,Jan,80000,9000,62666.666667,23000,17333.333333,39.130435
4,Rohit,HR,Feb,40000,6000,53333.333333,20500,-13333.333333,29.268293
5,Sneha,IT,Feb,70000,8000,60000.000000,24000,10000.000000,33.333333
6,Vikas,Finance,Feb,60000,5500,62666.666667,23000,-2666.666667,23.913043
7,Pooja,HR,Feb,55000,7500,53333.333333,20500,1666.666667,36.585366
8,Karan,IT,Mar,75000,6500,60000.000000,24000,15000.000000,27.083333
9,Anjali,Finance,Mar,48000,8500,62666.666667,23000,-14666.666667,36.956522

In [ ]:
rank()-suppose we want employees ranked by salary

In [21]:
df["Salary_Rank"]=df["Salary"].rank(ascending=False)
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Sal,Dept_Total_Sales,Sal_vs_Dept,Sales_Percentage,Salary_Rank
0,Rahul,IT,Jan,50000,5000,60000.000000,24000,-10000.000000,20.833333,7.0
1,Priya,HR,Jan,65000,7000,53333.333333,20500,11666.666667,34.146341,4.0
2,Amit,IT,Jan,45000,4500,60000.000000,24000,-15000.000000,18.750000,9.0
3,Neha,Finance,Jan,80000,9000,62666.666667,23000,17333.333333,39.130435,1.0
4,Rohit,HR,Feb,40000,6000,53333.333333,20500,-13333.333333,29.268293,10.0
5,Sneha,IT,Feb,70000,8000,60000.000000,24000,10000.000000,33.333333,3.0
6,Vikas,Finance,Feb,60000,5500,62666.666667,23000,-2666.666667,23.913043,5.0
7,Pooja,HR,Feb,55000,7500,53333.333333,20500,1666.666667,36.585366,6.0
8,Karan,IT,Mar,75000,6500,60000.000000,24000,15000.000000,27.083333,2.0
9,Anjali,Finance,Mar,48000,8500,62666.666667,23000,-14666.666667,36.956522,8.0

In [ ]:
ranking withih each department

In [27]:
df["Dept_Salary_Rank"]=df.groupby("Department")["Salary"].rank(ascending=False)
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Sal,Dept_Total_Sales,Sal_vs_Dept,Sales_Percentage,Salary_Rank,Dept_Salary_Rank
0,Rahul,IT,Jan,50000,5000,60000.000000,24000,-10000.000000,20.833333,7.0,3.0
1,Priya,HR,Jan,65000,7000,53333.333333,20500,11666.666667,34.146341,4.0,1.0
2,Amit,IT,Jan,45000,4500,60000.000000,24000,-15000.000000,18.750000,9.0,4.0
3,Neha,Finance,Jan,80000,9000,62666.666667,23000,17333.333333,39.130435,1.0,1.0
4,Rohit,HR,Feb,40000,6000,53333.333333,20500,-13333.333333,29.268293,10.0,3.0
5,Sneha,IT,Feb,70000,8000,60000.000000,24000,10000.000000,33.333333,3.0,2.0
6,Vikas,Finance,Feb,60000,5500,62666.666667,23000,-2666.666667,23.913043,5.0,2.0
7,Pooja,HR,Feb,55000,7500,53333.333333,20500,1666.666667,36.585366,6.0,2.0
8,Karan,IT,Mar,75000,6500,60000.000000,24000,15000.000000,27.083333,2.0,1.0
9,Anjali,Finance,Mar,48000,8500,62666.666667,23000,-14666.666667,36.956522,8.0,3.0

In [ ]:
cumcount()-count rows within each group

In [31]:
df["Employee_Number"]=df.groupby("Department").cumcount()+1
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Sal,Dept_Total_Sales,Sal_vs_Dept,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Employee_Number
0,Rahul,IT,Jan,50000,5000,60000.000000,24000,-10000.000000,20.833333,7.0,3.0,1
1,Priya,HR,Jan,65000,7000,53333.333333,20500,11666.666667,34.146341,4.0,1.0,1
2,Amit,IT,Jan,45000,4500,60000.000000,24000,-15000.000000,18.750000,9.0,4.0,2
3,Neha,Finance,Jan,80000,9000,62666.666667,23000,17333.333333,39.130435,1.0,1.0,1
4,Rohit,HR,Feb,40000,6000,53333.333333,20500,-13333.333333,29.268293,10.0,3.0,2
5,Sneha,IT,Feb,70000,8000,60000.000000,24000,10000.000000,33.333333,3.0,2.0,3
6,Vikas,Finance,Feb,60000,5500,62666.666667,23000,-2666.666667,23.913043,5.0,2.0,2
7,Pooja,HR,Feb,55000,7500,53333.333333,20500,1666.666667,36.585366,6.0,2.0,3
8,Karan,IT,Mar,75000,6500,60000.000000,24000,15000.000000,27.083333,2.0,1.0,4
9,Anjali,Finance,Mar,48000,8500,62666.666667,23000,-14666.666667,36.956522,8.0,3.0,3

In [ ]:
cumsum()-running totals

In [37]:
df["Running_Sales"]=df["Sales"].cumsum()
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Sal,Dept_Total_Sales,Sal_vs_Dept,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Employee_Number,Running_Sales
0,Rahul,IT,Jan,50000,5000,60000.000000,24000,-10000.000000,20.833333,7.0,3.0,1,5000
1,Priya,HR,Jan,65000,7000,53333.333333,20500,11666.666667,34.146341,4.0,1.0,1,12000
2,Amit,IT,Jan,45000,4500,60000.000000,24000,-15000.000000,18.750000,9.0,4.0,2,16500
3,Neha,Finance,Jan,80000,9000,62666.666667,23000,17333.333333,39.130435,1.0,1.0,1,25500
4,Rohit,HR,Feb,40000,6000,53333.333333,20500,-13333.333333,29.268293,10.0,3.0,2,31500
5,Sneha,IT,Feb,70000,8000,60000.000000,24000,10000.000000,33.333333,3.0,2.0,3,39500
6,Vikas,Finance,Feb,60000,5500,62666.666667,23000,-2666.666667,23.913043,5.0,2.0,2,45000
7,Pooja,HR,Feb,55000,7500,53333.333333,20500,1666.666667,36.585366,6.0,2.0,3,52500
8,Karan,IT,Mar,75000,6500,60000.000000,24000,15000.000000,27.083333,2.0,1.0,4,59000
9,Anjali,Finance,Mar,48000,8500,62666.666667,23000,-14666.666667,36.956522,8.0,3.0,3,67500

In [ ]:
running totals within a group - we want a running sales total for each department.

In [43]:
df["Dept_Running_Sales"]=df.groupby("Department")["Sales"].cumsum()
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Sal,Dept_Total_Sales,Sal_vs_Dept,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Employee_Number,Running_Sales,Dept_Running_Sales
0,Rahul,IT,Jan,50000,5000,60000.000000,24000,-10000.000000,20.833333,7.0,3.0,1,5000,5000
1,Priya,HR,Jan,65000,7000,53333.333333,20500,11666.666667,34.146341,4.0,1.0,1,12000,7000
2,Amit,IT,Jan,45000,4500,60000.000000,24000,-15000.000000,18.750000,9.0,4.0,2,16500,9500
3,Neha,Finance,Jan,80000,9000,62666.666667,23000,17333.333333,39.130435,1.0,1.0,1,25500,9000
4,Rohit,HR,Feb,40000,6000,53333.333333,20500,-13333.333333,29.268293,10.0,3.0,2,31500,13000
5,Sneha,IT,Feb,70000,8000,60000.000000,24000,10000.000000,33.333333,3.0,2.0,3,39500,17500
6,Vikas,Finance,Feb,60000,5500,62666.666667,23000,-2666.666667,23.913043,5.0,2.0,2,45000,14500
7,Pooja,HR,Feb,55000,7500,53333.333333,20500,1666.666667,36.585366,6.0,2.0,3,52500,20500
8,Karan,IT,Mar,75000,6500,60000.000000,24000,15000.000000,27.083333,2.0,1.0,4,59000,24000
9,Anjali,Finance,Mar,48000,8500,62666.666667,23000,-14666.666667,36.956522,8.0,3.0,3,67500,23000

In [ ]:
cummmax()-tracks the highest sales

In [49]:
df["Running_Max"]=df["Sales"].cummax()
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Sal,Dept_Total_Sales,Sal_vs_Dept,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Employee_Number,Running_Sales,Dept_Running_Sales,Running_Max
0,Rahul,IT,Jan,50000,5000,60000.000000,24000,-10000.000000,20.833333,7.0,3.0,1,5000,5000,5000
1,Priya,HR,Jan,65000,7000,53333.333333,20500,11666.666667,34.146341,4.0,1.0,1,12000,7000,7000
2,Amit,IT,Jan,45000,4500,60000.000000,24000,-15000.000000,18.750000,9.0,4.0,2,16500,9500,7000
3,Neha,Finance,Jan,80000,9000,62666.666667,23000,17333.333333,39.130435,1.0,1.0,1,25500,9000,9000
4,Rohit,HR,Feb,40000,6000,53333.333333,20500,-13333.333333,29.268293,10.0,3.0,2,31500,13000,9000
5,Sneha,IT,Feb,70000,8000,60000.000000,24000,10000.000000,33.333333,3.0,2.0,3,39500,17500,9000
6,Vikas,Finance,Feb,60000,5500,62666.666667,23000,-2666.666667,23.913043,5.0,2.0,2,45000,14500,9000
7,Pooja,HR,Feb,55000,7500,53333.333333,20500,1666.666667,36.585366,6.0,2.0,3,52500,20500,9000
8,Karan,IT,Mar,75000,6500,60000.000000,24000,15000.000000,27.083333,2.0,1.0,4,59000,24000,9000
9,Anjali,Finance,Mar,48000,8500,62666.666667,23000,-14666.666667,36.956522,8.0,3.0,3,67500,23000,9000

In [ ]:
cummin()

In [53]:
df["Running_Min"]=df["Sales"].cummin()
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Sal,Dept_Total_Sales,Sal_vs_Dept,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Employee_Number,Running_Sales,Dept_Running_Sales,Running_Max,Running_Min
0,Rahul,IT,Jan,50000,5000,60000.000000,24000,-10000.000000,20.833333,7.0,3.0,1,5000,5000,5000,5000
1,Priya,HR,Jan,65000,7000,53333.333333,20500,11666.666667,34.146341,4.0,1.0,1,12000,7000,7000,5000
2,Amit,IT,Jan,45000,4500,60000.000000,24000,-15000.000000,18.750000,9.0,4.0,2,16500,9500,7000,4500
3,Neha,Finance,Jan,80000,9000,62666.666667,23000,17333.333333,39.130435,1.0,1.0,1,25500,9000,9000,4500
4,Rohit,HR,Feb,40000,6000,53333.333333,20500,-13333.333333,29.268293,10.0,3.0,2,31500,13000,9000,4500
5,Sneha,IT,Feb,70000,8000,60000.000000,24000,10000.000000,33.333333,3.0,2.0,3,39500,17500,9000,4500
6,Vikas,Finance,Feb,60000,5500,62666.666667,23000,-2666.666667,23.913043,5.0,2.0,2,45000,14500,9000,4500
7,Pooja,HR,Feb,55000,7500,53333.333333,20500,1666.666667,36.585366,6.0,2.0,3,52500,20500,9000,4500
8,Karan,IT,Mar,75000,6500,60000.000000,24000,15000.000000,27.083333,2.0,1.0,4,59000,24000,9000,4500
9,Anjali,Finance,Mar,48000,8500,62666.666667,23000,-14666.666667,36.956522,8.0,3.0,3,67500,23000,9000,4500

In [ ]:
shift()-shift moves values up or down

In [57]:
df["Previous_Sales"]=df["Sales"].shift(1)
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Sal,Dept_Total_Sales,Sal_vs_Dept,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Employee_Number,Running_Sales,Dept_Running_Sales,Running_Max,Running_Min,Previous_Sales
0,Rahul,IT,Jan,50000,5000,60000.000000,24000,-10000.000000,20.833333,7.0,3.0,1,5000,5000,5000,5000,NaN
1,Priya,HR,Jan,65000,7000,53333.333333,20500,11666.666667,34.146341,4.0,1.0,1,12000,7000,7000,5000,5000.0
2,Amit,IT,Jan,45000,4500,60000.000000,24000,-15000.000000,18.750000,9.0,4.0,2,16500,9500,7000,4500,7000.0
3,Neha,Finance,Jan,80000,9000,62666.666667,23000,17333.333333,39.130435,1.0,1.0,1,25500,9000,9000,4500,4500.0
4,Rohit,HR,Feb,40000,6000,53333.333333,20500,-13333.333333,29.268293,10.0,3.0,2,31500,13000,9000,4500,9000.0
5,Sneha,IT,Feb,70000,8000,60000.000000,24000,10000.000000,33.333333,3.0,2.0,3,39500,17500,9000,4500,6000.0
6,Vikas,Finance,Feb,60000,5500,62666.666667,23000,-2666.666667,23.913043,5.0,2.0,2,45000,14500,9000,4500,8000.0
7,Pooja,HR,Feb,55000,7500,53333.333333,20500,1666.666667,36.585366,6.0,2.0,3,52500,20500,9000,4500,5500.0
8,Karan,IT,Mar,75000,6500,60000.000000,24000,15000.000000,27.083333,2.0,1.0,4,59000,24000,9000,4500,7500.0
9,Anjali,Finance,Mar,48000,8500,62666.666667,23000,-14666.666667,36.956522,8.0,3.0,3,67500,23000,9000,4500,6500.0

In [ ]:
previous values within each department

In [61]:
df["Previous_Dept_Sales"]=df.groupby("Department")["Sales"].shift(1)
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Sal,Dept_Total_Sales,Sal_vs_Dept,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Employee_Number,Running_Sales,Dept_Running_Sales,Running_Max,Running_Min,Previous_Sales,Previous_Dept_Sales
0,Rahul,IT,Jan,50000,5000,60000.000000,24000,-10000.000000,20.833333,7.0,3.0,1,5000,5000,5000,5000,NaN,NaN
1,Priya,HR,Jan,65000,7000,53333.333333,20500,11666.666667,34.146341,4.0,1.0,1,12000,7000,7000,5000,5000.0,NaN
2,Amit,IT,Jan,45000,4500,60000.000000,24000,-15000.000000,18.750000,9.0,4.0,2,16500,9500,7000,4500,7000.0,5000.0
3,Neha,Finance,Jan,80000,9000,62666.666667,23000,17333.333333,39.130435,1.0,1.0,1,25500,9000,9000,4500,4500.0,NaN
4,Rohit,HR,Feb,40000,6000,53333.333333,20500,-13333.333333,29.268293,10.0,3.0,2,31500,13000,9000,4500,9000.0,7000.0
5,Sneha,IT,Feb,70000,8000,60000.000000,24000,10000.000000,33.333333,3.0,2.0,3,39500,17500,9000,4500,6000.0,4500.0
6,Vikas,Finance,Feb,60000,5500,62666.666667,23000,-2666.666667,23.913043,5.0,2.0,2,45000,14500,9000,4500,8000.0,9000.0
7,Pooja,HR,Feb,55000,7500,53333.333333,20500,1666.666667,36.585366,6.0,2.0,3,52500,20500,9000,4500,5500.0,6000.0
8,Karan,IT,Mar,75000,6500,60000.000000,24000,15000.000000,27.083333,2.0,1.0,4,59000,24000,9000,4500,7500.0,8000.0
9,Anjali,Finance,Mar,48000,8500,62666.666667,23000,-14666.666667,36.956522,8.0,3.0,3,67500,23000,9000,4500,6500.0,5500.0

In [ ]:
diff()-cal teh diffrenec between prevoius row and current row

In [65]:
df["Sales_Change"]=df["Sales"].diff()
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Sal,Dept_Total_Sales,Sal_vs_Dept,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Employee_Number,Running_Sales,Dept_Running_Sales,Running_Max,Running_Min,Previous_Sales,Previous_Dept_Sales,Sales_Change
0,Rahul,IT,Jan,50000,5000,60000.000000,24000,-10000.000000,20.833333,7.0,3.0,1,5000,5000,5000,5000,NaN,NaN,NaN
1,Priya,HR,Jan,65000,7000,53333.333333,20500,11666.666667,34.146341,4.0,1.0,1,12000,7000,7000,5000,5000.0,NaN,2000.0
2,Amit,IT,Jan,45000,4500,60000.000000,24000,-15000.000000,18.750000,9.0,4.0,2,16500,9500,7000,4500,7000.0,5000.0,-2500.0
3,Neha,Finance,Jan,80000,9000,62666.666667,23000,17333.333333,39.130435,1.0,1.0,1,25500,9000,9000,4500,4500.0,NaN,4500.0
4,Rohit,HR,Feb,40000,6000,53333.333333,20500,-13333.333333,29.268293,10.0,3.0,2,31500,13000,9000,4500,9000.0,7000.0,-3000.0
5,Sneha,IT,Feb,70000,8000,60000.000000,24000,10000.000000,33.333333,3.0,2.0,3,39500,17500,9000,4500,6000.0,4500.0,2000.0
6,Vikas,Finance,Feb,60000,5500,62666.666667,23000,-2666.666667,23.913043,5.0,2.0,2,45000,14500,9000,4500,8000.0,9000.0,-2500.0
7,Pooja,HR,Feb,55000,7500,53333.333333,20500,1666.666667,36.585366,6.0,2.0,3,52500,20500,9000,4500,5500.0,6000.0,2000.0
8,Karan,IT,Mar,75000,6500,60000.000000,24000,15000.000000,27.083333,2.0,1.0,4,59000,24000,9000,4500,7500.0,8000.0,-1000.0
9,Anjali,Finance,Mar,48000,8500,62666.666667,23000,-14666.666667,36.956522,8.0,3.0,3,67500,23000,9000,4500,6500.0,5500.0,2000.0

In [ ]:
difference within a group

In [71]:
df["Dept_Sales_Change"]=df.groupby("Department")["Sales"].diff()
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Sal,Dept_Total_Sales,Sal_vs_Dept,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Employee_Number,Running_Sales,Dept_Running_Sales,Running_Max,Running_Min,Previous_Sales,Previous_Dept_Sales,Sales_Change,Dept_Sales_Change
0,Rahul,IT,Jan,50000,5000,60000.000000,24000,-10000.000000,20.833333,7.0,3.0,1,5000,5000,5000,5000,NaN,NaN,NaN,NaN
1,Priya,HR,Jan,65000,7000,53333.333333,20500,11666.666667,34.146341,4.0,1.0,1,12000,7000,7000,5000,5000.0,NaN,2000.0,NaN
2,Amit,IT,Jan,45000,4500,60000.000000,24000,-15000.000000,18.750000,9.0,4.0,2,16500,9500,7000,4500,7000.0,5000.0,-2500.0,-500.0
3,Neha,Finance,Jan,80000,9000,62666.666667,23000,17333.333333,39.130435,1.0,1.0,1,25500,9000,9000,4500,4500.0,NaN,4500.0,NaN
4,Rohit,HR,Feb,40000,6000,53333.333333,20500,-13333.333333,29.268293,10.0,3.0,2,31500,13000,9000,4500,9000.0,7000.0,-3000.0,-1000.0
5,Sneha,IT,Feb,70000,8000,60000.000000,24000,10000.000000,33.333333,3.0,2.0,3,39500,17500,9000,4500,6000.0,4500.0,2000.0,3500.0
6,Vikas,Finance,Feb,60000,5500,62666.666667,23000,-2666.666667,23.913043,5.0,2.0,2,45000,14500,9000,4500,8000.0,9000.0,-2500.0,-3500.0
7,Pooja,HR,Feb,55000,7500,53333.333333,20500,1666.666667,36.585366,6.0,2.0,3,52500,20500,9000,4500,5500.0,6000.0,2000.0,1500.0
8,Karan,IT,Mar,75000,6500,60000.000000,24000,15000.000000,27.083333,2.0,1.0,4,59000,24000,9000,4500,7500.0,8000.0,-1000.0,-1500.0
9,Anjali,Finance,Mar,48000,8500,62666.666667,23000,-14666.666667,36.956522,8.0,3.0,3,67500,23000,9000,4500,6500.0,5500.0,2000.0,3000.0

In [ ]:
percentage change-cal percentage growth-pct_change()

In [73]:
df["Sales Growth"]=df["Sales"].pct_change()*100
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Sal,Dept_Total_Sales,Sal_vs_Dept,Sales_Percentage,Salary_Rank,...,Employee_Number,Running_Sales,Dept_Running_Sales,Running_Max,Running_Min,Previous_Sales,Previous_Dept_Sales,Sales_Change,Dept_Sales_Change,Sales Growth
0,Rahul,IT,Jan,50000,5000,60000.000000,24000,-10000.000000,20.833333,7.0,...,1,5000,5000,5000,5000,NaN,NaN,NaN,NaN,NaN
1,Priya,HR,Jan,65000,7000,53333.333333,20500,11666.666667,34.146341,4.0,...,1,12000,7000,7000,5000,5000.0,NaN,2000.0,NaN,40.000000
2,Amit,IT,Jan,45000,4500,60000.000000,24000,-15000.000000,18.750000,9.0,...,2,16500,9500,7000,4500,7000.0,5000.0,-2500.0,-500.0,-35.714286
3,Neha,Finance,Jan,80000,9000,62666.666667,23000,17333.333333,39.130435,1.0,...,1,25500,9000,9000,4500,4500.0,NaN,4500.0,NaN,100.000000
4,Rohit,HR,Feb,40000,6000,53333.333333,20500,-13333.333333,29.268293,10.0,...,2,31500,13000,9000,4500,9000.0,7000.0,-3000.0,-1000.0,-33.333333
5,Sneha,IT,Feb,70000,8000,60000.000000,24000,10000.000000,33.333333,3.0,...,3,39500,17500,9000,4500,6000.0,4500.0,2000.0,3500.0,33.333333
6,Vikas,Finance,Feb,60000,5500,62666.666667,23000,-2666.666667,23.913043,5.0,...,2,45000,14500,9000,4500,8000.0,9000.0,-2500.0,-3500.0,-31.250000
7,Pooja,HR,Feb,55000,7500,53333.333333,20500,1666.666667,36.585366,6.0,...,3,52500,20500,9000,4500,5500.0,6000.0,2000.0,1500.0,36.363636
8,Karan,IT,Mar,75000,6500,60000.000000,24000,15000.000000,27.083333,2.0,...,4,59000,24000,9000,4500,7500.0,8000.0,-1000.0,-1500.0,-13.333333
9,Anjali,Finance,Mar,48000,8500,62666.666667,23000,-14666.666667,36.956522,8.0,...,3,67500,23000,9000,4500,6500.0,5500.0,2000.0,3000.0,30.769231

In [ ]:
Grouped Percentage change

In [79]:
df["Dept_Growth"]=df.groupby("Department")["Sales"].pct_change()*100
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Sal,Dept_Total_Sales,Sal_vs_Dept,Sales_Percentage,Salary_Rank,...,Running_Sales,Dept_Running_Sales,Running_Max,Running_Min,Previous_Sales,Previous_Dept_Sales,Sales_Change,Dept_Sales_Change,Sales Growth,Dept_Growth
0,Rahul,IT,Jan,50000,5000,60000.000000,24000,-10000.000000,20.833333,7.0,...,5000,5000,5000,5000,NaN,NaN,NaN,NaN,NaN,NaN
1,Priya,HR,Jan,65000,7000,53333.333333,20500,11666.666667,34.146341,4.0,...,12000,7000,7000,5000,5000.0,NaN,2000.0,NaN,40.000000,NaN
2,Amit,IT,Jan,45000,4500,60000.000000,24000,-15000.000000,18.750000,9.0,...,16500,9500,7000,4500,7000.0,5000.0,-2500.0,-500.0,-35.714286,-10.000000
3,Neha,Finance,Jan,80000,9000,62666.666667,23000,17333.333333,39.130435,1.0,...,25500,9000,9000,4500,4500.0,NaN,4500.0,NaN,100.000000,NaN
4,Rohit,HR,Feb,40000,6000,53333.333333,20500,-13333.333333,29.268293,10.0,...,31500,13000,9000,4500,9000.0,7000.0,-3000.0,-1000.0,-33.333333,-14.285714
5,Sneha,IT,Feb,70000,8000,60000.000000,24000,10000.000000,33.333333,3.0,...,39500,17500,9000,4500,6000.0,4500.0,2000.0,3500.0,33.333333,77.777778
6,Vikas,Finance,Feb,60000,5500,62666.666667,23000,-2666.666667,23.913043,5.0,...,45000,14500,9000,4500,8000.0,9000.0,-2500.0,-3500.0,-31.250000,-38.888889
7,Pooja,HR,Feb,55000,7500,53333.333333,20500,1666.666667,36.585366,6.0,...,52500,20500,9000,4500,5500.0,6000.0,2000.0,1500.0,36.363636,25.000000
8,Karan,IT,Mar,75000,6500,60000.000000,24000,15000.000000,27.083333,2.0,...,59000,24000,9000,4500,7500.0,8000.0,-1000.0,-1500.0,-13.333333,-18.750000
9,Anjali,Finance,Mar,48000,8500,62666.666667,23000,-14666.666667,36.956522,8.0,...,67500,23000,9000,4500,6500.0,5500.0,2000.0,3000.0,30.769231,54.545455

In [ ]:
Q1

Create:

Dept_Avg_Salary

using:

groupby + transform("mean")
Q2

Create:

Dept_Total_Salary

using transform("sum").

Q3

Create:

Dept_Max_Salary

using transform("max").

Q4

Create:

Salary_vs_Dept_Avg

Formula:

Salary - Dept_Avg_Salary
Q5

Create:

Sales_Percentage

showing each employee's percentage contribution to their department's total sales.

In [81]:
import pandas as pd

data = {
    "Employee": [
        "Rahul", "Priya", "Amit", "Neha",
        "Rohit", "Sneha", "Vikas", "Pooja",
        "Karan", "Anjali"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "IT", "Finance", "HR",
        "IT", "Finance"
    ],

    "Month": [
        "Jan", "Jan", "Jan", "Jan",
        "Feb", "Feb", "Feb", "Feb",
        "Mar", "Mar"
    ],

    "Salary": [
        50000, 65000, 45000, 80000,
        40000, 70000, 60000, 55000,
        75000, 48000
    ],

    "Sales": [
        5000, 7000, 4500, 9000,
        6000, 8000, 5500, 7500,
        6500, 8500
    ]
}

df = pd.DataFrame(data)
df

  Employee Department Month  Salary  Sales
0    Rahul         IT   Jan   50000   5000
1    Priya         HR   Jan   65000   7000
2     Amit         IT   Jan   45000   4500
3     Neha    Finance   Jan   80000   9000
4    Rohit         HR   Feb   40000   6000
5    Sneha         IT   Feb   70000   8000
6    Vikas    Finance   Feb   60000   5500
7    Pooja         HR   Feb   55000   7500
8    Karan         IT   Mar   75000   6500
9   Anjali    Finance   Mar   48000   8500

In [ ]:
Q1

Create:

Dept_Avg_Salary

using:

groupby + transform("mean")

In [89]:
df["Dept_Avg_Salary"]=df.groupby("Department")["Salary"].transform("mean")
df

  Employee Department Month  Salary  Sales  Dept_Avg_Salary  Dept_Total_Salary
0    Rahul         IT   Jan   50000   5000     60000.000000             240000
1    Priya         HR   Jan   65000   7000     53333.333333             160000
2     Amit         IT   Jan   45000   4500     60000.000000             240000
3     Neha    Finance   Jan   80000   9000     62666.666667             188000
4    Rohit         HR   Feb   40000   6000     53333.333333             160000
5    Sneha         IT   Feb   70000   8000     60000.000000             240000
6    Vikas    Finance   Feb   60000   5500     62666.666667             188000
7    Pooja         HR   Feb   55000   7500     53333.333333             160000
8    Karan         IT   Mar   75000   6500     60000.000000             240000
9   Anjali    Finance   Mar   48000   8500     62666.666667             188000

In [ ]:
Create:

Dept_Total_Salary

using transform("sum").

In [87]:
df["Dept_Total_Salary"]=df.groupby("Department")["Salary"].transform("sum")
df

  Employee Department Month  Salary  Sales  Dept_Avg_Salary  Dept_Total_Salary
0    Rahul         IT   Jan   50000   5000      6000.000000             240000
1    Priya         HR   Jan   65000   7000      6833.333333             160000
2     Amit         IT   Jan   45000   4500      6000.000000             240000
3     Neha    Finance   Jan   80000   9000      7666.666667             188000
4    Rohit         HR   Feb   40000   6000      6833.333333             160000
5    Sneha         IT   Feb   70000   8000      6000.000000             240000
6    Vikas    Finance   Feb   60000   5500      7666.666667             188000
7    Pooja         HR   Feb   55000   7500      6833.333333             160000
8    Karan         IT   Mar   75000   6500      6000.000000             240000
9   Anjali    Finance   Mar   48000   8500      7666.666667             188000

In [ ]:
Q3

Create:

Dept_Max_Salary

using transform("max").

In [93]:
df["Dept_Max_Salary"]=df.groupby("Department")["Salary"].transform("max")
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000

In [ ]:
Q4

Create:

Salary_vs_Dept_Avg

Formula:

Salary - Dept_Avg_Salary

In [97]:
df["Salary_vs_Dept_Avg"]=df["Salary"]-df["Dept_Avg_Salary"]
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667

In [ ]:

Create:

Sales_Percentage

showing each employee's percentage contribution to their department's total sales.

In [103]:
df["Sales_Percentage"]=df["Sales"]/df["Dept_Total_Salary"] * 100
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277

In [ ]:
Q6

Create overall Salary_Rank.

Highest salary should have rank 1.

Q7

Create:

Dept_Salary_Rank

Rank employees within each department.

Q8

Create:

Dept_Sales_Rank

Rank employees within each department based on Sales.

Q9

Find the employee who ranks 1st in salary within their department.

Q10

Create a column:

Top_Performer

Rules:

Dept_Salary_Rank == 1 → "Yes"
Otherwise             → "No"

In [ ]:
Q6

Create overall Salary_Rank.

Highest salary should have rank 1.

In [107]:
df["Salary_Rank"]=df["Salary"].rank()
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage,Salary_Rank
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333,4.0
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000,7.0
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000,2.0
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234,10.0
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000,1.0
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333,8.0
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532,6.0
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500,5.0
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333,9.0
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277,3.0

In [ ]:
Q7

Create:

Dept_Salary_Rank

Rank employees within each department.

In [109]:
df["Dept_Salary_Rank"]=df.groupby("Department")["Salary"].rank()
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage,Salary_Rank,Dept_Salary_Rank
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333,4.0,2.0
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000,7.0,3.0
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000,2.0,1.0
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234,10.0,3.0
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000,1.0,1.0
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333,8.0,3.0
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532,6.0,2.0
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500,5.0,2.0
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333,9.0,4.0
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277,3.0,1.0

In [ ]:
Q8

Create:

Dept_Sales_Rank

Rank employees within each department based on Sales.

In [111]:
df["Dept_Sales_Rank"]=df.groupby("Department")["Sales"].rank()
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Dept_Sales_Rank
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333,4.0,2.0,2.0
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000,7.0,3.0,2.0
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000,2.0,1.0,1.0
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234,10.0,3.0,3.0
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000,1.0,1.0,1.0
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333,8.0,3.0,4.0
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532,6.0,2.0,1.0
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500,5.0,2.0,3.0
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333,9.0,4.0,3.0
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277,3.0,1.0,2.0

In [ ]:
Q9

Find the employee who ranks 1st in salary within their department.

In [121]:
df["Dept_Salary_Rank"]=df.groupby("Department")["Salary"].rank(ascending=False)
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Dept_Sales_Rank,Emp_Rank_Dept
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333,4.0,3.0,2.0,3.0
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000,7.0,1.0,2.0,1.0
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000,2.0,4.0,1.0,4.0
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234,10.0,1.0,3.0,1.0
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000,1.0,3.0,1.0,3.0
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333,8.0,2.0,4.0,2.0
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532,6.0,2.0,1.0,2.0
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500,5.0,2.0,3.0,2.0
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333,9.0,1.0,3.0,1.0
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277,3.0,3.0,2.0,3.0

In [ ]:
Q10

Create a column:

Top_Performer

Rules:

Dept_Salary_Rank == 1 → "Yes"
Otherwise             → "No"

In [123]:
import numpy as np
df["Top_Performer"]=np.where(df["Dept_Salary_Rank"]==1,"Yes","No")
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Dept_Sales_Rank,Emp_Rank_Dept,Top_Performer
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333,4.0,3.0,2.0,3.0,No
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000,7.0,1.0,2.0,1.0,Yes
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000,2.0,4.0,1.0,4.0,No
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234,10.0,1.0,3.0,1.0,Yes
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000,1.0,3.0,1.0,3.0,No
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333,8.0,2.0,4.0,2.0,No
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532,6.0,2.0,1.0,2.0,No
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500,5.0,2.0,3.0,2.0,No
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333,9.0,1.0,3.0,1.0,Yes
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277,3.0,3.0,2.0,3.0,No

In [ ]:
Q11

Create:

Employee_Number

numbering employees within each department starting from 1.

Q12

Create:

Running_Sales

for the entire DataFrame.

Q13

Create:

Dept_Running_Sales

running sales separately for each department.

Q14

Create:

Running_Max_Sales

using cummax().

Q15

Create:

Running_Min_Sales

using cummin().

In [ ]:
Q11

Create:

Employee_Number

numbering employees within each department starting from 1.

In [129]:
df["Employee_Number"]=df.groupby("Department").cumcount()+1
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Dept_Sales_Rank,Emp_Rank_Dept,Top_Performer,Employee_Number
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333,4.0,3.0,2.0,3.0,No,1
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000,7.0,1.0,2.0,1.0,Yes,1
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000,2.0,4.0,1.0,4.0,No,2
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234,10.0,1.0,3.0,1.0,Yes,1
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000,1.0,3.0,1.0,3.0,No,2
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333,8.0,2.0,4.0,2.0,No,3
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532,6.0,2.0,1.0,2.0,No,2
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500,5.0,2.0,3.0,2.0,No,3
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333,9.0,1.0,3.0,1.0,Yes,4
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277,3.0,3.0,2.0,3.0,No,3

In [ ]:
Q12

Create:

Running_Sales

for the entire DataFrame.

In [131]:
df["Running_Sales"]=df["Sales"].cumsum()
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Dept_Sales_Rank,Emp_Rank_Dept,Top_Performer,Employee_Number,Running_Sales
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333,4.0,3.0,2.0,3.0,No,1,5000
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000,7.0,1.0,2.0,1.0,Yes,1,12000
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000,2.0,4.0,1.0,4.0,No,2,16500
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234,10.0,1.0,3.0,1.0,Yes,1,25500
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000,1.0,3.0,1.0,3.0,No,2,31500
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333,8.0,2.0,4.0,2.0,No,3,39500
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532,6.0,2.0,1.0,2.0,No,2,45000
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500,5.0,2.0,3.0,2.0,No,3,52500
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333,9.0,1.0,3.0,1.0,Yes,4,59000
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277,3.0,3.0,2.0,3.0,No,3,67500

In [ ]:
Create:

Dept_Running_Sales

running sales separately for each department.

In [133]:
df["Dept_Running_Sales"]=df.groupby("Department")["Sales"].cumsum()
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Dept_Sales_Rank,Emp_Rank_Dept,Top_Performer,Employee_Number,Running_Sales,Dept_Running_Sales
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333,4.0,3.0,2.0,3.0,No,1,5000,5000
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000,7.0,1.0,2.0,1.0,Yes,1,12000,7000
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000,2.0,4.0,1.0,4.0,No,2,16500,9500
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234,10.0,1.0,3.0,1.0,Yes,1,25500,9000
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000,1.0,3.0,1.0,3.0,No,2,31500,13000
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333,8.0,2.0,4.0,2.0,No,3,39500,17500
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532,6.0,2.0,1.0,2.0,No,2,45000,14500
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500,5.0,2.0,3.0,2.0,No,3,52500,20500
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333,9.0,1.0,3.0,1.0,Yes,4,59000,24000
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277,3.0,3.0,2.0,3.0,No,3,67500,23000

In [ ]:
Q14

Create:

Running_Max_Sales

using cummax().

In [135]:
df["Running_Max_Sales"]=df["Sales"].cummax()
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Dept_Sales_Rank,Emp_Rank_Dept,Top_Performer,Employee_Number,Running_Sales,Dept_Running_Sales,Running_Max_Sales
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333,4.0,3.0,2.0,3.0,No,1,5000,5000,5000
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000,7.0,1.0,2.0,1.0,Yes,1,12000,7000,7000
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000,2.0,4.0,1.0,4.0,No,2,16500,9500,7000
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234,10.0,1.0,3.0,1.0,Yes,1,25500,9000,9000
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000,1.0,3.0,1.0,3.0,No,2,31500,13000,9000
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333,8.0,2.0,4.0,2.0,No,3,39500,17500,9000
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532,6.0,2.0,1.0,2.0,No,2,45000,14500,9000
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500,5.0,2.0,3.0,2.0,No,3,52500,20500,9000
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333,9.0,1.0,3.0,1.0,Yes,4,59000,24000,9000
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277,3.0,3.0,2.0,3.0,No,3,67500,23000,9000

In [ ]:
Q15

Create:

Running_Min_Sales

using cummin().

In [137]:
df["Running_Min_Sales"]=df["Sales"].cummin()
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage,Salary_Rank,Dept_Salary_Rank,Dept_Sales_Rank,Emp_Rank_Dept,Top_Performer,Employee_Number,Running_Sales,Dept_Running_Sales,Running_Max_Sales,Running_Min_Sales
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333,4.0,3.0,2.0,3.0,No,1,5000,5000,5000,5000
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000,7.0,1.0,2.0,1.0,Yes,1,12000,7000,7000,5000
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000,2.0,4.0,1.0,4.0,No,2,16500,9500,7000,4500
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234,10.0,1.0,3.0,1.0,Yes,1,25500,9000,9000,4500
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000,1.0,3.0,1.0,3.0,No,2,31500,13000,9000,4500
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333,8.0,2.0,4.0,2.0,No,3,39500,17500,9000,4500
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532,6.0,2.0,1.0,2.0,No,2,45000,14500,9000,4500
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500,5.0,2.0,3.0,2.0,No,3,52500,20500,9000,4500
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333,9.0,1.0,3.0,1.0,Yes,4,59000,24000,9000,4500
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277,3.0,3.0,2.0,3.0,No,3,67500,23000,9000,4500

In [ ]:
Q16

Create:

Previous_Sales

using shift().

Q17

Create:

Sales_Change

using diff().

Q18

Create:

Previous_Dept_Sales

using:

groupby() + shift()
Q19

Create:

Dept_Sales_Change

using:

groupby() + diff()
Q20

Create:

Sales_Growth_Percentage

using pct_change().

In [ ]:
Q16

Create:

Previous_Sales

using shift().

In [139]:
df["Previous_Sales"]=df["Sales"].shift(1)
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage,...,Dept_Salary_Rank,Dept_Sales_Rank,Emp_Rank_Dept,Top_Performer,Employee_Number,Running_Sales,Dept_Running_Sales,Running_Max_Sales,Running_Min_Sales,Previous_Sales
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333,...,3.0,2.0,3.0,No,1,5000,5000,5000,5000,NaN
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000,...,1.0,2.0,1.0,Yes,1,12000,7000,7000,5000,5000.0
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000,...,4.0,1.0,4.0,No,2,16500,9500,7000,4500,7000.0
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234,...,1.0,3.0,1.0,Yes,1,25500,9000,9000,4500,4500.0
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000,...,3.0,1.0,3.0,No,2,31500,13000,9000,4500,9000.0
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333,...,2.0,4.0,2.0,No,3,39500,17500,9000,4500,6000.0
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532,...,2.0,1.0,2.0,No,2,45000,14500,9000,4500,8000.0
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500,...,2.0,3.0,2.0,No,3,52500,20500,9000,4500,5500.0
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333,...,1.0,3.0,1.0,Yes,4,59000,24000,9000,4500,7500.0
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277,...,3.0,2.0,3.0,No,3,67500,23000,9000,4500,6500.0

In [ ]:
Q17

Create:

Sales_Change

using diff().

In [143]:
df["Sales_Change"]=df["Sales"].diff()
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage,...,Dept_Sales_Rank,Emp_Rank_Dept,Top_Performer,Employee_Number,Running_Sales,Dept_Running_Sales,Running_Max_Sales,Running_Min_Sales,Previous_Sales,Sales_Change
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333,...,2.0,3.0,No,1,5000,5000,5000,5000,NaN,NaN
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000,...,2.0,1.0,Yes,1,12000,7000,7000,5000,5000.0,2000.0
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000,...,1.0,4.0,No,2,16500,9500,7000,4500,7000.0,-2500.0
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234,...,3.0,1.0,Yes,1,25500,9000,9000,4500,4500.0,4500.0
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000,...,1.0,3.0,No,2,31500,13000,9000,4500,9000.0,-3000.0
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333,...,4.0,2.0,No,3,39500,17500,9000,4500,6000.0,2000.0
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532,...,1.0,2.0,No,2,45000,14500,9000,4500,8000.0,-2500.0
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500,...,3.0,2.0,No,3,52500,20500,9000,4500,5500.0,2000.0
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333,...,3.0,1.0,Yes,4,59000,24000,9000,4500,7500.0,-1000.0
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277,...,2.0,3.0,No,3,67500,23000,9000,4500,6500.0,2000.0

In [ ]:
Q18

Create:

Previous_Dept_Sales

using:

groupby() + shift()

In [145]:
df["Previous_Dept_Sales"]=df.groupby("Department")["Sales"].shift(1)
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage,...,Emp_Rank_Dept,Top_Performer,Employee_Number,Running_Sales,Dept_Running_Sales,Running_Max_Sales,Running_Min_Sales,Previous_Sales,Sales_Change,Previous_Dept_Sales
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333,...,3.0,No,1,5000,5000,5000,5000,NaN,NaN,NaN
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000,...,1.0,Yes,1,12000,7000,7000,5000,5000.0,2000.0,NaN
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000,...,4.0,No,2,16500,9500,7000,4500,7000.0,-2500.0,5000.0
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234,...,1.0,Yes,1,25500,9000,9000,4500,4500.0,4500.0,NaN
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000,...,3.0,No,2,31500,13000,9000,4500,9000.0,-3000.0,7000.0
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333,...,2.0,No,3,39500,17500,9000,4500,6000.0,2000.0,4500.0
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532,...,2.0,No,2,45000,14500,9000,4500,8000.0,-2500.0,9000.0
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500,...,2.0,No,3,52500,20500,9000,4500,5500.0,2000.0,6000.0
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333,...,1.0,Yes,4,59000,24000,9000,4500,7500.0,-1000.0,8000.0
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277,...,3.0,No,3,67500,23000,9000,4500,6500.0,2000.0,5500.0

In [ ]:
Q19

Create:

Dept_Sales_Change

using:

groupby() + diff()

In [147]:
df["Dept_Sales_Change"]=df.groupby("Department")["Sales"].diff()
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage,...,Top_Performer,Employee_Number,Running_Sales,Dept_Running_Sales,Running_Max_Sales,Running_Min_Sales,Previous_Sales,Sales_Change,Previous_Dept_Sales,Dept_Sales_Change
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333,...,No,1,5000,5000,5000,5000,NaN,NaN,NaN,NaN
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000,...,Yes,1,12000,7000,7000,5000,5000.0,2000.0,NaN,NaN
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000,...,No,2,16500,9500,7000,4500,7000.0,-2500.0,5000.0,-500.0
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234,...,Yes,1,25500,9000,9000,4500,4500.0,4500.0,NaN,NaN
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000,...,No,2,31500,13000,9000,4500,9000.0,-3000.0,7000.0,-1000.0
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333,...,No,3,39500,17500,9000,4500,6000.0,2000.0,4500.0,3500.0
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532,...,No,2,45000,14500,9000,4500,8000.0,-2500.0,9000.0,-3500.0
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500,...,No,3,52500,20500,9000,4500,5500.0,2000.0,6000.0,1500.0
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333,...,Yes,4,59000,24000,9000,4500,7500.0,-1000.0,8000.0,-1500.0
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277,...,No,3,67500,23000,9000,4500,6500.0,2000.0,5500.0,3000.0

In [ ]:
Q20

Create:

Sales_Growth_Percentage

using pct_change().

In [155]:
df["Sales_Growth_Percentage"]=df["Sales"].pct_change()*100
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage,...,Employee_Number,Running_Sales,Dept_Running_Sales,Running_Max_Sales,Running_Min_Sales,Previous_Sales,Sales_Change,Previous_Dept_Sales,Dept_Sales_Change,Sales_Growth_Percentage
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333,...,1,5000,5000,5000,5000,NaN,NaN,NaN,NaN,NaN
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000,...,1,12000,7000,7000,5000,5000.0,2000.0,NaN,NaN,40.000000
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000,...,2,16500,9500,7000,4500,7000.0,-2500.0,5000.0,-500.0,-35.714286
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234,...,1,25500,9000,9000,4500,4500.0,4500.0,NaN,NaN,100.000000
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000,...,2,31500,13000,9000,4500,9000.0,-3000.0,7000.0,-1000.0,-33.333333
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333,...,3,39500,17500,9000,4500,6000.0,2000.0,4500.0,3500.0,33.333333
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532,...,2,45000,14500,9000,4500,8000.0,-2500.0,9000.0,-3500.0,-31.250000
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500,...,3,52500,20500,9000,4500,5500.0,2000.0,6000.0,1500.0,36.363636
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333,...,4,59000,24000,9000,4500,7500.0,-1000.0,8000.0,-1500.0,-13.333333
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277,...,3,67500,23000,9000,4500,6500.0,2000.0,5500.0,3000.0,30.769231

In [ ]:
Q21

Create:

Dept_Avg_Sales

Then create:

Above_Dept_Average

Rules:

Sales > Dept_Avg_Sales → "Yes"
Otherwise              → "No"

In [159]:
df["Dept_Avg_Sales"]=df.groupby("Department")["Sales"].transform("mean")

In [161]:
import numpy as np
df["Above_Dept_Average"]=np.where(
    df["Sales"] >df["Dept_Avg_Sales"],"Yes","No"
)
df

,Employee,Department,Month,Salary,Sales,Dept_Avg_Salary,Dept_Total_Salary,Dept_Max_Salary,Salary_vs_Dept_Avg,Sales_Percentage,...,Dept_Running_Sales,Running_Max_Sales,Running_Min_Sales,Previous_Sales,Sales_Change,Previous_Dept_Sales,Dept_Sales_Change,Sales_Growth_Percentage,Dept_Avg_Sales,Above_Dept_Average
0,Rahul,IT,Jan,50000,5000,60000.000000,240000,75000,-10000.000000,2.083333,...,5000,5000,5000,NaN,NaN,NaN,NaN,NaN,6000.000000,No
1,Priya,HR,Jan,65000,7000,53333.333333,160000,65000,11666.666667,4.375000,...,7000,7000,5000,5000.0,2000.0,NaN,NaN,40.000000,6833.333333,Yes
2,Amit,IT,Jan,45000,4500,60000.000000,240000,75000,-15000.000000,1.875000,...,9500,7000,4500,7000.0,-2500.0,5000.0,-500.0,-35.714286,6000.000000,No
3,Neha,Finance,Jan,80000,9000,62666.666667,188000,80000,17333.333333,4.787234,...,9000,9000,4500,4500.0,4500.0,NaN,NaN,100.000000,7666.666667,Yes
4,Rohit,HR,Feb,40000,6000,53333.333333,160000,65000,-13333.333333,3.750000,...,13000,9000,4500,9000.0,-3000.0,7000.0,-1000.0,-33.333333,6833.333333,No
5,Sneha,IT,Feb,70000,8000,60000.000000,240000,75000,10000.000000,3.333333,...,17500,9000,4500,6000.0,2000.0,4500.0,3500.0,33.333333,6000.000000,Yes
6,Vikas,Finance,Feb,60000,5500,62666.666667,188000,80000,-2666.666667,2.925532,...,14500,9000,4500,8000.0,-2500.0,9000.0,-3500.0,-31.250000,7666.666667,No
7,Pooja,HR,Feb,55000,7500,53333.333333,160000,65000,1666.666667,4.687500,...,20500,9000,4500,5500.0,2000.0,6000.0,1500.0,36.363636,6833.333333,Yes
8,Karan,IT,Mar,75000,6500,60000.000000,240000,75000,15000.000000,2.708333,...,24000,9000,4500,7500.0,-1000.0,8000.0,-1500.0,-13.333333,6000.000000,Yes
9,Anjali,Finance,Mar,48000,8500,62666.666667,188000,80000,-14666.666667,4.521277,...,23000,9000,4500,6500.0,2000.0,5500.0,3000.0,30.769231,7666.666667,Yes

In [ ]:
Q22

Create:

Salary_Rank

within each department.

Then return only:

Name
Department
Salary
Salary_Rank

for employees ranked 1 or 2.

In [177]:
df["Salary_Rank"]=df.groupby("Department")["Salary"].rank(
    method="min",
    ascending=False
)
res = df[df["Salary_Rank"].isin([1, 2])][
    ["Employee", "Department", "Salary", "Salary_Rank"]
]
res

  Employee Department  Salary  Salary_Rank
1    Priya         HR   65000          1.0
3     Neha    Finance   80000          1.0
5    Sneha         IT   70000          2.0
6    Vikas    Finance   60000          2.0
7    Pooja         HR   55000          2.0
8    Karan         IT   75000          1.0

In [ ]:
Q23

Create:

Dept_Total_Sales
Sales_Percentage

Then verify that the percentages within each department add up to approximately:

100%

In [189]:
df["Dept_Total_Sales"]=df.groupby("Department")["Sales"].transform("sum")

In [187]:
df["Sales_Percentage"]=df["Sales"] / df["Dept_Total_Sales"]

verified=df.groupby("Department")["Sales_Percentage"].sum()
verified

In [ ]:
Q24 💼

HR wants to find employees whose salary is above their department's average salary.

Create:

Dept_Avg_Salary
Above_Average

and return:

Employee
Department
Salary
Dept_Avg_Salary
Above_Average

for only employees above average.

In [ ]:
df["Dept_Avg_Salary"]=df.groupby("Department")["Salary"].transform("mean")

In [202]:
import numpy as np
df["Above_Average"]=np.where(
    df["Salary"] > df["Dept_Avg_Salary"],"Yes","No"
)
result=df[df["Above_Average"]=="Yes"][
["Employee","Department","Salary","Dept_Avg_Salary","Above_Average"]
]
result

  Employee Department  Salary  Dept_Avg_Salary Above_Average
1    Priya         HR   65000     53333.333333           Yes
3     Neha    Finance   80000     62666.666667           Yes
5    Sneha         IT   70000     60000.000000           Yes
7    Pooja         HR   55000     53333.333333           Yes
8    Karan         IT   75000     60000.000000           Yes

In [ ]:
🏆 Q25 — Master Problem

Imagine you're a Data Analyst.

Management asks:

"For every employee, show their department's average salary, their salary rank within the department, 
their department's total sales, their sales contribution percentage, and whether they are above the department's average salary."

Create these columns:

Dept_Avg_Salary
Dept_Salary_Rank
Dept_Total_Sales
Sales_Percentage
Above_Dept_Average

Your final DataFrame should look conceptually like:

Employee | Department | Salary | Dept_Avg_Salary |
Dept_Salary_Rank | Dept_Total_Sales |
Sales_Percentage | Above_Dept_Average

In [204]:
df["Dept_Avg_Salary"]=df.groupby("Department")["Salary"].transform("mean")

In [206]:
df["Dept_Salary_Rank"]=df.groupby("Department")["Salary"].rank()

In [208]:
df["Dept_Total_Sales"]=df.groupby("Department")["Sales"].transform("sum")

In [210]:
df["Sales_Percentage"]=df["Sales"]/df["Dept_Total_Sales"]*100

In [220]:
import numpy as np
df["Above_Dept_Average"]=np.where(
    df["Salary"]>df["Dept_Avg_Salary"],"YES" ,"No"
)

In [222]:
dataframes= ["Employee","Department","Salary","Dept_Avg_Salary","Dept_Salary_Rank","Dept_Total_Sales","Sales_Percentage","Above_Dept_Average"]

In [224]:
dataframes

['Employee',
 'Department',
 'Salary',
 'Dept_Avg_Salary',
 'Dept_Salary_Rank',
 'Dept_Total_Sales',
 'Sales_Percentage',
 'Above_Dept_Average']