In [1]:
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    
    "Name": [
        "Rahul Sharma", "Priya Singh", "Amit Kumar", "Neha Verma",
        "Rohit Singh", "Sneha Gupta", "Vikas Kumar", "Pooja Sharma",
        "Karan Singh", "Anjali Verma"
    ],
    
    "Age": [25, 32, 28, 41, 24, 35, 29, 45, 31, 27],
    
    "Department": [
        "IT", "HR", "IT", "Finance", "HR",
        "IT", "Finance", "HR", "IT", "Finance"
    ],
    
    "Salary": [
        50000, 65000, 45000, 80000, 40000,
        70000, 60000, 55000, 75000, 48000
    ],
    
    "Experience": [
        2, 6, 3, 10, 1,
        7, 5, 8, 6, 2
    ],
    
    "City": [
        "Delhi", "Mumbai", "Delhi", "Pune", "Mumbai",
        "Delhi", "Pune", "Mumbai", "Delhi", "Pune"
    ]
}

df = pd.DataFrame(data)
df

   Employee_ID          Name  Age Department  Salary  Experience    City
0          101  Rahul Sharma   25         IT   50000           2   Delhi
1          102   Priya Singh   32         HR   65000           6  Mumbai
2          103    Amit Kumar   28         IT   45000           3   Delhi
3          104    Neha Verma   41    Finance   80000          10    Pune
4          105   Rohit Singh   24         HR   40000           1  Mumbai
5          106   Sneha Gupta   35         IT   70000           7   Delhi
6          107   Vikas Kumar   29    Finance   60000           5    Pune
7          108  Pooja Sharma   45         HR   55000           8  Mumbai
8          109   Karan Singh   31         IT   75000           6   Delhi
9          110  Anjali Verma   27    Finance   48000           2    Pune

In [ ]:
Boolean Filtering — The Foundation
Suppose we want employees whose salary is greater than ₹60,000.

In [5]:
df[df["Salary"]>60000]

   Employee_ID         Name  Age Department  Salary  Experience    City
1          102  Priya Singh   32         HR   65000           6  Mumbai
3          104   Neha Verma   41    Finance   80000          10    Pune
5          106  Sneha Gupta   35         IT   70000           7   Delhi
8          109  Karan Singh   31         IT   75000           6   Delhi

In [ ]:
Multiple Conditions
Employees whose salary is above ₹50,000 AND experience is at least 5 years.

In [19]:
df[
(df["Salary"]>50000) & 
(df["Experience"]>=5)
]

   Employee_ID          Name  Age Department  Salary  Experience    City
1          102   Priya Singh   32         HR   65000           6  Mumbai
3          104    Neha Verma   41    Finance   80000          10    Pune
5          106   Sneha Gupta   35         IT   70000           7   Delhi
6          107   Vikas Kumar   29    Finance   60000           5    Pune
7          108  Pooja Sharma   45         HR   55000           8  Mumbai
8          109   Karan Singh   31         IT   75000           6   Delhi

In [27]:
df[
(df["Department"]=="IT" )&
(df["Salary"]>60000)
]

   Employee_ID         Name  Age Department  Salary  Experience   City
5          106  Sneha Gupta   35         IT   70000           7  Delhi
8          109  Karan Singh   31         IT   75000           6  Delhi

In [31]:
df[
(df["Department"]=="IT") |
(df["Department"]=="HR")
]

   Employee_ID          Name  Age Department  Salary  Experience    City
0          101  Rahul Sharma   25         IT   50000           2   Delhi
1          102   Priya Singh   32         HR   65000           6  Mumbai
2          103    Amit Kumar   28         IT   45000           3   Delhi
4          105   Rohit Singh   24         HR   40000           1  Mumbai
5          106   Sneha Gupta   35         IT   70000           7   Delhi
7          108  Pooja Sharma   45         HR   55000           8  Mumbai
8          109   Karan Singh   31         IT   75000           6   Delhi

In [ ]:
isin()

In [33]:
df[df["Department"].isin(["IT","HR","Finance"])]

   Employee_ID          Name  Age Department  Salary  Experience    City
0          101  Rahul Sharma   25         IT   50000           2   Delhi
1          102   Priya Singh   32         HR   65000           6  Mumbai
2          103    Amit Kumar   28         IT   45000           3   Delhi
3          104    Neha Verma   41    Finance   80000          10    Pune
4          105   Rohit Singh   24         HR   40000           1  Mumbai
5          106   Sneha Gupta   35         IT   70000           7   Delhi
6          107   Vikas Kumar   29    Finance   60000           5    Pune
7          108  Pooja Sharma   45         HR   55000           8  Mumbai
8          109   Karan Singh   31         IT   75000           6   Delhi
9          110  Anjali Verma   27    Finance   48000           2    Pune

In [ ]:
Find employees from Delhi or Mumbai:

In [35]:
df[df["City"].isin(["Delhi","Mumbai"])]

   Employee_ID          Name  Age Department  Salary  Experience    City
0          101  Rahul Sharma   25         IT   50000           2   Delhi
1          102   Priya Singh   32         HR   65000           6  Mumbai
2          103    Amit Kumar   28         IT   45000           3   Delhi
4          105   Rohit Singh   24         HR   40000           1  Mumbai
5          106   Sneha Gupta   35         IT   70000           7   Delhi
7          108  Pooja Sharma   45         HR   55000           8  Mumbai
8          109   Karan Singh   31         IT   75000           6   Delhi

In [ ]:
NOT isin()

In [ ]:
Find employees who are NOT from Delhi.

In [43]:
df[~df["City"].isin(["Delhi"])]

   Employee_ID          Name  Age Department  Salary  Experience    City
1          102   Priya Singh   32         HR   65000           6  Mumbai
3          104    Neha Verma   41    Finance   80000          10    Pune
4          105   Rohit Singh   24         HR   40000           1  Mumbai
6          107   Vikas Kumar   29    Finance   60000           5    Pune
7          108  Pooja Sharma   45         HR   55000           8  Mumbai
9          110  Anjali Verma   27    Finance   48000           2    Pune

In [ ]:
between()

In [ ]:
Find employees aged between 25 and 35.

In [47]:
df[df["Age"].between(25,35)]

   Employee_ID          Name  Age Department  Salary  Experience    City
0          101  Rahul Sharma   25         IT   50000           2   Delhi
1          102   Priya Singh   32         HR   65000           6  Mumbai
2          103    Amit Kumar   28         IT   45000           3   Delhi
5          106   Sneha Gupta   35         IT   70000           7   Delhi
6          107   Vikas Kumar   29    Finance   60000           5    Pune
8          109   Karan Singh   31         IT   75000           6   Delhi
9          110  Anjali Verma   27    Finance   48000           2    Pune

In [55]:

df["Age"].between(25,35,
inclusive="neither")

0    False
1     True
2     True
3    False
4    False
5    False
6     True
7    False
8     True
9     True
Name: Age, dtype: bool

In [ ]:
str.contains

In [ ]:
Suppose we want employees whose name contains "Sharma".

In [57]:
df[df["Name"].str.contains("Sharma")]

   Employee_ID          Name  Age Department  Salary  Experience    City
0          101  Rahul Sharma   25         IT   50000           2   Delhi
7          108  Pooja Sharma   45         HR   55000           8  Mumbai

In [59]:
df[df["Name"].str.contains("Sharma",case=False)]

   Employee_ID          Name  Age Department  Salary  Experience    City
0          101  Rahul Sharma   25         IT   50000           2   Delhi
7          108  Pooja Sharma   45         HR   55000           8  Mumbai

In [ ]:
str.startswith()

In [ ]:
Find names beginning with "A":

In [61]:
df[df["Name"].str.startswith("A")]

   Employee_ID          Name  Age Department  Salary  Experience   City
2          103    Amit Kumar   28         IT   45000           3  Delhi
9          110  Anjali Verma   27    Finance   48000           2   Pune

In [ ]:
str.endswith()-Find names ending with "Singh":

In [63]:
df[df["Name"].str.endswith("Singh")]

   Employee_ID         Name  Age Department  Salary  Experience    City
1          102  Priya Singh   32         HR   65000           6  Mumbai
4          105  Rohit Singh   24         HR   40000           1  Mumbai
8          109  Karan Singh   31         IT   75000           6   Delhi

In [ ]:
str.len()-Find names whose length is greater than 10:

In [65]:
df[df["Name"].str.len()>10]

   Employee_ID          Name  Age Department  Salary  Experience    City
0          101  Rahul Sharma   25         IT   50000           2   Delhi
1          102   Priya Singh   32         HR   65000           6  Mumbai
4          105   Rohit Singh   24         HR   40000           1  Mumbai
5          106   Sneha Gupta   35         IT   70000           7   Delhi
6          107   Vikas Kumar   29    Finance   60000           5    Pune
7          108  Pooja Sharma   45         HR   55000           8  Mumbai
8          109   Karan Singh   31         IT   75000           6   Delhi
9          110  Anjali Verma   27    Finance   48000           2    Pune

In [ ]:
nlargest()-Find the top 3 highest-paid employees.

In [69]:
df.nlargest(3,"Salary")

   Employee_ID         Name  Age Department  Salary  Experience   City
3          104   Neha Verma   41    Finance   80000          10   Pune
8          109  Karan Singh   31         IT   75000           6  Delhi
5          106  Sneha Gupta   35         IT   70000           7  Delhi

In [ ]:
nsmallest()-Find the 3 lowest-paid employees:

In [71]:
df.nsmallest(3,"Salary")

   Employee_ID          Name  Age Department  Salary  Experience    City
4          105   Rohit Singh   24         HR   40000           1  Mumbai
2          103    Amit Kumar   28         IT   45000           3   Delhi
9          110  Anjali Verma   27    Finance   48000           2    Pune

In [ ]:
idxmax()-Find the index of the employee with the highest salary.

In [75]:
df["Salary"].idxmax()

3

In [85]:
df.loc[df["Salary"].idxmax()]

Employee_ID           104
Name           Neha Verma
Age                    41
Department        Finance
Salary              80000
Experience             10
City                 Pune
Name: 3, dtype: object

In [ ]:
idxmin()

In [89]:
df.loc[df["Salary"].idxmin()]

Employee_ID            105
Name           Rohit Singh
Age                     24
Department              HR
Salary               40000
Experience               1
City                Mumbai
Name: 4, dtype: object

In [ ]:
filtering +sorting

In [ ]:
Find IT employees earning more than ₹50,000, sorted by salary descending.

In [95]:
df[
(df["Department"]=="IT") &
(df["Salary"]>50000)
].sort_values("Salary",ascending=False)

   Employee_ID         Name  Age Department  Salary  Experience   City
8          109  Karan Singh   31         IT   75000           6  Delhi
5          106  Sneha Gupta   35         IT   70000           7  Delhi

In [ ]:
Filtering +TopN

In [ ]:
Find the top 2 highest-paid IT employees.

In [99]:
df[
df["Department"]=="IT"
].nlargest(2,"Salary")

   Employee_ID         Name  Age Department  Salary  Experience   City
8          109  Karan Singh   31         IT   75000           6  Delhi
5          106  Sneha Gupta   35         IT   70000           7  Delhi

In [ ]:
Advanced_filtering +query()

In [107]:
df.query(
    "Department =='IT' and Salary>50000"
)

   Employee_ID         Name  Age Department  Salary  Experience   City
5          106  Sneha Gupta   35         IT   70000           7  Delhi
8          109  Karan Singh   31         IT   75000           6  Delhi

In [ ]:
for multiple departments use in

In [111]:
df.query(
    "Department in ['IT','HR']"
)

   Employee_ID          Name  Age Department  Salary  Experience    City
0          101  Rahul Sharma   25         IT   50000           2   Delhi
1          102   Priya Singh   32         HR   65000           6  Mumbai
2          103    Amit Kumar   28         IT   45000           3   Delhi
4          105   Rohit Singh   24         HR   40000           1  Mumbai
5          106   Sneha Gupta   35         IT   70000           7   Delhi
7          108  Pooja Sharma   45         HR   55000           8  Mumbai
8          109   Karan Singh   31         IT   75000           6   Delhi

In [ ]:
duplicated for advanced filtering

In [119]:
df[df.duplicated("Department",keep=False)]

   Employee_ID          Name  Age Department  Salary  Experience    City
0          101  Rahul Sharma   25         IT   50000           2   Delhi
1          102   Priya Singh   32         HR   65000           6  Mumbai
2          103    Amit Kumar   28         IT   45000           3   Delhi
3          104    Neha Verma   41    Finance   80000          10    Pune
4          105   Rohit Singh   24         HR   40000           1  Mumbai
5          106   Sneha Gupta   35         IT   70000           7   Delhi
6          107   Vikas Kumar   29    Finance   60000           5    Pune
7          108  Pooja Sharma   45         HR   55000           8  Mumbai
8          109   Karan Singh   31         IT   75000           6   Delhi
9          110  Anjali Verma   27    Finance   48000           2    Pune

In [123]:
df[df.duplicated("City",keep=False)]

   Employee_ID          Name  Age Department  Salary  Experience    City
0          101  Rahul Sharma   25         IT   50000           2   Delhi
1          102   Priya Singh   32         HR   65000           6  Mumbai
2          103    Amit Kumar   28         IT   45000           3   Delhi
3          104    Neha Verma   41    Finance   80000          10    Pune
4          105   Rohit Singh   24         HR   40000           1  Mumbai
5          106   Sneha Gupta   35         IT   70000           7   Delhi
6          107   Vikas Kumar   29    Finance   60000           5    Pune
7          108  Pooja Sharma   45         HR   55000           8  Mumbai
8          109   Karan Singh   31         IT   75000           6   Delhi
9          110  Anjali Verma   27    Finance   48000           2    Pune

In [ ]:
Find the top 3 IT employees from Delhi or Mumbai with salary above ₹50,000 and experience of at least 5 years.

In [135]:
df[
(df["Department"]=="IT") &
(df["City"].isin(["Delhi","Mumbai"])) &
(df["Salary"]>50000 )&
(df["Experience"]>5)
].nlargest(3,"Salary")

   Employee_ID         Name  Age Department  Salary  Experience   City
8          109  Karan Singh   31         IT   75000           6  Delhi
5          106  Sneha Gupta   35         IT   70000           7  Delhi

In [ ]:
Q1

Find all employees with salary greater than ₹60,000.

Q2

Find all employees with experience of at least 5 years.

Q3

Find all employees younger than 30.

Q4

Find all employees from Delhi.

Q5

Find employees from the IT department with salary greater than ₹60,000.

In [ ]:
Q1. Find all employees with salary greater than ₹60,000.

In [139]:
df[df["Salary"]>60000]

   Employee_ID         Name  Age Department  Salary  Experience    City
1          102  Priya Singh   32         HR   65000           6  Mumbai
3          104   Neha Verma   41    Finance   80000          10    Pune
5          106  Sneha Gupta   35         IT   70000           7   Delhi
8          109  Karan Singh   31         IT   75000           6   Delhi

In [ ]:
Q2

Find all employees with experience of at least 5 years.

In [143]:
df[df["Experience"]>=5]

   Employee_ID          Name  Age Department  Salary  Experience    City
1          102   Priya Singh   32         HR   65000           6  Mumbai
3          104    Neha Verma   41    Finance   80000          10    Pune
5          106   Sneha Gupta   35         IT   70000           7   Delhi
6          107   Vikas Kumar   29    Finance   60000           5    Pune
7          108  Pooja Sharma   45         HR   55000           8  Mumbai
8          109   Karan Singh   31         IT   75000           6   Delhi

In [ ]:
Q3

Find all employees younger than 30.

In [147]:
df[df["Age"]<30]

   Employee_ID          Name  Age Department  Salary  Experience    City
0          101  Rahul Sharma   25         IT   50000           2   Delhi
2          103    Amit Kumar   28         IT   45000           3   Delhi
4          105   Rohit Singh   24         HR   40000           1  Mumbai
6          107   Vikas Kumar   29    Finance   60000           5    Pune
9          110  Anjali Verma   27    Finance   48000           2    Pune

In [ ]:
Q4

Find all employees from Delhi.

In [151]:
df[df["City"].isin(["Delhi"])]

   Employee_ID          Name  Age Department  Salary  Experience   City
0          101  Rahul Sharma   25         IT   50000           2  Delhi
2          103    Amit Kumar   28         IT   45000           3  Delhi
5          106   Sneha Gupta   35         IT   70000           7  Delhi
8          109   Karan Singh   31         IT   75000           6  Delhi

In [ ]:
Q5

Find employees from the IT department with salary greater than ₹60,000.

In [153]:
df[
(df["Department"]=="IT") &
(df["Salary"]>60000)
]

   Employee_ID         Name  Age Department  Salary  Experience   City
5          106  Sneha Gupta   35         IT   70000           7  Delhi
8          109  Karan Singh   31         IT   75000           6  Delhi

In [ ]:
Q6

Find employees from:

IT
HR

using isin().

Q7

Find employees who are not from IT.

Q8

Find employees whose age is between 25 and 35.

Q9

Find employees whose salary is between ₹50,000 and ₹70,000.

Q10

Find employees from Delhi or Pune whose experience is at least 5 years

In [ ]:
Q6

Find employees from:

IT
HR

using isin().

In [159]:
df["City"].isin(["IT","HR"])

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: City, dtype: bool

In [ ]:
Q7

Find employees who are not from IT.

In [163]:
df[~df["Department"].isin(["IT"])]

   Employee_ID          Name  Age Department  Salary  Experience    City
1          102   Priya Singh   32         HR   65000           6  Mumbai
3          104    Neha Verma   41    Finance   80000          10    Pune
4          105   Rohit Singh   24         HR   40000           1  Mumbai
6          107   Vikas Kumar   29    Finance   60000           5    Pune
7          108  Pooja Sharma   45         HR   55000           8  Mumbai
9          110  Anjali Verma   27    Finance   48000           2    Pune

In [ ]:
Q8

Find employees whose age is between 25 and 35.

In [167]:
df[df["Age"].between(25,35)]

   Employee_ID          Name  Age Department  Salary  Experience    City
0          101  Rahul Sharma   25         IT   50000           2   Delhi
1          102   Priya Singh   32         HR   65000           6  Mumbai
2          103    Amit Kumar   28         IT   45000           3   Delhi
5          106   Sneha Gupta   35         IT   70000           7   Delhi
6          107   Vikas Kumar   29    Finance   60000           5    Pune
8          109   Karan Singh   31         IT   75000           6   Delhi
9          110  Anjali Verma   27    Finance   48000           2    Pune

In [ ]:
Q9

Find employees whose salary is between ₹50,000 and ₹70,000.

In [169]:
df["Salary"].between(50000,70000)

0     True
1     True
2    False
3    False
4    False
5     True
6     True
7     True
8    False
9    False
Name: Salary, dtype: bool

In [ ]:
10

Find employees from Delhi or Pune whose experience is at least 5 years

In [171]:
df[
(df["City"].isin(["Delhi","Pune"]))&
(df["Experience"]>5)
]

   Employee_ID         Name  Age Department  Salary  Experience   City
3          104   Neha Verma   41    Finance   80000          10   Pune
5          106  Sneha Gupta   35         IT   70000           7  Delhi
8          109  Karan Singh   31         IT   75000           6  Delhi

In [ ]:
Q11

Find employees whose name contains "Sharma".

Q12

Find employees whose name contains "singh" regardless of capitalization.

Q13

Find employees whose name starts with "A".

Q14

Find employees whose name ends with "Kumar".

Q15

Find employees whose name contains "a" and whose salary is greater than ₹50,000.

In [ ]:
Q11

Find employees whose name contains "Sharma".

In [175]:
df[df["Name"].str.contains("Sharma")]

   Employee_ID          Name  Age Department  Salary  Experience    City
0          101  Rahul Sharma   25         IT   50000           2   Delhi
7          108  Pooja Sharma   45         HR   55000           8  Mumbai

In [ ]:
Q12

Find employees whose name contains "singh" regardless of capitalization.

In [179]:
df[df["Name"].str.contains("singh",case=False)]

   Employee_ID         Name  Age Department  Salary  Experience    City
1          102  Priya Singh   32         HR   65000           6  Mumbai
4          105  Rohit Singh   24         HR   40000           1  Mumbai
8          109  Karan Singh   31         IT   75000           6   Delhi

In [ ]:
Q13

Find employees whose name starts with "A".

In [183]:
df[df["Name"].str.startswith("A")]

   Employee_ID          Name  Age Department  Salary  Experience   City
2          103    Amit Kumar   28         IT   45000           3  Delhi
9          110  Anjali Verma   27    Finance   48000           2   Pune

In [ ]:
Q14

Find employees whose name ends with "Kumar".

In [187]:
df[df["Name"].str.endswith("Kumar")]

   Employee_ID         Name  Age Department  Salary  Experience   City
2          103   Amit Kumar   28         IT   45000           3  Delhi
6          107  Vikas Kumar   29    Finance   60000           5   Pune

In [ ]:
Q15

Find employees whose name contains "a" and whose salary is greater than ₹50,000.

In [193]:
df[
(df["Name"].str.contains("a")) &
(df["Salary"]>50000)
]

   Employee_ID          Name  Age Department  Salary  Experience    City
1          102   Priya Singh   32         HR   65000           6  Mumbai
3          104    Neha Verma   41    Finance   80000          10    Pune
5          106   Sneha Gupta   35         IT   70000           7   Delhi
6          107   Vikas Kumar   29    Finance   60000           5    Pune
7          108  Pooja Sharma   45         HR   55000           8  Mumbai
8          109   Karan Singh   31         IT   75000           6   Delhi

In [ ]:
Q16

Find the top 3 highest-paid employees.

Q17

Find the 3 employees with the lowest salary.

Q18

Find the top 2 most experienced employees.

Q19

Find the highest-paid IT employee.

Use:

idxmax()
Q20

Find the least-experienced employee.

Use:

idxmin()

In [ ]:
Q16

Find the top 3 highest-paid employees.

In [203]:
df.nlargest(3,"Salary")

   Employee_ID         Name  Age Department  Salary  Experience   City
3          104   Neha Verma   41    Finance   80000          10   Pune
8          109  Karan Singh   31         IT   75000           6  Delhi
5          106  Sneha Gupta   35         IT   70000           7  Delhi

In [ ]:
Q17

Find the 3 employees with the lowest salary.

In [205]:
df.nsmallest(3,"Salary")

   Employee_ID          Name  Age Department  Salary  Experience    City
4          105   Rohit Singh   24         HR   40000           1  Mumbai
2          103    Amit Kumar   28         IT   45000           3   Delhi
9          110  Anjali Verma   27    Finance   48000           2    Pune

In [ ]:
Q18

Find the top 2 most experienced employees.

In [207]:
df.nlargest(2,"Experience")

   Employee_ID          Name  Age Department  Salary  Experience    City
3          104    Neha Verma   41    Finance   80000          10    Pune
7          108  Pooja Sharma   45         HR   55000           8  Mumbai

In [ ]:
Q19

Find the highest-paid IT employee.

Use:

idxmax()

In [209]:
df["Salary"].idxmax()

3

In [ ]:
20

Find the least-experienced employee.

Use:

idxmin()

In [213]:
df["Salary"].idxmin()

4

In [ ]:
Q21

Find the top 2 highest-paid employees from each department.

Hint:

You already learned this pattern in Lesson 3.

Q22

Find employees satisfying all conditions:

Department = IT
Age < 35
Salary > 50000
Experience >= 5
Q23

Find employees satisfying either:

Salary >= 70000

OR

Experience >= 8
Q24 💼

HR wants employees eligible for a senior position.

Conditions:

Experience >= 6
AND
Salary >= 60000
AND
Age <= 40

Return:

Name
Department
Age
Salary
Experience

Sort by salary descending.

In [ ]:
Q21

Find the top 2 highest-paid employees from each department.

In [225]:
df.groupby("Department")["Salary"].nlargest(2)

Department
Finance     3    80000
            6    60000
HR          1    65000
            7    55000
IT          8    75000
            5    70000
Name: Salary, dtype: int64

In [ ]:
22

Find employees satisfying all conditions:

Department = IT
Age < 35
Salary > 50000
Experience >= 5

In [233]:
df[
(df["Department"]=="IT") &
(df["Age"]<35) &
(df["Salary"]>50000) &
(df["Experience"]>=5)
]

   Employee_ID         Name  Age Department  Salary  Experience   City
8          109  Karan Singh   31         IT   75000           6  Delhi

In [ ]:
Q23

Find employees satisfying either:

Salary >= 70000

OR

Experience >= 8

In [235]:
df[
(df["Salary"]>=70000) |
(df["Experience"]>=8)
]

   Employee_ID          Name  Age Department  Salary  Experience    City
3          104    Neha Verma   41    Finance   80000          10    Pune
5          106   Sneha Gupta   35         IT   70000           7   Delhi
7          108  Pooja Sharma   45         HR   55000           8  Mumbai
8          109   Karan Singh   31         IT   75000           6   Delhi

In [ ]:
Q24 💼

HR wants employees eligible for a senior position.

Conditions:

Experience >= 6
AND
Salary >= 60000
AND
Age <= 40

Return:

Name
Department
Age
Salary
Experience

Sort by salary descending.

In [239]:
df[
(df["Experience"] >=6 )&
(df["Salary"]>=60000) &
(df["Age"]<=40)
]

   Employee_ID         Name  Age Department  Salary  Experience    City
1          102  Priya Singh   32         HR   65000           6  Mumbai
5          106  Sneha Gupta   35         IT   70000           7   Delhi
8          109  Karan Singh   31         IT   75000           6   Delhi

In [ ]:
Q25 — Data Analyst Challenge

HR asks:

"Give me the top 3 IT employees who are based in Delhi or Mumbai, have at least 5 years of experience, and earn between ₹50,000 and ₹80,000."

In [241]:
df[
(df["Department"]=='IT') &
(df["City"].isin(["Delhi","Mumbai"]))&
(df["Experience"]>5) &
(df["Salary"].between(
    50000,80000
))
].nlargest(3,"Salary")

   Employee_ID         Name  Age Department  Salary  Experience   City
8          109  Karan Singh   31         IT   75000           6  Delhi
5          106  Sneha Gupta   35         IT   70000           7  Delhi