In [ ]:
vectorization

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit"],
    "Salary": [30000, 40000, 50000, 60000, 70000]
})
df

    Name  Salary
0  Rahul   30000
1  Priya   40000
2   Amit   50000
3   Neha   60000
4  Rohit   70000

In [ ]:
Maan lo tumhare paas 5 employees ki salary hai aur har employee ko ₹5,000 bonus dena hai.

In [5]:
df["New_Salary"]=df["Salary"]+5000
df

    Name  Salary  New_Salary
0  Rahul   30000       35000
1  Priya   40000       45000
2   Amit   50000       55000
3   Neha   60000       65000
4  Rohit   70000       75000

In [ ]:
Requirement: salary ₹50,000 se kam hai to 10% increment; otherwise 5%

In [67]:
import numpy as np
np.where(
    df["Salary"]>50000,
    df["Salary"]*1.10,
    df["Salary"]*1.05
)

array([31500., 42000., 52500., 66000., 77000.])

In [17]:
for index,row in df.iterrows():
    print(row["Name"],row["Salary"])

Rahul 30000
Priya 40000
Amit 50000
Neha 60000
Rohit 70000

In [25]:
for row in df.itertuples(index=False):
    print(row.Name,row.Salary)

Rahul 30000
Priya 40000
Amit 50000
Neha 60000
Rohit 70000

In [ ]:
Q1. Bonus calculation
Vectorization use karke har employee ki salary mein ₹3,000 add karo. New column ka naam Bonus_Salary rakho.

Q2. Salary increment
Salary ₹50,000 se kam ho to 10% increment, warna 5%. np.where() use karo aur Incremented_Salary column banao.

Q3. Conditional filtering
Salary ₹40,000 se zyada wale employees select karo. Pehle normal filtering, phir query() use karke solve karo.

Q4. Memory inspection
DataFrame ki har column ka data type aur total memory usage inspect karo. memory_usage(deep=True) use karo.

Q5. Performance comparison
Ek 100,000-row DataFrame banao. Salary mein 1000 add karne ke liye vectorized method aur Python loop ka execution time compare karo.

In [ ]:
1. Bonus calculation
Vectorization use karke har employee ki salary mein ₹3,000 add karo. New column ka naam Bonus_Salary rakho.

In [27]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit"],
    "Salary": [30000, 40000, 50000, 60000, 70000]
})
df

    Name  Salary
0  Rahul   30000
1  Priya   40000
2   Amit   50000
3   Neha   60000
4  Rohit   70000

In [31]:
df["Bonus_Salary"]=df["Salary"]+3000
df

    Name  Salary  Bonus_Salary
0  Rahul   30000         33000
1  Priya   40000         43000
2   Amit   50000         53000
3   Neha   60000         63000
4  Rohit   70000         73000

In [ ]:
Q2. Salary increment
Salary ₹50,000 se kam ho to 10% increment, warna 5%. np.where() use karo aur Incremented_Salary column banao.

In [33]:
import numpy as np
np.where(
    df["Salary"]>50000,
    df["Salary"]*0.10,
    df["Salary"]*0.05
)

array([1500., 2000., 2500., 6000., 7000.])

In [35]:
sales_df = pd.DataFrame({
    "Product": ["Laptop", "Mobile", "Tablet", "Monitor"],
    "Price": [50000, 20000, 15000, 12000],
    "Quantity": [2, 5, 3, 4]
})
sales_df

   Product  Price  Quantity
0   Laptop  50000         2
1   Mobile  20000         5
2   Tablet  15000         3
3  Monitor  12000         4

In [ ]:
har product ki total revenue calculate karo.

In [45]:
sales_df["Revenue"]=sales_df["Price"] * sales_df["Quantity"]
sales_df

   Product  Price  Quantity  Revenue
0   Laptop  50000         2   100000
1   Mobile  20000         5   100000
2   Tablet  15000         3    45000
3  Monitor  12000         4    48000

In [ ]:
Har employee ki annual salary calculate karo. Assume salary monthly hai. Column ka naam `Annual_Salary` rakho.

In [49]:
df["Annual_Salary"]=df["Salary"]*12
df

    Name  Salary  Bonus_Salary  Annual_Salary
0  Rahul   30000         33000         360000
1  Priya   40000         43000         480000
2   Amit   50000         53000         600000
3   Neha   60000         63000         720000
4  Rohit   70000         73000         840000

In [ ]:
Har employee ki salary se ₹2,000 subtract karo aur result `Salary_After_Deduction` mein store karo.

In [53]:
df["Salary_After_Deduction"]=df["Salary"]-2000
df

    Name  Salary  Bonus_Salary  Annual_Salary  Salary_After_Deduction
0  Rahul   30000         33000         360000                   28000
1  Priya   40000         43000         480000                   38000
2   Amit   50000         53000         600000                   48000
3   Neha   60000         63000         720000                   58000
4  Rohit   70000         73000         840000                   68000

In [ ]:
Har employee ki salary ko 1.5 se multiply karo. Naya column `Revised_Salary` banao. Python loop use nahi karna.

In [57]:
df["Revised_Salary"]=df["Salary"]*1.5
df

,Name,Salary,Bonus_Salary,Annual_Salary,Salary_After_Deduction,Revised_Salary
0,Rahul,30000,33000,360000,28000,45000.0
1,Priya,40000,43000,480000,38000,60000.0
2,Amit,50000,53000,600000,48000,75000.0
3,Neha,60000,63000,720000,58000,90000.0
4,Rohit,70000,73000,840000,68000,105000.0

In [ ]:
Conditional Vectorization with np.where()

In [59]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit"],
    "Salary": [30000, 40000, 50000, 60000, 70000]
})
df

    Name  Salary
0  Rahul   30000
1  Priya   40000
2   Amit   50000
3   Neha   60000
4  Rohit   70000

In [ ]:
Maan lo company salary ke basis par employees ko increment dena chahti hai:
- Salary ₹50,000 se kam hai → 10% increment.
- Salary ₹50,000 ya usse zyada hai → 5% increment.

In [65]:
df["New_Salary"]=np.where(
    df["Salary"]<50000,
    df["Salary"]*1.10,
    df["Salary"]*1.05
)
df

    Name  Salary  New_Salary
0  Rahul   30000     33000.0
1  Priya   40000     44000.0
2   Amit   50000     52500.0
3   Neha   60000     63000.0
4  Rohit   70000     73500.0

In [ ]:
Q6: Salary ₹40,000 se kam ho toh "Junior", warna "Senior" assign karo. Column: Level.



Q7: Salary ₹50,000 se zyada ho toh "Eligible", warna "Not Eligible" assign karo. Column: Bonus_Status.



Q8: Salary ₹40,000 se kam ho toh 15% increment, warna 7% increment calculate karo. Column: Revised_Salary.



Q9: Salary ₹30,000 se zyada aur ₹60,000 se kam ho toh "Medium", otherwise "Other" assign karo.



Q10: Salary ₹50,000 ya usse zyada ho toh ₹5,000 bonus, warna ₹2,000 bonus do. Column: Bonus.

In [69]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit"],
    "Salary": [30000, 40000, 50000, 60000, 70000]
})
df

    Name  Salary
0  Rahul   30000
1  Priya   40000
2   Amit   50000
3   Neha   60000
4  Rohit   70000

In [ ]:
Q6: Salary ₹40,000 se kam ho toh "Junior", warna "Senior" assign karo. Column: Level.

In [73]:
df["Level"]=np.where(
    df["Salary"]<40000,"Junior","Senior"
)
df

    Name  Salary   Level
0  Rahul   30000  Junior
1  Priya   40000  Senior
2   Amit   50000  Senior
3   Neha   60000  Senior
4  Rohit   70000  Senior

In [ ]:
Q7: Salary ₹50,000 se zyada ho toh "Eligible", warna "Not Eligible" assign karo. Column: Bonus_Status.

In [77]:
df["Bonus_Status"]=np.where(
    df["Salary"]>50000,"Eligible","Not Eligible"
)
df

    Name  Salary   Level  Bonus_Status
0  Rahul   30000  Junior  Not Eligible
1  Priya   40000  Senior  Not Eligible
2   Amit   50000  Senior  Not Eligible
3   Neha   60000  Senior      Eligible
4  Rohit   70000  Senior      Eligible

In [ ]:
Q8: Salary ₹40,000 se kam ho toh 15% increment, warna 7% increment calculate karo. Column: Revised_Salary.

In [81]:
df["Revised_Salary"]=np.where(
    df["Salary"]<40000,
    df["Salary"]*1.15,
    df["Salary"]*1.07
)
df

    Name  Salary   Level  Bonus_Status  Revised_Salary
0  Rahul   30000  Junior  Not Eligible         34500.0
1  Priya   40000  Senior  Not Eligible         42800.0
2   Amit   50000  Senior  Not Eligible         53500.0
3   Neha   60000  Senior      Eligible         64200.0
4  Rohit   70000  Senior      Eligible         74900.0

In [ ]:
Q9: Salary ₹30,000 se zyada aur ₹60,000 se kam ho toh "Medium", otherwise "Other" assign karo.

In [88]:
np.where(
    (df["Salary"]>30000) & (df["Salary"]<60000) ,"Medium","Other"
)

array(['Other', 'Medium', 'Medium', 'Other', 'Other'], dtype='<U6')

In [ ]:
Q10: Salary ₹50,000 ya usse zyada ho toh ₹5,000 bonus, warna ₹2,000 bonus do. Column: Bonus.

In [94]:
df["Bonus"]=np.where(
    df["Salary"]>50000,
    df["Salary"]+5000,
    df["Salary"]+2000
)
df

    Name  Salary   Level  Bonus_Status  Revised_Salary  Bonus
0  Rahul   30000  Junior  Not Eligible         34500.0  32000
1  Priya   40000  Senior  Not Eligible         42800.0  42000
2   Amit   50000  Senior  Not Eligible         53500.0  52000
3   Neha   60000  Senior      Eligible         64200.0  65000
4  Rohit   70000  Senior      Eligible         74900.0  75000

In [ ]:
query()

In [96]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [30000, 40000, 50000, 60000, 70000],
    "Age": [22, 25, 28, 32, 35]
})
df

    Name Department  Salary  Age
0  Rahul         IT   30000   22
1  Priya         HR   40000   25
2   Amit         IT   50000   28
3   Neha    Finance   60000   32
4  Rohit         HR   70000   35

In [ ]:
Salary ₹50,000 se zyada

In [98]:
df.query("Salary>50000")

    Name Department  Salary  Age
3   Neha    Finance   60000   32
4  Rohit         HR   70000   35

In [ ]:
Maan lo humein un employees ko select karna hai jinki salary ₹40,000 se zyada hai aur age 30 se kam hai.

In [102]:
df.query("Salary > 40000 and Age<30")

   Name Department  Salary  Age
2  Amit         IT   50000   28

In [104]:
df.query("Department =='IT' or Salary > 60000")

    Name Department  Salary  Age
0  Rahul         IT   30000   22
2   Amit         IT   50000   28
4  Rohit         HR   70000   35

In [106]:
df.query("30000<=Salary <=60000")

    Name Department  Salary  Age
0  Rahul         IT   30000   22
1  Priya         HR   40000   25
2   Amit         IT   50000   28
3   Neha    Finance   60000   32

In [ ]:
Q11

High Salary Employees
Sirf un employees ko select karo jinki salary ₹60,000 se zyada hai.
Expected: Rohit



Q12

Young Employees
Age 30 se kam wale employees select karo.
Expected: Rahul, Priya, Amit



Q13

IT Department
Sirf IT department ke employees select karo.
Expected: Rahul, Amit



Q14

Multiple Conditions
Un employees ko select karo jinki salary ₹30,000 se zyada hai aur age 30 ya usse zyada hai.
Expected: Neha, Rohit



Q15

Salary Range
Un employees ko select karo jinki salary ₹40,000 se ₹70,000 ke beech hai, dono limits included.
Expected: Priya, Amit, Neha, Rohit


Show hints

In [108]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [30000, 40000, 50000, 60000, 70000],
    "Age": [22, 25, 28, 32, 35]
})
df

    Name Department  Salary  Age
0  Rahul         IT   30000   22
1  Priya         HR   40000   25
2   Amit         IT   50000   28
3   Neha    Finance   60000   32
4  Rohit         HR   70000   35

In [ ]:
Q11

High Salary Employees
Sirf un employees ko select karo jinki salary ₹60,000 se zyada hai.
Expected: Rohit

In [110]:
df.query("Salary > 60000")

    Name Department  Salary  Age
4  Rohit         HR   70000   35

In [ ]:

Q12

Young Employees
Age 30 se kam wale employees select karo.
Expected: Rahul, Priya, Amit

In [112]:
df.query("Age < 30")

    Name Department  Salary  Age
0  Rahul         IT   30000   22
1  Priya         HR   40000   25
2   Amit         IT   50000   28

In [ ]:
Q13

IT Department
Sirf IT department ke employees select karo.
Expected: Rahul, Amit

In [114]:
df.query("Department=='IT'")

    Name Department  Salary  Age
0  Rahul         IT   30000   22
2   Amit         IT   50000   28

In [ ]:
Q14

Multiple Conditions
Un employees ko select karo jinki salary ₹30,000 se zyada hai aur age 30 ya usse zyada hai.
Expected: Neha, Rohit

In [116]:
df.query("Salary>30000 and Age>30")

    Name Department  Salary  Age
3   Neha    Finance   60000   32
4  Rohit         HR   70000   35

In [ ]:

Q15

Salary Range
Un employees ko select karo jinki salary ₹40,000 se ₹70,000 ke beech hai, dono limits included.
Expected: Priya, Amit, Neha, Rohit

In [118]:
df.query("40000<=Salary<=70000")

    Name Department  Salary  Age
1  Priya         HR   40000   25
2   Amit         IT   50000   28
3   Neha    Finance   60000   32
4  Rohit         HR   70000   35

In [ ]:
eval()

In [124]:
df.eval("Annual_Salary=Salary*12",inplace=True)
df

    Name Department  Salary  Age  Annual_Salary
0  Rahul         IT   30000   22         360000
1  Priya         HR   40000   25         480000
2   Amit         IT   50000   28         600000
3   Neha    Finance   60000   32         720000
4  Rohit         HR   70000   35         840000

In [126]:
import pandas as pd

df = pd.DataFrame({
    "Product": ["Laptop", "Mobile", "Tablet", "Monitor"],
    "Price": [50000, 20000, 15000, 12000],
    "Quantity": [2, 5, 3, 4]
})

df

   Product  Price  Quantity
0   Laptop  50000         2
1   Mobile  20000         5
2   Tablet  15000         3
3  Monitor  12000         4

In [ ]:
har product ki total sales calculate karni hai.

In [132]:
df.eval("Revenue=Price * Quantity",inplace=True)
df

   Product  Price  Quantity  Revenue
0   Laptop  50000         2   100000
1   Mobile  20000         5   100000
2   Tablet  15000         3    45000
3  Monitor  12000         4    48000

In [ ]:
Maan lo tumhe discount ke baad price calculate karna hai.

In [142]:
df.eval("Discount=Price*0.10",inplace=True)
df.eval("Final_Price=Price - Discount",inplace=True)
df

   Product  Price  Quantity  Revenue  Discount  Final_Price
0   Laptop  50000         2   100000    5000.0      45000.0
1   Mobile  20000         5   100000    2000.0      18000.0
2   Tablet  15000         3    45000    1500.0      13500.0
3  Monitor  12000         4    48000    1200.0      10800.0

In [144]:
df = pd.DataFrame({
    "Product": ["Laptop", "Mobile", "Tablet", "Monitor"],
    "Price": [50000, 20000, 15000, 12000],
    "Quantity": [2, 5, 3, 4]
})
df

   Product  Price  Quantity
0   Laptop  50000         2
1   Mobile  20000         5
2   Tablet  15000         3
3  Monitor  12000         4

In [ ]:
Q16

Total Revenue
Price × Quantity calculate karke Revenue column banao, using eval().



Q17

10% Discount
Price × 0.10 calculate karke Discount column banao.



Q18

Final Price
Price − Discount calculate karke Final_Price column banao. Q17 ka Discount column available hona chahiye.



Q19

Double Quantity Revenue
Price × Quantity × 2 calculate karke Double_Revenue column banao.



Q20

Revenue Per Unit
Revenue ÷ Quantity calculate karke Revenue_Per_Unit column banao. Pehle Revenue column create karna.

In [ ]:
Q16

Total Revenue
Price × Quantity calculate karke Revenue column banao, using eval().

In [146]:
df.eval("Revenue=Price * Quantity")

   Product  Price  Quantity  Revenue
0   Laptop  50000         2   100000
1   Mobile  20000         5   100000
2   Tablet  15000         3    45000
3  Monitor  12000         4    48000

In [ ]:

Q17

10% Discount
Price × 0.10 calculate karke Discount column banao.

In [152]:
df.eval(" Discount=Price * 0.10",inplace=True)
df

   Product  Price  Quantity  Discount
0   Laptop  50000         2    5000.0
1   Mobile  20000         5    2000.0
2   Tablet  15000         3    1500.0
3  Monitor  12000         4    1200.0

In [ ]:

Q18

Final Price
Price − Discount calculate karke Final_Price column banao. Q17 ka Discount column available hona chahiye.

In [156]:
df.eval("FinalPrice=Price-Discount")

   Product  Price  Quantity  Discount  FinalPrice
0   Laptop  50000         2    5000.0     45000.0
1   Mobile  20000         5    2000.0     18000.0
2   Tablet  15000         3    1500.0     13500.0
3  Monitor  12000         4    1200.0     10800.0

In [ ]:

Q19

Double Quantity Revenue
Price × Quantity × 2 calculate karke Double_Revenue column banao.

In [158]:
df.eval("Double_Revenue = Price*Quantity*2")

   Product  Price  Quantity  Discount  Double_Revenue
0   Laptop  50000         2    5000.0          200000
1   Mobile  20000         5    2000.0          200000
2   Tablet  15000         3    1500.0           90000
3  Monitor  12000         4    1200.0           96000

In [ ]:
Q20

Revenue Per Unit
Revenue ÷ Quantity calculate karke Revenue_Per_Unit column banao. Pehle Revenue column create karna.

In [162]:
df.eval("Revenue=Price * Quantity",inplace=True)
df

   Product  Price  Quantity  Discount  Revenue
0   Laptop  50000         2    5000.0   100000
1   Mobile  20000         5    2000.0   100000
2   Tablet  15000         3    1500.0    45000
3  Monitor  12000         4    1200.0    48000

In [164]:
df.eval("Revenue_Per_Unit=Revenue/ Quantity")

   Product  Price  Quantity  Discount  Revenue  Revenue_Per_Unit
0   Laptop  50000         2    5000.0   100000           50000.0
1   Mobile  20000         5    2000.0   100000           20000.0
2   Tablet  15000         3    1500.0    45000           15000.0
3  Monitor  12000         4    1200.0    48000           12000.0

In [ ]:
Memory Optimization in Pandas

In [168]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit"],
    "Age": [22, 25, 28, 32, 35],
    "Salary": [30000, 40000, 50000, 60000, 70000],
    "Department": ["IT", "HR", "IT", "Finance", "HR"]
})

df.memory_usage(deep=True)

Index         132
Name          268
Age            40
Salary         40
Department    260
dtype: int64

In [178]:
df.memory_usage(deep=True).sum()

740

In [ ]:
megabytes me convert krne ke lye

In [180]:
df.memory_usage(deep=True).sum()/(1024**2)

0.000705718994140625

In [184]:
df["Age"].astype('int32')

0    22
1    25
2    28
3    32
4    35
Name: Age, dtype: int32

In [186]:
df["Salary"].astype('int32')

0    30000
1    40000
2    50000
3    60000
4    70000
Name: Salary, dtype: int32

In [188]:
df["Department"].astype('category')

0         IT
1         HR
2         IT
3    Finance
4         HR
Name: Department, dtype: category
Categories (3, object): ['Finance', 'HR', 'IT']

In [190]:
df["Department"] = df["Department"].astype("object")
before = df["Department"].memory_usage(deep=True)

df["Department"] = df["Department"].astype("category")
after = df["Department"].memory_usage(deep=True)

print("Before:", before)
print("After:", after)

Before: 392
After: 403

In [192]:
df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D", "E", "F"],
    "Age": [22, 25, 28, 32, 35, 27],
    "Salary": [30000, 40000, 50000, 60000, 70000, 45000],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"]
})
df

  Employee  Age  Salary Department
0        A   22   30000         IT
1        B   25   40000         HR
2        C   28   50000         IT
3        D   32   60000    Finance
4        E   35   70000         HR
5        F   27   45000         IT

In [ ]:
Q21

Check Data Types
Saare columns ke data types print karo.
Goal: dtypes samajhna



Q22

Measure Memory
Har column ki memory usage deep=True ke saath print karo.



Q23

Optimize Age
Age column ko int32 mein convert karo aur uska naya data type check karo.



Q24

Optimize Department
Department ko category mein convert karo aur verify karo ki conversion successful hai.

In [ ]:
Q21

Check Data Types
Saare columns ke data types print karo.
Goal: dtypes samajhna

In [194]:
df.dtypes

Employee      object
Age            int64
Salary         int64
Department    object
dtype: object

In [ ]:

Q22

Measure Memory
Har column ki memory usage deep=True ke saath print karo.

In [196]:
df.memory_usage(deep=True)

Index         132
Employee      300
Age            48
Salary         48
Department    311
dtype: int64

In [ ]:
Q23

Optimize Age
Age column ko int32 mein convert karo aur uska naya data type check karo.

In [198]:
df["Age"].astype('int32')

0    22
1    25
2    28
3    32
4    35
5    27
Name: Age, dtype: int32

In [ ]:
24

Optimize Department
Department ko category mein convert karo aur verify karo ki conversion successful hai.

In [200]:
df["Department"].astype('category')

0         IT
1         HR
2         IT
3    Finance
4         HR
5         IT
Name: Department, dtype: category
Categories (3, object): ['Finance', 'HR', 'IT']