In [1]:
import pandas as pd
data={
    "Name":["Rahul","Priya","Amit","Neha"],
    "Age":[25,28,30,26],
    "Department":["IT","HR","IT","Finance"],
    "Salary":[50000, 45000, 65000, 55000]
    
}
df=pd.DataFrame(data)
print(df)

    Name  Age Department  Salary
0  Rahul   25         IT   50000
1  Priya   28         HR   45000
2   Amit   30         IT   65000
3   Neha   26    Finance   55000

In [5]:
#Q1. Display the first 2 rows.
df.head(2)

    Name  Age Department  Salary
0  Rahul   25         IT   50000
1  Priya   28         HR   45000

In [17]:
#Q2. Display only the Name column.
df["Name"]

0    Rahul
1    Priya
2     Amit
3     Neha
Name: Name, dtype: object

In [19]:
#Q3. Find the number of rows and columns.
df.shape

(4, 4)

In [33]:
#Q4. Find the employee with the highest salary.
df["Salary"].max()

65000

In [39]:
#Q5. Find all employees who work in the IT department.
df[df["Department"]=="IT"]

    Name  Age Department  Salary
0  Rahul   25         IT   50000
2   Amit   30         IT   65000

In [47]:
#Q6.Find employees whose salary is greater than 50000.
df[df["Salary"]>50000]

   Name  Age Department  Salary
2  Amit   30         IT   65000
3  Neha   26    Finance   55000

In [51]:
#Q7.Find employees whose age is greater than 25.
df[df["Age"]>25]

    Name  Age Department  Salary
1  Priya   28         HR   45000
2   Amit   30         IT   65000
3   Neha   26    Finance   55000

In [57]:
#Q8.Display only the Name and Salary columns.
df[["Name","Salary"]]

    Name  Salary
0  Rahul   50000
1  Priya   45000
2   Amit   65000
3   Neha   55000

In [63]:
#Q9.Find the minimum salary.
df["Salary"].min()

45000

In [65]:
#Q10.Find the employee who has the highest salary.
df["Salary"].max()

65000