In [ ]:
Advanced string amd text data processing

In [1]:
import pandas as pd

data = {
    "Name": [
        "  Rahul Sharma ",
        "PRIYA SINGH",
        "amit kumar  ",
        " Neha Verma",
        "ROHIT SINGH ",
        "sneha gupta",
        "  VIKAS KUMAR",
        "Pooja Sharma  ",
        "karan singh",
        " ANJALI VERMA "
    ],

    "Email": [
        "rahul.sharma@gmail.com",
        "PRIYA.SINGH@YAHOO.COM",
        "amit.kumar@gmail.com",
        "neha.verma@outlook.com",
        "rohit.singh@gmail.com",
        "SNEHA.GUPTA@YAHOO.COM",
        "vikas.kumar@gmail.com",
        "pooja.sharma@outlook.com",
        "karan.singh@gmail.com",
        "anjali.verma@yahoo.com"
    ],

    "Department": [
        "it", "HR", "IT ", "finance", "HR",
        " it", "Finance", "HR", "IT", "finance "
    ],

    "City": [
        "Delhi", "mumbai", "DELHI", "Pune",
        " Mumbai ", "delhi", "PUNE", "Mumbai",
        "DELHI ", "pune"
    ],

    "Phone": [
        "9876543210",
        "987-654-3211",
        "987 654 3212",
        "+91-9876543213",
        "9876543214",
        "987-654-3215",
        "987 654 3216",
        "+91 9876543217",
        "9876543218",
        "987-654-3219"
    ]
}

df = pd.DataFrame(data)
df

,Name,Email,Department,City,Phone
0,Rahul Sharma,rahul.sharma@gmail.com,it,Delhi,9876543210
1,PRIYA SINGH,PRIYA.SINGH@YAHOO.COM,HR,mumbai,987-654-3211
2,amit kumar,amit.kumar@gmail.com,IT,DELHI,987 654 3212
3,Neha Verma,neha.verma@outlook.com,finance,Pune,+91-9876543213
4,ROHIT SINGH,rohit.singh@gmail.com,HR,Mumbai,9876543214
5,sneha gupta,SNEHA.GUPTA@YAHOO.COM,it,delhi,987-654-3215
6,VIKAS KUMAR,vikas.kumar@gmail.com,Finance,PUNE,987 654 3216
7,Pooja Sharma,pooja.sharma@outlook.com,HR,Mumbai,+91 9876543217
8,karan singh,karan.singh@gmail.com,IT,DELHI,9876543218
9,ANJALI VERMA,anjali.verma@yahoo.com,finance,pune,987-654-3219

In [ ]:
.str.lower()

In [3]:
df["Name"].str.lower()

0      rahul sharma
1        priya singh
2       amit kumar
3         neha verma
4       rohit singh
5        sneha gupta
6        vikas kumar
7     pooja sharma
8        karan singh
9      anjali verma
Name: Name, dtype: object

In [ ]:
.str.upper()

In [5]:
df["Name"].str.upper()

0      RAHUL SHARMA
1        PRIYA SINGH
2       AMIT KUMAR
3         NEHA VERMA
4       ROHIT SINGH
5        SNEHA GUPTA
6        VIKAS KUMAR
7     POOJA SHARMA
8        KARAN SINGH
9      ANJALI VERMA
Name: Name, dtype: object

In [ ]:
.str.title()

In [7]:
df["Name"].str.title()

0      Rahul Sharma
1        Priya Singh
2       Amit Kumar
3         Neha Verma
4       Rohit Singh
5        Sneha Gupta
6        Vikas Kumar
7     Pooja Sharma
8        Karan Singh
9      Anjali Verma
Name: Name, dtype: object

In [ ]:
.str.strip()

In [9]:
df["Name"].str.strip()

0    Rahul Sharma
1     PRIYA SINGH
2      amit kumar
3      Neha Verma
4     ROHIT SINGH
5     sneha gupta
6     VIKAS KUMAR
7    Pooja Sharma
8     karan singh
9    ANJALI VERMA
Name: Name, dtype: object

In [11]:
df["Name"].str.strip().str.title()

0    Rahul Sharma
1     Priya Singh
2      Amit Kumar
3      Neha Verma
4     Rohit Singh
5     Sneha Gupta
6     Vikas Kumar
7    Pooja Sharma
8     Karan Singh
9    Anjali Verma
Name: Name, dtype: object

In [13]:
df["Department"].str.strip().str.upper()

0         IT
1         HR
2         IT
3    FINANCE
4         HR
5         IT
6    FINANCE
7         HR
8         IT
9    FINANCE
Name: Department, dtype: object

In [15]:
df["Phone"].str.replace("-","")

0        9876543210
1        9876543211
2      987 654 3212
3     +919876543213
4        9876543214
5        9876543215
6      987 654 3216
7    +91 9876543217
8        9876543218
9        9876543219
Name: Phone, dtype: object

In [19]:
df["Phone"].str.replace(" ","")

0        9876543210
1      987-654-3211
2        9876543212
3    +91-9876543213
4        9876543214
5      987-654-3215
6        9876543216
7     +919876543217
8        9876543218
9      987-654-3219
Name: Phone, dtype: object

In [ ]:
remove multiple chracter using regex

In [21]:
df["Phone"].str.replace(
    r"[\s-]","",
    regex=True
    
)#remove spaces

0       9876543210
1       9876543211
2       9876543212
3    +919876543213
4       9876543214
5       9876543215
6       9876543216
7    +919876543217
8       9876543218
9       9876543219
Name: Phone, dtype: object

In [ ]:
.str.len()

In [23]:
df["Name"].str.len()

0    15
1    11
2    12
3    11
4    12
5    11
6    13
7    14
8    11
9    14
Name: Name, dtype: int64

In [ ]:
.str.contains()

In [33]:
df[
df["Name"].str.contains("Sharma",case=False)
]

,Name,Email,Department,City,Phone
0,Rahul Sharma,rahul.sharma@gmail.com,it,Delhi,9876543210
7,Pooja Sharma,pooja.sharma@outlook.com,HR,Mumbai,+91 9876543217

In [35]:
df[
df["Name"].str.startswith("R")
]

           Name                  Email Department      City       Phone
4  ROHIT SINGH   rohit.singh@gmail.com         HR   Mumbai   9876543214

In [37]:
df[
df["Name"].str.lower().str.startswith("r")
]

           Name                  Email Department      City       Phone
4  ROHIT SINGH   rohit.singh@gmail.com         HR   Mumbai   9876543214

In [45]:
df[
df["Name"].str.lower().str.endswith("singh")
]

          Name                  Email Department    City         Phone
1  PRIYA SINGH  PRIYA.SINGH@YAHOO.COM         HR  mumbai  987-654-3211
8  karan singh  karan.singh@gmail.com         IT  DELHI     9876543218

In [47]:
df["Name"].str.split()

0    [Rahul, Sharma]
1     [PRIYA, SINGH]
2      [amit, kumar]
3      [Neha, Verma]
4     [ROHIT, SINGH]
5     [sneha, gupta]
6     [VIKAS, KUMAR]
7    [Pooja, Sharma]
8     [karan, singh]
9    [ANJALI, VERMA]
Name: Name, dtype: object

In [ ]:
.str.get()

In [49]:
df["Name"].str.split().str.get(0)

0     Rahul
1     PRIYA
2      amit
3      Neha
4     ROHIT
5     sneha
6     VIKAS
7     Pooja
8     karan
9    ANJALI
Name: Name, dtype: object

In [51]:
df["Name"].str.split().str.get(1)

0    Sharma
1     SINGH
2     kumar
3     Verma
4     SINGH
5     gupta
6     KUMAR
7    Sharma
8     singh
9     VERMA
Name: Name, dtype: object

In [55]:
df["First_Name"]=df["Name"].str.split().str.get(0)
df

,Name,Email,Department,City,Phone,First_Name
0,Rahul Sharma,rahul.sharma@gmail.com,it,Delhi,9876543210,Rahul
1,PRIYA SINGH,PRIYA.SINGH@YAHOO.COM,HR,mumbai,987-654-3211,PRIYA
2,amit kumar,amit.kumar@gmail.com,IT,DELHI,987 654 3212,amit
3,Neha Verma,neha.verma@outlook.com,finance,Pune,+91-9876543213,Neha
4,ROHIT SINGH,rohit.singh@gmail.com,HR,Mumbai,9876543214,ROHIT
5,sneha gupta,SNEHA.GUPTA@YAHOO.COM,it,delhi,987-654-3215,sneha
6,VIKAS KUMAR,vikas.kumar@gmail.com,Finance,PUNE,987 654 3216,VIKAS
7,Pooja Sharma,pooja.sharma@outlook.com,HR,Mumbai,+91 9876543217,Pooja
8,karan singh,karan.singh@gmail.com,IT,DELHI,9876543218,karan
9,ANJALI VERMA,anjali.verma@yahoo.com,finance,pune,987-654-3219,ANJALI

In [59]:
df["Last_Name"]=df["Name"].str.split().str.get(1)
df

,Name,Email,Department,City,Phone,First_Name,Last_Name
0,Rahul Sharma,rahul.sharma@gmail.com,it,Delhi,9876543210,Rahul,Sharma
1,PRIYA SINGH,PRIYA.SINGH@YAHOO.COM,HR,mumbai,987-654-3211,PRIYA,SINGH
2,amit kumar,amit.kumar@gmail.com,IT,DELHI,987 654 3212,amit,kumar
3,Neha Verma,neha.verma@outlook.com,finance,Pune,+91-9876543213,Neha,Verma
4,ROHIT SINGH,rohit.singh@gmail.com,HR,Mumbai,9876543214,ROHIT,SINGH
5,sneha gupta,SNEHA.GUPTA@YAHOO.COM,it,delhi,987-654-3215,sneha,gupta
6,VIKAS KUMAR,vikas.kumar@gmail.com,Finance,PUNE,987 654 3216,VIKAS,KUMAR
7,Pooja Sharma,pooja.sharma@outlook.com,HR,Mumbai,+91 9876543217,Pooja,Sharma
8,karan singh,karan.singh@gmail.com,IT,DELHI,9876543218,karan,singh
9,ANJALI VERMA,anjali.verma@yahoo.com,finance,pune,987-654-3219,ANJALI,VERMA

In [61]:
df["Email"].str.split("@").str.get(1)

0      gmail.com
1      YAHOO.COM
2      gmail.com
3    outlook.com
4      gmail.com
5      YAHOO.COM
6      gmail.com
7    outlook.com
8      gmail.com
9      yahoo.com
Name: Email, dtype: object

In [65]:
df["Email"].str.split("@").str.get(0)

0    rahul.sharma
1     PRIYA.SINGH
2      amit.kumar
3      neha.verma
4     rohit.singh
5     SNEHA.GUPTA
6     vikas.kumar
7    pooja.sharma
8     karan.singh
9    anjali.verma
Name: Email, dtype: object

In [ ]:
.str.extract()-using regex

In [69]:
df["Email"].str.extract(
    r"@(.+)$"
)

             0
0    gmail.com
1    YAHOO.COM
2    gmail.com
3  outlook.com
4    gmail.com
5    YAHOO.COM
6    gmail.com
7  outlook.com
8    gmail.com
9    yahoo.com

In [ ]:
extract email provider-yahoo,gmail,outlook

In [73]:
df["Email"].str.extract(
    r"@([^.]+)"
)

         0
0    gmail
1    YAHOO
2    gmail
3  outlook
4    gmail
5    YAHOO
6    gmail
7  outlook
8    gmail
9    yahoo

In [ ]:
phone number cleaning

In [ ]:
non-numeric characters-\D-any character that is not digit

In [75]:
df["Phone"].str.replace(
    r"\D","",regex=True
)

0      9876543210
1      9876543211
2      9876543212
3    919876543213
4      9876543214
5      9876543215
6      9876543216
7    919876543217
8      9876543218
9      9876543219
Name: Phone, dtype: object

In [ ]:
phone number validating

In [79]:
df["Phone"].str.len()

0    10
1    12
2    12
3    14
4    10
5    12
6    12
7    14
8    10
9    12
Name: Phone, dtype: int64

In [83]:
df["Phone"].str.match(
    r"^[0-9]{10}$"
)

0     True
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8     True
9    False
Name: Phone, dtype: bool

In [ ]:
.str.findall()-to find out all digits inside a string

In [87]:
df["Phone"].str.findall(r"\d")

0          [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
1          [9, 8, 7, 6, 5, 4, 3, 2, 1, 1]
2          [9, 8, 7, 6, 5, 4, 3, 2, 1, 2]
3    [9, 1, 9, 8, 7, 6, 5, 4, 3, 2, 1, 3]
4          [9, 8, 7, 6, 5, 4, 3, 2, 1, 4]
5          [9, 8, 7, 6, 5, 4, 3, 2, 1, 5]
6          [9, 8, 7, 6, 5, 4, 3, 2, 1, 6]
7    [9, 1, 9, 8, 7, 6, 5, 4, 3, 2, 1, 7]
8          [9, 8, 7, 6, 5, 4, 3, 2, 1, 8]
9          [9, 8, 7, 6, 5, 4, 3, 2, 1, 9]
Name: Phone, dtype: object

In [89]:
import pandas as pd

data = {
    "Name": [
        "  Rahul Sharma ",
        "PRIYA SINGH",
        "amit kumar  ",
        " Neha Verma",
        "ROHIT SINGH ",
        "sneha gupta",
        "  VIKAS KUMAR",
        "Pooja Sharma  ",
        "karan singh",
        " ANJALI VERMA "
    ],

    "Email": [
        "rahul.sharma@gmail.com",
        "PRIYA.SINGH@YAHOO.COM",
        "amit.kumar@gmail.com",
        "neha.verma@outlook.com",
        "rohit.singh@gmail.com",
        "SNEHA.GUPTA@YAHOO.COM",
        "vikas.kumar@gmail.com",
        "pooja.sharma@outlook.com",
        "karan.singh@gmail.com",
        "anjali.verma@yahoo.com"
    ],

    "Department": [
        "it", "HR", "IT ", "finance", "HR",
        " it", "Finance", "HR", "IT", "finance "
    ],

    "City": [
        "Delhi", "mumbai", "DELHI", "Pune",
        " Mumbai ", "delhi", "PUNE", "Mumbai",
        "DELHI ", "pune"
    ],

    "Phone": [
        "9876543210",
        "987-654-3211",
        "987 654 3212",
        "+91-9876543213",
        "9876543214",
        "987-654-3215",
        "987 654 3216",
        "+91 9876543217",
        "9876543218",
        "987-654-3219"
    ]
}

df = pd.DataFrame(data)
df

,Name,Email,Department,City,Phone
0,Rahul Sharma,rahul.sharma@gmail.com,it,Delhi,9876543210
1,PRIYA SINGH,PRIYA.SINGH@YAHOO.COM,HR,mumbai,987-654-3211
2,amit kumar,amit.kumar@gmail.com,IT,DELHI,987 654 3212
3,Neha Verma,neha.verma@outlook.com,finance,Pune,+91-9876543213
4,ROHIT SINGH,rohit.singh@gmail.com,HR,Mumbai,9876543214
5,sneha gupta,SNEHA.GUPTA@YAHOO.COM,it,delhi,987-654-3215
6,VIKAS KUMAR,vikas.kumar@gmail.com,Finance,PUNE,987 654 3216
7,Pooja Sharma,pooja.sharma@outlook.com,HR,Mumbai,+91 9876543217
8,karan singh,karan.singh@gmail.com,IT,DELHI,9876543218
9,ANJALI VERMA,anjali.verma@yahoo.com,finance,pune,987-654-3219

In [ ]:
Q1
Remove leading and trailing spaces from Name.
Q2
Convert Name to lowercase.
Q3
Convert Name to proper title case.
Q4
Clean Department by removing spaces and converting everything to uppercase.
Q5
Clean City by removing spaces and converting it to title case.

In [ ]:
Q1
Remove leading and trailing spaces from Name.

In [91]:
df["Name"].str.strip()

0    Rahul Sharma
1     PRIYA SINGH
2      amit kumar
3      Neha Verma
4     ROHIT SINGH
5     sneha gupta
6     VIKAS KUMAR
7    Pooja Sharma
8     karan singh
9    ANJALI VERMA
Name: Name, dtype: object

In [ ]:
Q2
Convert Name to lowercase.

In [93]:
df["Name"].str.lower()

0      rahul sharma
1        priya singh
2       amit kumar
3         neha verma
4       rohit singh
5        sneha gupta
6        vikas kumar
7     pooja sharma
8        karan singh
9      anjali verma
Name: Name, dtype: object

In [ ]:
Q3
Convert Name to proper title case.

In [95]:
df["Name"].str.title()

0      Rahul Sharma
1        Priya Singh
2       Amit Kumar
3         Neha Verma
4       Rohit Singh
5        Sneha Gupta
6        Vikas Kumar
7     Pooja Sharma
8        Karan Singh
9      Anjali Verma
Name: Name, dtype: object

In [ ]:
Q4
Clean Department by removing spaces and converting everything to uppercase.

In [97]:
df["Department"].str.upper().str.strip()

0         IT
1         HR
2         IT
3    FINANCE
4         HR
5         IT
6    FINANCE
7         HR
8         IT
9    FINANCE
Name: Department, dtype: object

In [ ]:

Q5
Clean City by removing spaces and converting it to title case.

In [99]:
df["City"].str.strip().str.lower()

0     delhi
1    mumbai
2     delhi
3      pune
4    mumbai
5     delhi
6      pune
7    mumbai
8     delhi
9      pune
Name: City, dtype: object

In [ ]:
Q6
Find employees whose name contains "sharma".
Make the search case-insensitive.
Q7
Find employees whose name starts with "R".
Q8
Find employees whose name ends with "Singh".
Q9
Find employees whose names contain the letter "a".
Ignore capitalization.
Q10
Find names whose length is greater than 10 characters.

In [ ]:
Q6
Find employees whose name contains "sharma".
Make the search case-insensitive.

In [107]:
df[df["Name"].str.contains("sharma",case=False)]

,Name,Email,Department,City,Phone
0,Rahul Sharma,rahul.sharma@gmail.com,it,Delhi,9876543210
7,Pooja Sharma,pooja.sharma@outlook.com,HR,Mumbai,+91 9876543217

In [ ]:
Q7
Find employees whose name starts with "R".

In [115]:
df[df["Name"].str.startswith("R")]

           Name                  Email Department      City       Phone
4  ROHIT SINGH   rohit.singh@gmail.com         HR   Mumbai   9876543214

In [ ]:
Q8
Find employees whose name ends with "Singh".

In [123]:
df[

df["Name"].str.endswith("Singh")
]

Empty DataFrame
Columns: [Name, Email, Department, City, Phone]
Index: []

In [ ]:
Q9
Find employees whose names contain the letter "a".
Ignore capitalization.

In [127]:
df[df["Name"].str.contains("a")]

,Name,Email,Department,City,Phone
0,Rahul Sharma,rahul.sharma@gmail.com,it,Delhi,9876543210
2,amit kumar,amit.kumar@gmail.com,IT,DELHI,987 654 3212
3,Neha Verma,neha.verma@outlook.com,finance,Pune,+91-9876543213
5,sneha gupta,SNEHA.GUPTA@YAHOO.COM,it,delhi,987-654-3215
7,Pooja Sharma,pooja.sharma@outlook.com,HR,Mumbai,+91 9876543217
8,karan singh,karan.singh@gmail.com,IT,DELHI,9876543218

In [ ]:
Q10
Find names whose length is greater than 10 characters.

In [131]:
df[df["Name"].str.len()>10]

,Name,Email,Department,City,Phone
0,Rahul Sharma,rahul.sharma@gmail.com,it,Delhi,9876543210
1,PRIYA SINGH,PRIYA.SINGH@YAHOO.COM,HR,mumbai,987-654-3211
2,amit kumar,amit.kumar@gmail.com,IT,DELHI,987 654 3212
3,Neha Verma,neha.verma@outlook.com,finance,Pune,+91-9876543213
4,ROHIT SINGH,rohit.singh@gmail.com,HR,Mumbai,9876543214
5,sneha gupta,SNEHA.GUPTA@YAHOO.COM,it,delhi,987-654-3215
6,VIKAS KUMAR,vikas.kumar@gmail.com,Finance,PUNE,987 654 3216
7,Pooja Sharma,pooja.sharma@outlook.com,HR,Mumbai,+91 9876543217
8,karan singh,karan.singh@gmail.com,IT,DELHI,9876543218
9,ANJALI VERMA,anjali.verma@yahoo.com,finance,pune,987-654-3219

In [ ]:
Q11
Create:
First_Name

from Name.
Q12
Create:
Last_Name

from Name.
Q13
Extract the username from Email.
Example:
rahul.sharma@gmail.com
        ↓
rahul.sharma

Q14
Extract the complete email domain.
Example:
rahul.sharma@gmail.com
        ↓
gmail.com

Q15
Extract only the email provider:
gmail
yahoo
outlook

In [ ]:
Q11
Create:
First_Name

from Name.

In [145]:
df["Name"].str.split().str.get(0)

0     Rahul
1     PRIYA
2      amit
3      Neha
4     ROHIT
5     sneha
6     VIKAS
7     Pooja
8     karan
9    ANJALI
Name: Name, dtype: object

In [ ]:
Q12
Create:
Last_Name

from Name.

In [147]:
df["Name"].str.split().str.get(1)

0    Sharma
1     SINGH
2     kumar
3     Verma
4     SINGH
5     gupta
6     KUMAR
7    Sharma
8     singh
9     VERMA
Name: Name, dtype: object

In [ ]:
13
Extract the username from Email.
Example:
rahul.sharma@gmail.com
        ↓
rahul.sharma

In [149]:
df["Email"].str.split("@").str.get(0)

0    rahul.sharma
1     PRIYA.SINGH
2      amit.kumar
3      neha.verma
4     rohit.singh
5     SNEHA.GUPTA
6     vikas.kumar
7    pooja.sharma
8     karan.singh
9    anjali.verma
Name: Email, dtype: object

In [ ]:
Q14
Extract the complete email domain.
Example:
rahul.sharma@gmail.com
        ↓
gmail.com

In [151]:
df["Email"].str.split("@").str.get(1)

0      gmail.com
1      YAHOO.COM
2      gmail.com
3    outlook.com
4      gmail.com
5      YAHOO.COM
6      gmail.com
7    outlook.com
8      gmail.com
9      yahoo.com
Name: Email, dtype: object

In [ ]:
15
Extract only the email provider:
gmail
yahoo
outlook

In [157]:
df["Email"].str.extract(
    r"@([^.]+)"
)
 #r"@([^.]+)"

         0
0    gmail
1    YAHOO
2    gmail
3  outlook
4    gmail
5    YAHOO
6    gmail
7  outlook
8    gmail
9    yahoo

In [ ]:
Q16
Remove - from Phone.
Q17
Remove spaces from Phone.
Q18
Create Clean_Phone containing only digits.
Hint:
r"\D"


Q19
Find the length of every cleaned phone number.
Q20
Identify phone numbers that are not exactly 10 digits after cleaning.

In [ ]:
Q16
Remove - from Phone.

In [161]:
df["Phone"].str.replace("-","")

0        9876543210
1        9876543211
2      987 654 3212
3     +919876543213
4        9876543214
5        9876543215
6      987 654 3216
7    +91 9876543217
8        9876543218
9        9876543219
Name: Phone, dtype: object

In [ ]:
17
Remove spaces from Phone.

In [163]:
df["Phone"].str.replace(" ","")

0        9876543210
1      987-654-3211
2        9876543212
3    +91-9876543213
4        9876543214
5      987-654-3215
6        9876543216
7     +919876543217
8        9876543218
9      987-654-3219
Name: Phone, dtype: object

In [ ]:
Q18
Create Clean_Phone containing only digits.
Hint:
r"\D"

In [171]:
df["Clean_Phone"]=df["Phone"].str.replace(r"\D","",regex=True)
df

,Name,Email,Department,City,Phone,Clean_Phone
0,Rahul Sharma,rahul.sharma@gmail.com,it,Delhi,9876543210,9876543210
1,PRIYA SINGH,PRIYA.SINGH@YAHOO.COM,HR,mumbai,987-654-3211,9876543211
2,amit kumar,amit.kumar@gmail.com,IT,DELHI,987 654 3212,9876543212
3,Neha Verma,neha.verma@outlook.com,finance,Pune,+91-9876543213,919876543213
4,ROHIT SINGH,rohit.singh@gmail.com,HR,Mumbai,9876543214,9876543214
5,sneha gupta,SNEHA.GUPTA@YAHOO.COM,it,delhi,987-654-3215,9876543215
6,VIKAS KUMAR,vikas.kumar@gmail.com,Finance,PUNE,987 654 3216,9876543216
7,Pooja Sharma,pooja.sharma@outlook.com,HR,Mumbai,+91 9876543217,919876543217
8,karan singh,karan.singh@gmail.com,IT,DELHI,9876543218,9876543218
9,ANJALI VERMA,anjali.verma@yahoo.com,finance,pune,987-654-3219,9876543219

In [ ]:
Q19
Find the length of every cleaned phone number.

In [173]:
df["Clean_Phone"].str.len()

0    10
1    10
2    10
3    12
4    10
5    10
6    10
7    12
8    10
9    10
Name: Clean_Phone, dtype: int64

In [ ]:
Q20
Identify phone numbers that are not exactly 10 digits after cleaning.

In [175]:
df["Clean_Phone"].str.match(
    r"^[0-9]{10}&"
)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Clean_Phone, dtype: bool

In [ ]:
Q21
Create a completely cleaned version of:
Name
Department
City

Rules:
Name       → strip + title
Department → strip + upper
City       → strip + title

In [177]:
df["Name"].str.strip().str.title()

0    Rahul Sharma
1     Priya Singh
2      Amit Kumar
3      Neha Verma
4     Rohit Singh
5     Sneha Gupta
6     Vikas Kumar
7    Pooja Sharma
8     Karan Singh
9    Anjali Verma
Name: Name, dtype: object

In [179]:
df["Department"].str.strip().str.upper()

0         IT
1         HR
2         IT
3    FINANCE
4         HR
5         IT
6    FINANCE
7         HR
8         IT
9    FINANCE
Name: Department, dtype: object

In [181]:
df["City"].str.strip().str.title()

0     Delhi
1    Mumbai
2     Delhi
3      Pune
4    Mumbai
5     Delhi
6      Pune
7    Mumbai
8     Delhi
9      Pune
Name: City, dtype: object

In [ ]:
Q22
Create:
First_Name
Last_Name
Email_User
Email_Domain

from:
Name
Email

In [187]:
df["First_Name"]=df["Name"].str.split().str.get(0)
df

,Name,Email,Department,City,Phone,Clean_Phone,First_Name
0,Rahul Sharma,rahul.sharma@gmail.com,it,Delhi,9876543210,9876543210,Rahul
1,PRIYA SINGH,PRIYA.SINGH@YAHOO.COM,HR,mumbai,987-654-3211,9876543211,PRIYA
2,amit kumar,amit.kumar@gmail.com,IT,DELHI,987 654 3212,9876543212,amit
3,Neha Verma,neha.verma@outlook.com,finance,Pune,+91-9876543213,919876543213,Neha
4,ROHIT SINGH,rohit.singh@gmail.com,HR,Mumbai,9876543214,9876543214,ROHIT
5,sneha gupta,SNEHA.GUPTA@YAHOO.COM,it,delhi,987-654-3215,9876543215,sneha
6,VIKAS KUMAR,vikas.kumar@gmail.com,Finance,PUNE,987 654 3216,9876543216,VIKAS
7,Pooja Sharma,pooja.sharma@outlook.com,HR,Mumbai,+91 9876543217,919876543217,Pooja
8,karan singh,karan.singh@gmail.com,IT,DELHI,9876543218,9876543218,karan
9,ANJALI VERMA,anjali.verma@yahoo.com,finance,pune,987-654-3219,9876543219,ANJALI

In [193]:
df["Last_Name"]=df["Name"].str.split().str.get(1)
df

,Name,Email,Department,City,Phone,Clean_Phone,First_Name,Last_Name
0,Rahul Sharma,rahul.sharma@gmail.com,it,Delhi,9876543210,9876543210,Rahul,Sharma
1,PRIYA SINGH,PRIYA.SINGH@YAHOO.COM,HR,mumbai,987-654-3211,9876543211,PRIYA,SINGH
2,amit kumar,amit.kumar@gmail.com,IT,DELHI,987 654 3212,9876543212,amit,kumar
3,Neha Verma,neha.verma@outlook.com,finance,Pune,+91-9876543213,919876543213,Neha,Verma
4,ROHIT SINGH,rohit.singh@gmail.com,HR,Mumbai,9876543214,9876543214,ROHIT,SINGH
5,sneha gupta,SNEHA.GUPTA@YAHOO.COM,it,delhi,987-654-3215,9876543215,sneha,gupta
6,VIKAS KUMAR,vikas.kumar@gmail.com,Finance,PUNE,987 654 3216,9876543216,VIKAS,KUMAR
7,Pooja Sharma,pooja.sharma@outlook.com,HR,Mumbai,+91 9876543217,919876543217,Pooja,Sharma
8,karan singh,karan.singh@gmail.com,IT,DELHI,9876543218,9876543218,karan,singh
9,ANJALI VERMA,anjali.verma@yahoo.com,finance,pune,987-654-3219,9876543219,ANJALI,VERMA

In [195]:
df["Email_User"]=df["Email"].str.split("@").str.get(0)
df

,Name,Email,Department,City,Phone,Clean_Phone,First_Name,Last_Name,Email_User
0,Rahul Sharma,rahul.sharma@gmail.com,it,Delhi,9876543210,9876543210,Rahul,Sharma,rahul.sharma
1,PRIYA SINGH,PRIYA.SINGH@YAHOO.COM,HR,mumbai,987-654-3211,9876543211,PRIYA,SINGH,PRIYA.SINGH
2,amit kumar,amit.kumar@gmail.com,IT,DELHI,987 654 3212,9876543212,amit,kumar,amit.kumar
3,Neha Verma,neha.verma@outlook.com,finance,Pune,+91-9876543213,919876543213,Neha,Verma,neha.verma
4,ROHIT SINGH,rohit.singh@gmail.com,HR,Mumbai,9876543214,9876543214,ROHIT,SINGH,rohit.singh
5,sneha gupta,SNEHA.GUPTA@YAHOO.COM,it,delhi,987-654-3215,9876543215,sneha,gupta,SNEHA.GUPTA
6,VIKAS KUMAR,vikas.kumar@gmail.com,Finance,PUNE,987 654 3216,9876543216,VIKAS,KUMAR,vikas.kumar
7,Pooja Sharma,pooja.sharma@outlook.com,HR,Mumbai,+91 9876543217,919876543217,Pooja,Sharma,pooja.sharma
8,karan singh,karan.singh@gmail.com,IT,DELHI,9876543218,9876543218,karan,singh,karan.singh
9,ANJALI VERMA,anjali.verma@yahoo.com,finance,pune,987-654-3219,9876543219,ANJALI,VERMA,anjali.verma

In [205]:
df["Email_Domain"]=df["Email"].str.split("@").str.get(1)

df

,Name,Email,Department,City,Phone,Clean_Phone,First_Name,Last_Name,Email_User,Email_Domain
0,Rahul Sharma,rahul.sharma@gmail.com,it,Delhi,9876543210,9876543210,Rahul,Sharma,rahul.sharma,gmail.com
1,PRIYA SINGH,PRIYA.SINGH@YAHOO.COM,HR,mumbai,987-654-3211,9876543211,PRIYA,SINGH,PRIYA.SINGH,YAHOO.COM
2,amit kumar,amit.kumar@gmail.com,IT,DELHI,987 654 3212,9876543212,amit,kumar,amit.kumar,gmail.com
3,Neha Verma,neha.verma@outlook.com,finance,Pune,+91-9876543213,919876543213,Neha,Verma,neha.verma,outlook.com
4,ROHIT SINGH,rohit.singh@gmail.com,HR,Mumbai,9876543214,9876543214,ROHIT,SINGH,rohit.singh,gmail.com
5,sneha gupta,SNEHA.GUPTA@YAHOO.COM,it,delhi,987-654-3215,9876543215,sneha,gupta,SNEHA.GUPTA,YAHOO.COM
6,VIKAS KUMAR,vikas.kumar@gmail.com,Finance,PUNE,987 654 3216,9876543216,VIKAS,KUMAR,vikas.kumar,gmail.com
7,Pooja Sharma,pooja.sharma@outlook.com,HR,Mumbai,+91 9876543217,919876543217,Pooja,Sharma,pooja.sharma,outlook.com
8,karan singh,karan.singh@gmail.com,IT,DELHI,9876543218,9876543218,karan,singh,karan.singh,gmail.com
9,ANJALI VERMA,anjali.verma@yahoo.com,finance,pune,987-654-3219,9876543219,ANJALI,VERMA,anjali.verma,yahoo.com

In [ ]:
Q23 💼
Find all employees whose:
Department = IT

after cleaning the Department column.
Remember that raw values include:
"it"
"IT "
" it"

In [207]:
df["Department"]=="IT"

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8     True
9    False
Name: Department, dtype: bool

In [ ]:
Q24 💼
Create a Clean_Phone column that contains only digits.
Then create:
Phone_Valid

Rules:
10 digits → "Valid"
Anything else → "Invalid"

In [217]:
df["Clean_Phone"]=df["Phone"].str.replace(r"\D","",regex=True)
import numpy as np
np.where(
    df["Clean_Phone"] ==10,"Valid","Invalid"
)

array(['Invalid', 'Invalid', 'Invalid', 'Invalid', 'Invalid', 'Invalid',
       'Invalid', 'Invalid', 'Invalid', 'Invalid'], dtype='<U7')