In [ ]:
Missing Data & Advanced Data Cleaning

In [ ]:
NaN
None
""
"Unknown"
"N/A"
"-"
"not available"
wrong data types
duplicate records
inconsistent categories
invalid dates

In [1]:
import pandas as pd
import numpy as np

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    
    "Name": [
        "Rahul", "Priya", "Amit", "Neha", "Rohit",
        "Sneha", "Vikas", "Pooja", "Karan", "Anjali"
    ],
    
    "Age": [
        25, 32, np.nan, 41, 24,
        35, np.nan, 45, 31, 27
    ],
    
    "Department": [
        "IT", "HR", "IT", "Finance", "HR",
        "IT", "Finance", "HR", "IT", "Finance"
    ],
    
    "Salary": [
        50000, 65000, np.nan, 80000, 40000,
        70000, 60000, np.nan, 75000, 48000
    ],
    
    "Experience": [
        2, 6, 3, np.nan, 1,
        7, 5, 8, np.nan, 2
    ],
    
    "City": [
        "Delhi", "Mumbai", "Delhi", None, "Mumbai",
        "Delhi", "Pune", "Mumbai", "Delhi", None
    ]
}

df = pd.DataFrame(data)
df

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit   NaN         IT      NaN         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN    None
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas   NaN    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR      NaN         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0    None

In [ ]:
isna()-This returns True where a value is missing. detect missing values

In [3]:
df.isna()

   Employee_ID   Name    Age  Department  Salary  Experience   City
0        False  False  False       False   False       False  False
1        False  False  False       False   False       False  False
2        False  False   True       False    True       False  False
3        False  False  False       False   False        True   True
4        False  False  False       False   False       False  False
5        False  False  False       False   False       False  False
6        False  False   True       False   False       False  False
7        False  False  False       False    True       False  False
8        False  False  False       False   False        True  False
9        False  False  False       False   False       False   True

In [5]:
df.isnull()

   Employee_ID   Name    Age  Department  Salary  Experience   City
0        False  False  False       False   False       False  False
1        False  False  False       False   False       False  False
2        False  False   True       False    True       False  False
3        False  False  False       False   False        True   True
4        False  False  False       False   False       False  False
5        False  False  False       False   False       False  False
6        False  False   True       False   False       False  False
7        False  False  False       False    True       False  False
8        False  False  False       False   False        True  False
9        False  False  False       False   False       False   True

In [7]:
df.isnull().sum()

Employee_ID    0
Name           0
Age            2
Department     0
Salary         2
Experience     2
City           2
dtype: int64

In [9]:
df.isnull().sum().sum() #total missing values

8

In [13]:
df[df.isnull().any(axis=1)] #find rows containing missing values

   Employee_ID    Name   Age Department   Salary  Experience    City
2          103    Amit   NaN         IT      NaN         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN    None
6          107   Vikas   NaN    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR      NaN         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0    None

In [15]:
df[df.notna().all(axis=1)]#find rows containing no missing values

   Employee_ID   Name   Age Department   Salary  Experience    City
0          101  Rahul  25.0         IT  50000.0         2.0   Delhi
1          102  Priya  32.0         HR  65000.0         6.0  Mumbai
4          105  Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106  Sneha  35.0         IT  70000.0         7.0   Delhi

In [17]:
#filling missing values with mean
df["Age"]=df["Age"].fillna(
    df["Age"].mean()
)
df

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit  32.5         IT      NaN         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN    None
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR      NaN         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0    None

In [21]:
df["Age"]=df["Age"].fillna(
    df["Age"].median()
)
df

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit  32.5         IT      NaN         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN    None
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR      NaN         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0    None

In [29]:
df["City"]=df["City"].fillna(
    df["City"].mode()[0]
)
df

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit  32.5         IT      NaN         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN   Delhi
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR      NaN         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0   Delhi

In [35]:
df["City"]=df["City"].fillna("Unknown")
df

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit  32.5         IT      NaN         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN   Delhi
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR      NaN         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0   Delhi

In [37]:
df.dropna(subset=["Salary"]) #drop rows when speciifc column is missing

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
3          104    Neha  41.0    Finance  80000.0         NaN   Delhi
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0   Delhi

In [39]:
df.dropna()#remove rows containing missing values

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
9          110  Anjali  27.0    Finance  48000.0         2.0   Delhi

In [41]:
df["Salary"].ffill() #It uses the previous available value.

0    50000.0
1    65000.0
2    65000.0
3    80000.0
4    40000.0
5    70000.0
6    60000.0
7    60000.0
8    75000.0
9    48000.0
Name: Salary, dtype: float64

In [45]:
df["Salary"].bfill() #It uses the next available value.

0    50000.0
1    65000.0
2    80000.0
3    80000.0
4    40000.0
5    70000.0
6    60000.0
7    75000.0
8    75000.0
9    48000.0
Name: Salary, dtype: float64

In [53]:
#replace
df["City"]=df["City"].replace(
    ["NA","N/A","-",""],np.nan
)
df

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit  32.5         IT      NaN         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN   Delhi
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR      NaN         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0   Delhi

In [57]:
#pd.to_numeric()
df["Salary"]=pd.to_numeric(
    df["Salary"],
    errors="coerce"
)
df

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit  32.5         IT      NaN         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN   Delhi
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR      NaN         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0   Delhi

In [ ]:
pd.to_datetime(
    df["joining_Date"],
    errors="coerce"
)

In [61]:
df.duplicated() #detect dupicate rows

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [63]:
df.duplicated().sum()

0

In [65]:
df.drop_duplicates() #remove duplicate rows

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit  32.5         IT      NaN         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN   Delhi
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR      NaN         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0   Delhi

In [69]:
df.duplicated(
    subset=["Employee_ID"]
)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [79]:
df.drop_duplicates(
    subset=["Employee_ID"],
    keep="first"
)

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit  32.5         IT      NaN         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN   Delhi
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR      NaN         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0   Delhi

In [ ]:
#group by wise missing values

In [85]:
df["Salary"]=df.groupby("Department")["Salary"].fillna(
    df["Salary"].transform(
        lambda x:x.fillna(x.mean())
    )
)
df

C:\Users\santo\AppData\Local\Temp\ipykernel_4576\657403331.py:1: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  df["Salary"]=df.groupby("Department")["Salary"].fillna(

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit  32.5         IT  61000.0         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN   Delhi
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR  61000.0         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0   Delhi

In [ ]:
Q1
Count missing values in every column.
Q2
Find the total number of missing cells in the entire DataFrame.
Q3
Find rows containing at least one missing value.
Q4
Find rows that contain no missing values.
Q5
Find which columns contain missing values.

In [87]:
import pandas as pd
import numpy as np

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    
    "Name": [
        "Rahul", "Priya", "Amit", "Neha", "Rohit",
        "Sneha", "Vikas", "Pooja", "Karan", "Anjali"
    ],
    
    "Age": [
        25, 32, np.nan, 41, 24,
        35, np.nan, 45, 31, 27
    ],
    
    "Department": [
        "IT", "HR", "IT", "Finance", "HR",
        "IT", "Finance", "HR", "IT", "Finance"
    ],
    
    "Salary": [
        50000, 65000, np.nan, 80000, 40000,
        70000, 60000, np.nan, 75000, 48000
    ],
    
    "Experience": [
        2, 6, 3, np.nan, 1,
        7, 5, 8, np.nan, 2
    ],
    
    "City": [
        "Delhi", "Mumbai", "Delhi", None, "Mumbai",
        "Delhi", "Pune", "Mumbai", "Delhi", None
    ]
}

df = pd.DataFrame(data)
df

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit   NaN         IT      NaN         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN    None
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas   NaN    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR      NaN         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0    None

In [ ]:
Q1
Count missing values in every column.

In [89]:
df.isna().sum()

Employee_ID    0
Name           0
Age            2
Department     0
Salary         2
Experience     2
City           2
dtype: int64

In [ ]:
Q2
Find the total number of missing cells in the entire DataFrame.

In [93]:
df.isna().sum().sum()

8

In [ ]:
Q3
Find rows containing at least one missing value.

In [97]:
df[df.isna().any(axis=1)]

   Employee_ID    Name   Age Department   Salary  Experience    City
2          103    Amit   NaN         IT      NaN         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN    None
6          107   Vikas   NaN    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR      NaN         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0    None

In [ ]:
Q4
Find rows that contain no missing values.

In [99]:
df[df.notna().all(axis=1)]

   Employee_ID   Name   Age Department   Salary  Experience    City
0          101  Rahul  25.0         IT  50000.0         2.0   Delhi
1          102  Priya  32.0         HR  65000.0         6.0  Mumbai
4          105  Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106  Sneha  35.0         IT  70000.0         7.0   Delhi

In [ ]:
Q5
Find which columns contain missing values.

In [103]:
df.columns[df.isna().any()]

Index(['Age', 'Salary', 'Experience', 'City'], dtype='object')

In [ ]:
Q6
Fill missing Age with the mean Age.
Q7
Fill missing Salary with the median Salary.
Q8
Fill missing Experience with 0.
Think carefully:
Is 0 actually meaningful here?

Q9
Fill missing City with "Unknown".
Q10
Fill missing City with the most frequent city using mode().

In [ ]:
Q6
Fill missing Age with the mean Age.

In [109]:
df["Age"]=df["Age"].fillna(
    df["Age"].mean()
)
df

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit  32.5         IT      NaN         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN    None
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR      NaN         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0    None

In [ ]:
Q7
Fill missing Salary with the median Salary.

In [115]:
df["Salary"]=df["Salary"].fillna(
    df["Salary"].mean()
)
df

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit  32.5         IT  61000.0         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN    None
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR  61000.0         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0    None

In [ ]:
8
Fill missing Experience with 0.
Think carefully:
Is 0 actually meaningful here?

In [117]:
df["Experience"].fillna(0)

0    2.0
1    6.0
2    3.0
3    0.0
4    1.0
5    7.0
6    5.0
7    8.0
8    0.0
9    2.0
Name: Experience, dtype: float64

In [ ]:
Q9
Fill missing City with "Unknown".

In [119]:
df["City"].fillna("Unknown")

0      Delhi
1     Mumbai
2      Delhi
3    Unknown
4     Mumbai
5      Delhi
6       Pune
7     Mumbai
8      Delhi
9    Unknown
Name: City, dtype: object

In [ ]:
Q10
Fill missing City with the most frequent city using mode().

In [121]:
df["City"].fillna(
    df["City"].mode()
)

0     Delhi
1    Mumbai
2     Delhi
3       NaN
4    Mumbai
5     Delhi
6      Pune
7    Mumbai
8     Delhi
9       NaN
Name: City, dtype: object

In [ ]:
Q11
Remove rows where Salary is missing.
Q12
Remove rows where either Age or Experience is missing.
Q13
Remove rows where all values are missing.
Hint:
how="all"


Q14
Remove columns containing missing values.
Q15 💡
Explain why:
df.dropna()


can be dangerous on a large real-world dataset.

In [ ]:
Q11
Remove rows where Salary is missing.

In [123]:
df.dropna(subset=["Salary"])

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit  32.5         IT  61000.0         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN    None
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR  61000.0         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0    None

In [ ]:
12
Remove rows where either Age or Experience is missing.

In [125]:
df.dropna(subset=["Age","Experience"])

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit  32.5         IT  61000.0         3.0   Delhi
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR  61000.0         8.0  Mumbai
9          110  Anjali  27.0    Finance  48000.0         2.0    None

In [ ]:
Q13
Remove rows where all values are missing.
Hint:
how="all"

In [141]:
df.dropna(axis=0)

   Employee_ID   Name   Age Department   Salary  Experience    City
0          101  Rahul  25.0         IT  50000.0         2.0   Delhi
1          102  Priya  32.0         HR  65000.0         6.0  Mumbai
2          103   Amit  32.5         IT  61000.0         3.0   Delhi
4          105  Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106  Sneha  35.0         IT  70000.0         7.0   Delhi
6          107  Vikas  32.5    Finance  60000.0         5.0    Pune
7          108  Pooja  45.0         HR  61000.0         8.0  Mumbai

In [ ]:
14
Remove columns containing missing values.

In [135]:
df.dropna(axis=1)

   Employee_ID    Name   Age Department   Salary
0          101   Rahul  25.0         IT  50000.0
1          102   Priya  32.0         HR  65000.0
2          103    Amit  32.5         IT  61000.0
3          104    Neha  41.0    Finance  80000.0
4          105   Rohit  24.0         HR  40000.0
5          106   Sneha  35.0         IT  70000.0
6          107   Vikas  32.5    Finance  60000.0
7          108   Pooja  45.0         HR  61000.0
8          109   Karan  31.0         IT  75000.0
9          110  Anjali  27.0    Finance  48000.0

In [ ]:
Q16
Use ffill() on the Salary column.
Q17
Use bfill() on the Salary column.
Q18
Suppose a City column contains:
"Delhi"
"N/A"
"Unknown"
"-"
None
"Mumbai"

Convert:
"N/A"
"Unknown"
"-"

to NaN.
Q19
Convert a Salary column containing strings such as:
"50000"
"65000"
"Unknown"
"80000"

to numeric using:
pd.to_numeric()


and errors="coerce".
Q20
Convert a Joining_Date column containing invalid dates to datetime using:
pd.to_datetime()


with:
errors="coerce"

In [ ]:
Q16
Use ffill() on the Salary column.

In [147]:
df.ffill()

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit  32.5         IT  61000.0         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         3.0   Delhi
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR  61000.0         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         8.0   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0   Delhi

In [ ]:
Q17
Use bfill() on the Salary column.

In [149]:
df["Salary"].ffill()

0    50000.0
1    65000.0
2    61000.0
3    80000.0
4    40000.0
5    70000.0
6    60000.0
7    61000.0
8    75000.0
9    48000.0
Name: Salary, dtype: float64

In [ ]:
Q18
Suppose a City column contains:
"Delhi"
"N/A"
"Unknown"
"-"
None
"Mumbai"

Convert:
"N/A"
"Unknown"
"-"

to NaN.

In [153]:
df["City"].replace(
    ["N/A","Unknown","-"],np.nan)

0     Delhi
1    Mumbai
2     Delhi
3      None
4    Mumbai
5     Delhi
6      Pune
7    Mumbai
8     Delhi
9      None
Name: City, dtype: object

In [ ]:
Q19
Convert a Salary column containing strings such as:
"50000"
"65000"
"Unknown"
"80000"

to numeric using:
pd.to_numeric()


and errors="coerce".

In [159]:
df["Salary"]=pd.to_numeric(
    df["Salary"],
    errors="coerce"
)
df

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit  32.5         IT  61000.0         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN    None
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR  61000.0         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0    None

In [ ]:
Q20
Convert a Joining_Date column containing invalid dates to datetime using:
pd.to_datetime()


with:
errors="coerce"

In [ ]:
pd.to_datetime(
    df["Joining_Date"],
    errors="coerce"
)

In [ ]:
Q21
Find duplicate rows.
Q22
Count duplicate rows.
Q23
Find duplicate Employee IDs.
Q24
Remove duplicate Employee IDs while keeping the last occurrence.

In [ ]:
Q21
Find duplicate rows.

In [164]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
Q22
Count duplicate rows.

In [168]:
df.duplicated().sum()

0

In [ ]:
Q23
Find duplicate Employee IDs.

In [174]:
df.duplicated(subset=["Employee_ID"])

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
Q24
Remove duplicate Employee IDs while keeping the last occurrence.

In [176]:
df.drop_duplicates(subset=["Employee_ID"],
                  keep="last")

   Employee_ID    Name   Age Department   Salary  Experience    City
0          101   Rahul  25.0         IT  50000.0         2.0   Delhi
1          102   Priya  32.0         HR  65000.0         6.0  Mumbai
2          103    Amit  32.5         IT  61000.0         3.0   Delhi
3          104    Neha  41.0    Finance  80000.0         NaN    None
4          105   Rohit  24.0         HR  40000.0         1.0  Mumbai
5          106   Sneha  35.0         IT  70000.0         7.0   Delhi
6          107   Vikas  32.5    Finance  60000.0         5.0    Pune
7          108   Pooja  45.0         HR  61000.0         8.0  Mumbai
8          109   Karan  31.0         IT  75000.0         NaN   Delhi
9          110  Anjali  27.0    Finance  48000.0         2.0    None