In [3]:
import pandas as pd

data = {
    "Order_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Month": [
        "Jan", "Jan", "Feb", "Feb", "Mar",
        "Mar", "Apr", "Apr", "May", "May"
    ],
    "Department": [
        "IT", "HR", "IT", "Finance", "HR",
        "IT", "Finance", "HR", "IT", "Finance"
    ],
    "Employee": [
        "Rahul", "Priya", "Amit", "Neha", "Rohit",
        "Sneha", "Vikas", "Pooja", "Karan", "Anjali"
    ],
    "Sales": [
        5000, 7000, 4500, 9000, 6000,
        8000, 5500, 7500, 6500, 8500
    ],
    "Profit": [
        1000, 1500, 800, 2000, 1200,
        1800, 1100, 1600, 1300, 1900
    ]
}

df = pd.DataFrame(data)

In [4]:
df

   Order_ID Month Department Employee  Sales  Profit
0       101   Jan         IT    Rahul   5000    1000
1       102   Jan         HR    Priya   7000    1500
2       103   Feb         IT     Amit   4500     800
3       104   Feb    Finance     Neha   9000    2000
4       105   Mar         HR    Rohit   6000    1200
5       106   Mar         IT    Sneha   8000    1800
6       107   Apr    Finance    Vikas   5500    1100
7       108   Apr         HR    Pooja   7500    1600
8       109   May         IT    Karan   6500    1300
9       110   May    Finance   Anjali   8500    1900

In [7]:
df.pivot_table(
    values="Sales",
    index="Department",
    aggfunc="sum"
)

            Sales
Department
Finance     23000
HR          20500
IT          24000

In [9]:
#pivot by month
df.pivot_table(
    values="Sales",
    index="Month",
    aggfunc="sum"
)

       Sales
Month
Apr    13000
Feb    13500
Jan    12000
Mar    14000
May    15000

In [11]:
#Multiple Aggregations
df.pivot_table(
    values="Sales",
    index="Department",
    aggfunc=["sum","mean","max"]
)

              sum         mean   max
            Sales        Sales Sales
Department
Finance     23000  7666.666667  9000
HR          20500  6833.333333  7500
IT          24000  6000.000000  8000

In [15]:
#multiple values
df.pivot_table(
    values=["Sales","Profit"],
    index="Department",
    aggfunc="sum"
)

            Profit  Sales
Department
Finance       5000  23000
HR            4300  20500
IT            4900  24000

In [19]:
#columns-powerful part -Sales by Department and Month
df.pivot_table(
    values="Sales",
    index="Department",
    columns="Month",
    aggfunc="sum"
)

Month          Apr     Feb     Jan     Mar     May
Department
Finance     5500.0  9000.0     NaN     NaN  8500.0
HR          7500.0     NaN  7000.0  6000.0     NaN
IT             NaN  4500.0  5000.0  8000.0  6500.0

In [21]:
#fill_value-Some Department × Month combinations don't exist.They may appear as:NaN
df.pivot_table(
    values="Sales",
    index="Department",
    columns="Month",
    aggfunc="sum",
    fill_value=0
)

Month        Apr   Feb   Jan   Mar   May
Department
Finance     5500  9000     0     0  8500
HR          7500     0  7000  6000     0
IT             0  4500  5000  8000  6500

In [23]:
#margins=True -Want totals?-margin=grand totals#
df.pivot_table(
    values="Sales",
    index="Department",
    columns="Month",
    aggfunc="sum",
    fill_value=0,
    margins=True
)

Month         Apr    Feb    Jan    Mar    May    All
Department
Finance      5500   9000      0      0   8500  23000
HR           7500      0   7000   6000      0  20500
IT              0   4500   5000   8000   6500  24000
All         13000  13500  12000  14000  15000  67500

In [25]:
#Multiple Index Columns
df.pivot_table(
    values="Sales",
    index=["Department","Employee"],
    aggfunc="sum"
)

                     Sales
Department Employee
Finance    Anjali     8500
           Neha       9000
           Vikas      5500
HR         Pooja      7500
           Priya      7000
           Rohit      6000
IT         Amit       4500
           Karan      6500
           Rahul      5000
           Sneha      8000

In [27]:
#Multiple Dimensions
df.pivot_table(
    values="Sales",
    index="Department",
    columns="Month",
    aggfunc="sum",
    fill_value=0,
    margins=True
)

Month         Apr    Feb    Jan    Mar    May    All
Department
Finance      5500   9000      0      0   8500  23000
HR           7500      0   7000   6000      0  20500
IT              0   4500   5000   8000   6500  24000
All         13000  13500  12000  14000  15000  67500

In [31]:
#melt() 🔥Now let's go in the opposite direction.
wide_df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit"],
    "Jan": [5000, 7000, 4500],
    "Feb": [6000, 8000, 5500],
    "Mar": [7000, 9000, 6500]
})
wide_df

    Name   Jan   Feb   Mar
0  Rahul  5000  6000  7000
1  Priya  7000  8000  9000
2   Amit  4500  5500  6500

In [39]:
long_df = wide_df.melt(
    id_vars="Name",
    var_name="Month",
    value_name="Sales"
)
long_df

    Name Month  Sales
0  Rahul   Jan   5000
1  Priya   Jan   7000
2   Amit   Jan   4500
3  Rahul   Feb   6000
4  Priya   Feb   8000
5   Amit   Feb   5500
6  Rahul   Mar   7000
7  Priya   Mar   9000
8   Amit   Mar   6500

In [41]:
#crosstab()-crosstab() is particularly useful for frequency/count tables.
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female"]
})
df

  Department  Gender
0         IT    Male
1         HR  Female
2         IT    Male
3    Finance  Female
4         HR    Male
5         IT  Female

In [45]:
#Number of employees by Department and Gender.
pd.crosstab(
    df["Department"],
    df["Gender"]
)

Gender      Female  Male
Department
Finance          1     0
HR               1     1
IT               1     2

In [49]:
#crosstab() with percentages
#Within each department, what percentage belongs to each gender?
pd.crosstab(
    df["Department"],
    df["Gender"],
    normalize="index"
)

Gender        Female      Male
Department
Finance     1.000000  0.000000
HR          0.500000  0.500000
IT          0.333333  0.666667

In [ ]:
Q1

Find total Sales by Department using pivot_table().

Q2

Find average Sales by Department.

Q3

Find maximum Sales by Department.

Q4

Find total Profit by Department.

Q5

Find total Sales by Month.

In [53]:
import pandas as pd

data = {
    "Order_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Month": [
        "Jan", "Jan", "Feb", "Feb", "Mar",
        "Mar", "Apr", "Apr", "May", "May"
    ],
    "Department": [
        "IT", "HR", "IT", "Finance", "HR",
        "IT", "Finance", "HR", "IT", "Finance"
    ],
    "Employee": [
        "Rahul", "Priya", "Amit", "Neha", "Rohit",
        "Sneha", "Vikas", "Pooja", "Karan", "Anjali"
    ],
    "Sales": [
        5000, 7000, 4500, 9000, 6000,
        8000, 5500, 7500, 6500, 8500
    ],
    "Profit": [
        1000, 1500, 800, 2000, 1200,
        1800, 1100, 1600, 1300, 1900
    ]
}

df = pd.DataFrame(data)
df

   Order_ID Month Department Employee  Sales  Profit
0       101   Jan         IT    Rahul   5000    1000
1       102   Jan         HR    Priya   7000    1500
2       103   Feb         IT     Amit   4500     800
3       104   Feb    Finance     Neha   9000    2000
4       105   Mar         HR    Rohit   6000    1200
5       106   Mar         IT    Sneha   8000    1800
6       107   Apr    Finance    Vikas   5500    1100
7       108   Apr         HR    Pooja   7500    1600
8       109   May         IT    Karan   6500    1300
9       110   May    Finance   Anjali   8500    1900

In [55]:
##Q1Find total Sales by Department using pivot_table().
df.pivot_table(
    values="Sales",
    index="Department",
    aggfunc="sum"
)

            Sales
Department
Finance     23000
HR          20500
IT          24000

In [57]:
#Q2Find average Sales by Department.
df.pivot_table(
    values="Sales",
    index="Department",
    aggfunc="mean"
)

                  Sales
Department
Finance     7666.666667
HR          6833.333333
IT          6000.000000

In [59]:
#Q3Find maximum Sales by Department.
df.pivot_table(
    values="Sales",
    index="Department",
    aggfunc="max"
)

            Sales
Department
Finance      9000
HR           7500
IT           8000

In [61]:
#4Find total Profit by Department.
df.pivot_table(
    values="Profit",
    index="Department",
    aggfunc="sum"
)

            Profit
Department
Finance       5000
HR            4300
IT            4900

In [73]:
#Q5Find total Sales by Month.
df.pivot_table(
    values="Sales",
    index="Month",
    aggfunc="sum"
)

       Sales
Month
Apr    13000
Feb    13500
Jan    12000
Mar    14000
May    15000

In [ ]:
Q6

Find total Sales by:

Department + Month

Use:

index="Department"
columns="Month"
Q7

Find average Sales by Department and Month.

Q8

Find total Profit by Department and Month.

Q9

Replace missing combinations with 0.

Q10

Add grand totals using:#

margins=True

In [77]:
'''Q6

Find total Sales by:

Department + Month

Use:

index="Department"
columns="Month"'''

df.pivot_table(
    values="Sales",
    index="Department",
    columns="Month",
    aggfunc="sum"
)

Month          Apr     Feb     Jan     Mar     May
Department
Finance     5500.0  9000.0     NaN     NaN  8500.0
HR          7500.0     NaN  7000.0  6000.0     NaN
IT             NaN  4500.0  5000.0  8000.0  6500.0

In [79]:
#Q7Find average Sales by Department and Month.
df.pivot_table(
    values="Sales",
    index="Department",
    columns="Month",
    aggfunc="mean"
)

Month          Apr     Feb     Jan     Mar     May
Department
Finance     5500.0  9000.0     NaN     NaN  8500.0
HR          7500.0     NaN  7000.0  6000.0     NaN
IT             NaN  4500.0  5000.0  8000.0  6500.0

In [81]:
#Q8Find total Profit by Department and Month.
df.pivot_table(
    values="Sales",
    index="Department",
    columns="Month",
    aggfunc="sum"
)

Month          Apr     Feb     Jan     Mar     May
Department
Finance     5500.0  9000.0     NaN     NaN  8500.0
HR          7500.0     NaN  7000.0  6000.0     NaN
IT             NaN  4500.0  5000.0  8000.0  6500.0

In [83]:
#Q9Replace missing combinations with 0.
df.pivot_table(
    values="Sales",
    index="Department",
    columns="Month",
    aggfunc="sum",
    fill_value=0
)

Month        Apr   Feb   Jan   Mar   May
Department
Finance     5500  9000     0     0  8500
HR          7500     0  7000  6000     0
IT             0  4500  5000  8000  6500

In [85]:
'''Q10

Add grand totals using:

margins=True'''
df.pivot_table(
    values="Sales",
    index="Department",
    columns="Month",
    aggfunc="sum",
    fill_value=0,
    margins=True
)

Month         Apr    Feb    Jan    Mar    May    All
Department
Finance      5500   9000      0      0   8500  23000
HR           7500      0   7000   6000      0  20500
IT              0   4500   5000   8000   6500  24000
All         13000  13500  12000  14000  15000  67500

In [ ]:
11

For each Department calculate:

Total Sales
Average Sales
Maximum Sales
Minimum Sales

Use one pivot_table().

Q12

For each Department calculate:

Total Sales
Total Profit
Q13

For each Department calculate:

Average Sales
Average Profit
Q14

Create a report:

Department × Month

showing both Sales and Profit.

Q15

Find total Sales by:

Department + Employee

In [87]:
'''11

For each Department calculate:

Total Sales
Average Sales
Maximum Sales
Minimum Sales

Use one pivot_table().
'''
df.pivot_table(
    values="Sales",
    index="Department",
    aggfunc=["sum","mean","max","min"]
)

              sum         mean   max   min
            Sales        Sales Sales Sales
Department
Finance     23000  7666.666667  9000  5500
HR          20500  6833.333333  7500  6000
IT          24000  6000.000000  8000  4500

In [100]:
'''Q12

For each Department calculate:

Total Sales
Total Profit'''
df.pivot_table(
    values=["Sales","Profit"],
    index="Department",
    aggfunc=["sum"]
)

              sum
           Profit  Sales
Department
Finance      5000  23000
HR           4300  20500
IT           4900  24000

In [102]:
'''Q13

For each Department calculate:

Average Sales
Average Profit'''
df.pivot_table(
    values=["Sales","Profit"],
    index="Department",
    aggfunc="mean"
)

                 Profit        Sales
Department
Finance     1666.666667  7666.666667
HR          1433.333333  6833.333333
IT          1225.000000  6000.000000

In [104]:
'''Q14

Create a report:

Department × Month

showing both Sales and Profit.'''
df.pivot_table(
    values=["Sales","Profit"],
    index="Department",
    columns="Month",
    aggfunc="sum",
    fill_value=0
)

           Profit                         Sales
Month         Apr   Feb   Jan   Mar   May   Apr   Feb   Jan   Mar   May
Department
Finance      1100  2000     0     0  1900  5500  9000     0     0  8500
HR           1600     0  1500  1200     0  7500     0  7000  6000     0
IT              0   800  1000  1800  1300     0  4500  5000  8000  6500

In [106]:
'''Q15

Find total Sales by:

Department + Employee'''
df.pivot_table(
    values="Sales",
    index=["Department","Employee"],
    aggfunc="sum"
)

                     Sales
Department Employee
Finance    Anjali     8500
           Neha       9000
           Vikas      5500
HR         Pooja      7500
           Priya      7000
           Rohit      6000
IT         Amit       4500
           Karan      6500
           Rahul      5000
           Sneha      8000

In [108]:
wide_df = pd.DataFrame({
    "Employee": ["Rahul", "Priya", "Amit", "Neha"],
    "Jan": [5000, 7000, 4500, 6000],
    "Feb": [5500, 7500, 5000, 6500],
    "Mar": [6000, 8000, 5500, 7000]
})

In [110]:
wide_df

  Employee   Jan   Feb   Mar
0    Rahul  5000  5500  6000
1    Priya  7000  7500  8000
2     Amit  4500  5000  5500
3     Neha  6000  6500  7000

In [ ]:
Q16

Convert wide_df from wide → long using melt().

Q17

Rename the resulting columns to:

Employee
Month
Sales
Q18

Convert your long-format data back to wide format.

Use pivot().

Q19

Calculate total sales for each employee from the long-format data.

Q20

Calculate average monthly sales for each employee.

In [120]:
'''Q16

Convert wide_df from wide → long using melt().
'''
long_df=wide_df.melt(
    id_vars="Employee",
    var_name="Month",
    value_name="Sales"
    
)
long_df

   Employee Month  Sales
0     Rahul   Jan   5000
1     Priya   Jan   7000
2      Amit   Jan   4500
3      Neha   Jan   6000
4     Rahul   Feb   5500
5     Priya   Feb   7500
6      Amit   Feb   5000
7      Neha   Feb   6500
8     Rahul   Mar   6000
9     Priya   Mar   8000
10     Amit   Mar   5500
11     Neha   Mar   7000

In [132]:
'''Q17

Rename the resulting columns to:

Employee
Month
Sales'''
wide_df.melt(
    id_vars="Employee",
    var_name="Month",
    value_name="Sale"
)

   Employee Month  Sale
0     Rahul   Jan  5000
1     Priya   Jan  7000
2      Amit   Jan  4500
3      Neha   Jan  6000
4     Rahul   Feb  5500
5     Priya   Feb  7500
6      Amit   Feb  5000
7      Neha   Feb  6500
8     Rahul   Mar  6000
9     Priya   Mar  8000
10     Amit   Mar  5500
11     Neha   Mar  7000

In [142]:
'''Q18

Convert your long-format data back to wide format.

Use pivot().'''

long_df.pivot(
    values="Sales",
    index="Employee",
    columns="Month"
)

Month      Feb   Jan   Mar
Employee
Amit      5000  4500  5500
Neha      6500  6000  7000
Priya     7500  7000  8000
Rahul     5500  5000  6000

In [146]:
'''Q19

Calculate total sales for each employee from the long-format data.'''

long_df.pivot_table(
    values="Sales",
    index="Employee",
    aggfunc="sum"
)

          Sales
Employee
Amit      15000
Neha      19500
Priya     22500
Rahul     16500

In [150]:
'''Q20

Calculate average monthly sales for each employee.'''
df.pivot_table(
    values="Sales",
    index="Employee",
    aggfunc="mean"
)

           Sales
Employee
Amit      4500.0
Anjali    8500.0
Karan     6500.0
Neha      9000.0
Pooja     7500.0
Priya     7000.0
Rahul     5000.0
Rohit     6000.0
Sneha     8000.0
Vikas     5500.0

In [152]:
employee_df = pd.DataFrame({
    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "IT", "Finance", "HR"
    ],
    "Gender": [
        "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female"
    ],
    "Experience_Level": [
        "Junior", "Senior", "Senior", "Senior",
        "Junior", "Senior", "Mid", "Mid"
    ]
})
employee_df

  Department  Gender Experience_Level
0         IT    Male           Junior
1         HR  Female           Senior
2         IT    Male           Senior
3    Finance  Female           Senior
4         HR    Male           Junior
5         IT  Female           Senior
6    Finance    Male              Mid
7         HR  Female              Mid

In [ ]:
Q21

Create a Department × Gender count table.

Q22

Create a Department × Experience_Level count table.

Q23

Calculate the percentage distribution of Gender within each Department.

Hint:

normalize="index"

In [156]:
'''Q21

Create a Department × Gender count table.'''
pd.crosstab(
    employee_df["Department"],
    employee_df["Gender"]
)

Gender      Female  Male
Department
Finance          1     1
HR               2     1
IT               1     2

In [164]:
'''Q22

Create a Department × Experience_Level count table.
'''
pd.crosstab(
     employee_df["Department"],
     employee_df["Experience_Level"]
    
)

Experience_Level  Junior  Mid  Senior
Department
Finance                0    1       1
HR                     1    1       1
IT                     1    0       2

In [168]:
'''Q23

Calculate the percentage distribution of Gender within each Department.

Hint:

normalize="index"'''

pd.crosstab(
    employee_df["Department"],
    employee_df["Gender"],
    normalize="index"
    
)

Gender        Female      Male
Department
Finance     0.500000  0.500000
HR          0.666667  0.333333
IT          0.333333  0.666667

In [188]:
'''Q24 — Sales Report

Using the original sales dataset, create a pivot report:

Department × Month

containing:

Total Sales
Average Sales
Total Profit

Also:

replace missing combinations with 0
add grand totals'''

df.pivot_table(
    values=["Sales"],
    index="Department",
    columns="Month",
    aggfunc="sum",
    fill_value=0,
    margins=True
)

            Sales
Month         Apr    Feb    Jan    Mar    May    All
Department
Finance      5500   9000      0      0   8500  23000
HR           7500      0   7000   6000      0  20500
IT              0   4500   5000   8000   6500  24000
All         13000  13500  12000  14000  15000  67500

In [190]:
df.pivot_table(
    values=["Sales"],
    index="Department",
    columns="Month",
    aggfunc="mean",
    fill_value=0,
    margins=True
)

             Sales
Month          Apr     Feb     Jan     Mar     May          All
Department
Finance     5500.0  9000.0     0.0     0.0  8500.0  7666.666667
HR          7500.0     0.0  7000.0  6000.0     0.0  6833.333333
IT             0.0  4500.0  5000.0  8000.0  6500.0  6000.000000
All         6500.0  6750.0  6000.0  7000.0  7500.0  6750.000000

In [192]:
df.pivot_table(
    values=["Profit"],
    index="Department",
    columns="Month",
    aggfunc="sum",
    fill_value=0,
    margins=True
)

           Profit
Month         Apr   Feb   Jan   Mar   May    All
Department
Finance      1100  2000     0     0  1900   5000
HR           1600     0  1500  1200     0   4300
IT              0   800  1000  1800  1300   4900
All          2700  2800  2500  3000  3200  14200

In [ ]:
'''Q25 — Business Dashboard Problem 💼

Create a summary table containing:

Department
Total Sales
Total Profit
Average Sales
Maximum Sales

Then answer programmatically:

Which department has the highest total sales?
Which department has the highest total profit?
Which department has the highest average sales?'''

In [206]:
total_sales=df.pivot_table(
    values=["Sales","Profit"],
    index="Department",
    aggfunc={
        "Sales":["sum","mean","max"],
        "Profit":["sum"]
    }
)
total_sales

           Profit Sales
              sum   max         mean    sum
Department
Finance      5000  9000  7666.666667  23000
HR           4300  7500  6833.333333  20500
IT           4900  8000  6000.000000  24000

In [221]:
summary=df.groupby("Department").agg(
    **{
        "Total_Sales":("Sales","sum"),
        "Total_Profit":("Profit","sum"),
        "Average_Sales":("Sales","mean"),
        "Maximum_Sales":("Sales","max")
    }
)
summary

            Total_Sales  Total_Profit  Average_Sales  Maximum_Sales
Department
Finance           23000          5000    7666.666667           9000
HR                20500          4300    6833.333333           7500
IT                24000          4900    6000.000000           8000

In [223]:
summary["Total_Sales"].idxmax()

'IT'

In [225]:
summary["Total_Profit"].idxmax()

'Finance'

In [ ]:
summary["Average"]