In [3]:
import pandas as pd
data={
    "Name":["Rahul","Priya","Amit","Neha","Rohit","Sneha"],
    "Age":[25,28,30,26,24,29],
    "Department":["IT","HR","IT","Finance","HR","IT"],
    "Salary":[50000,45000,65000,55000,40000,70000],
    "Experience":[2,5,7,4,1,6]
}
df=pd.DataFrame(data)
df

    Name  Age Department  Salary  Experience
0  Rahul   25         IT   50000           2
1  Priya   28         HR   45000           5
2   Amit   30         IT   65000           7
3   Neha   26    Finance   55000           4
4  Rohit   24         HR   40000           1
5  Sneha   29         IT   70000           6

In [5]:
#Show the first rows
df.head(3)

    Name  Age Department  Salary  Experience
0  Rahul   25         IT   50000           2
1  Priya   28         HR   45000           5
2   Amit   30         IT   65000           7

In [9]:
#show the last two rows
df.tail(2)

    Name  Age Department  Salary  Experience
4  Rohit   24         HR   40000           1
5  Sneha   29         IT   70000           6

In [11]:
#shape 6rows 5columns
df.shape

(6, 5)

In [15]:
df.shape[0] #rows
df.shape[1]  #columns

5

In [17]:
#columns-want to know the columns names
df.columns

Index(['Name', 'Age', 'Department', 'Salary', 'Experience'], dtype='object')

In [19]:
df.columns.tolist()

['Name', 'Age', 'Department', 'Salary', 'Experience']

In [21]:
#dtypes
df.dtypes

Name          object
Age            int64
Department    object
Salary         int64
Experience     int64
dtype: object

In [23]:
#info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         6 non-null      int64
 2   Department  6 non-null      object
 3   Salary      6 non-null      int64
 4   Experience  6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes

In [25]:
#selecting one column
df["Name"]

0    Rahul
1    Priya
2     Amit
3     Neha
4    Rohit
5    Sneha
Name: Name, dtype: object

In [27]:
df["Salary"]

0    50000
1    45000
2    65000
3    55000
4    40000
5    70000
Name: Salary, dtype: int64

In [29]:
#selecting multiple columns
df[["Name","Salary"]]

    Name  Salary
0  Rahul   50000
1  Priya   45000
2   Amit   65000
3   Neha   55000
4  Rohit   40000
5  Sneha   70000

In [31]:
#selecting rows using loc
df.loc[0]

Name          Rahul
Age              25
Department       IT
Salary        50000
Experience        2
Name: 0, dtype: object

In [33]:
df.loc[2]

Name           Amit
Age              30
Department       IT
Salary        65000
Experience        7
Name: 2, dtype: object

In [35]:
#multiple rows
df.loc[0:3]

    Name  Age Department  Salary  Experience
0  Rahul   25         IT   50000           2
1  Priya   28         HR   45000           5
2   Amit   30         IT   65000           7
3   Neha   26    Finance   55000           4

In [37]:
#iloc
df.iloc[0]

Name          Rahul
Age              25
Department       IT
Salary        50000
Experience        2
Name: 0, dtype: object

In [39]:
df.iloc[2]

Name           Amit
Age              30
Department       IT
Salary        65000
Experience        7
Name: 2, dtype: object

In [41]:
df.iloc[0:3]

    Name  Age Department  Salary  Experience
0  Rahul   25         IT   50000           2
1  Priya   28         HR   45000           5
2   Amit   30         IT   65000           7

In [43]:
df.loc[0,["Name","Salary"]]

Name      Rahul
Salary    50000
Name: 0, dtype: object

In [45]:
df.loc[0:2,["Name","Salary"]]

    Name  Salary
0  Rahul   50000
1  Priya   45000
2   Amit   65000

In [49]:
df.iloc[0:3,[0,3]]

    Name  Salary
0  Rahul   50000
1  Priya   45000
2   Amit   65000

In [53]:
#Filtering

df[df["Salary"] > 50000]

    Name  Age Department  Salary  Experience
2   Amit   30         IT   65000           7
3   Neha   26    Finance   55000           4
5  Sneha   29         IT   70000           6

In [61]:
#Q find IT employess whose salary is greater than 60000
df[(df["Department"]=="IT") & (df["Salary"] > 60000)]

    Name  Age Department  Salary  Experience
2   Amit   30         IT   65000           7
5  Sneha   29         IT   70000           6

In [63]:
#Q find employess who work in IT OR HR
df[(df["Department"]=="IT") | (df["Department"]=="HR")]

    Name  Age Department  Salary  Experience
0  Rahul   25         IT   50000           2
1  Priya   28         HR   45000           5
2   Amit   30         IT   65000           7
4  Rohit   24         HR   40000           1
5  Sneha   29         IT   70000           6

In [67]:
# find employees who are NOT in it
df[df["Department"]!="IT"]

    Name  Age Department  Salary  Experience
1  Priya   28         HR   45000           5
3   Neha   26    Finance   55000           4
4  Rohit   24         HR   40000           1

In [69]:
#Q1. Display the last 3 rows.
df.tail(3)

    Name  Age Department  Salary  Experience
3   Neha   26    Finance   55000           4
4  Rohit   24         HR   40000           1
5  Sneha   29         IT   70000           6

In [71]:
#Q2. Find the number of rows.
df.head()

    Name  Age Department  Salary  Experience
0  Rahul   25         IT   50000           2
1  Priya   28         HR   45000           5
2   Amit   30         IT   65000           7
3   Neha   26    Finance   55000           4
4  Rohit   24         HR   40000           1

In [73]:
#Q3. Find the number of columns.
df.columns

Index(['Name', 'Age', 'Department', 'Salary', 'Experience'], dtype='object')

In [81]:
#Q4. Display all column name.
df["Name"]

0    Rahul
1    Priya
2     Amit
3     Neha
4    Rohit
5    Sneha
Name: Name, dtype: object

In [85]:
#Q5. Display only Name, Department, and Salary.
df[["Name","Department","Salary"]]

    Name Department  Salary
0  Rahul         IT   50000
1  Priya         HR   45000
2   Amit         IT   65000
3   Neha    Finance   55000
4  Rohit         HR   40000
5  Sneha         IT   70000

In [91]:
#Q6. Display the first 3 rows using loc.
df.loc[0:3]

    Name  Age Department  Salary  Experience
0  Rahul   25         IT   50000           2
1  Priya   28         HR   45000           5
2   Amit   30         IT   65000           7
3   Neha   26    Finance   55000           4

In [93]:
#Q7. Display the first 3 rows using iloc.
df.iloc[0:3]

    Name  Age Department  Salary  Experience
0  Rahul   25         IT   50000           2
1  Priya   28         HR   45000           5
2   Amit   30         IT   65000           7

In [149]:
#Q8 Select the rows of Amit
df[df["Name"]=="Amit"]

   Name  Age Department  Salary  Experience
2  Amit   30         IT   65000           7

In [113]:
#Q9. Select Name and Salary for Rahul, Priya, and Amit.
df.loc[0:2,["Name","Salary"]]

    Name  Salary
0  Rahul   50000
1  Priya   45000
2   Amit   65000

In [115]:
#Q10. Find employees whose salary is greater than 50000.
df[df["Salary"] >50000]

    Name  Age Department  Salary  Experience
2   Amit   30         IT   65000           7
3   Neha   26    Finance   55000           4
5  Sneha   29         IT   70000           6

In [119]:
#Q11. Find employees whose age is less than 27
df[df["Age"]<27]

    Name  Age Department  Salary  Experience
0  Rahul   25         IT   50000           2
3   Neha   26    Finance   55000           4
4  Rohit   24         HR   40000           1

In [121]:
#Q12. Find employees who work in HR.
df[df["Department"]=="HR"]

    Name  Age Department  Salary  Experience
1  Priya   28         HR   45000           5
4  Rohit   24         HR   40000           1

In [123]:
#Q13. Find employees who work in IT AND have salary greater than 60000.
df[(df["Department"]=="IT") & (df["Salary"] >60000)]

    Name  Age Department  Salary  Experience
2   Amit   30         IT   65000           7
5  Sneha   29         IT   70000           6

In [127]:
#Q14. Find employees who work in HR OR have salary greater than 65000.
df[(df["Department"]=="HR") | (df["Salary"] > 65000)]

    Name  Age Department  Salary  Experience
1  Priya   28         HR   45000           5
4  Rohit   24         HR   40000           1
5  Sneha   29         IT   70000           6

In [145]:
#Q15. Find employees whose experience is greater than 3 AND salary is greater than 50000, and display only their Name, Salary, and Experience.

df.loc[(df["Experience"] > 3) & (df["Salary"] > 50000) ,["Name","Salary","Experience"]]

    Name  Salary  Experience
2   Amit   65000           7
3   Neha   55000           4
5  Sneha   70000           6

In [153]:
#Q16. Find the row of Sneha using a condition, not the index.
df[df["Name"]=="Sneha"]

    Name  Age Department  Salary  Experience
5  Sneha   29         IT   70000           6