In [1]:
import pandas as pd

data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit", "Sneha"],
    "Age": [25, 28, 30, 26, 24, 29],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [50000, 45000, 65000, 55000, 40000, 70000],
    "Experience": [2, 5, 7, 4, 1, 6]
}

df = pd.DataFrame(data)
df

    Name  Age Department  Salary  Experience
0  Rahul   25         IT   50000           2
1  Priya   28         HR   45000           5
2   Amit   30         IT   65000           7
3   Neha   26    Finance   55000           4
4  Rohit   24         HR   40000           1
5  Sneha   29         IT   70000           6

In [3]:
#Suppose we want to sort employees by salary.
df.sort_values("Salary")

    Name  Age Department  Salary  Experience
4  Rohit   24         HR   40000           1
1  Priya   28         HR   45000           5
0  Rahul   25         IT   50000           2
3   Neha   26    Finance   55000           4
2   Amit   30         IT   65000           7
5  Sneha   29         IT   70000           6

In [5]:
#Suppose we want to sort employees by salary.-highest salary
df.sort_values("Salary",ascending=False)

    Name  Age Department  Salary  Experience
5  Sneha   29         IT   70000           6
2   Amit   30         IT   65000           7
3   Neha   26    Finance   55000           4
0  Rahul   25         IT   50000           2
1  Priya   28         HR   45000           5
4  Rohit   24         HR   40000           1

In [11]:
#Sort and select Top N -Find the highest-paid employee.

df.sort_values("Salary",ascending=False).head(1)

    Name  Age Department  Salary  Experience
5  Sneha   29         IT   70000           6

In [13]:
#Top 3 employees
df.sort_values("Salary",ascending=False).head(3)

    Name  Age Department  Salary  Experience
5  Sneha   29         IT   70000           6
2   Amit   30         IT   65000           7
3   Neha   26    Finance   55000           4

In [17]:
#nlargest() - 
df.nlargest(3,"Salary")

    Name  Age Department  Salary  Experience
5  Sneha   29         IT   70000           6
2   Amit   30         IT   65000           7
3   Neha   26    Finance   55000           4

In [19]:
#nsmallest()
df.nsmallest(3,"Salary")

    Name  Age Department  Salary  Experience
4  Rohit   24         HR   40000           1
1  Priya   28         HR   45000           5
0  Rahul   25         IT   50000           2

In [23]:
#Sorting by Multiple Columns
'''Suppose we want to sort:

Department alphabetically
Salary from highest to lowest within each department'''

df.sort_values(by=["Department","Salary"],ascending=[True,False])

    Name  Age Department  Salary  Experience
3   Neha   26    Finance   55000           4
1  Priya   28         HR   45000           5
4  Rohit   24         HR   40000           1
5  Sneha   29         IT   70000           6
2   Amit   30         IT   65000           7
0  Rahul   25         IT   50000           2

In [35]:
#rank()
df["Salary_Rank"]=df["Salary"].rank(ascending=False)
df

    Name  Age Department  Salary  Experience  Salary_Rank
0  Rahul   25         IT   50000           2          4.0
1  Priya   28         HR   45000           5          5.0
2   Amit   30         IT   65000           7          2.0
3   Neha   26    Finance   55000           4          3.0
4  Rohit   24         HR   40000           1          6.0
5  Sneha   29         IT   70000           6          1.0

In [37]:
df["Salary"].rank(method="dense",ascending=False)

0    4.0
1    5.0
2    2.0
3    3.0
4    6.0
5    1.0
Name: Salary, dtype: float64

In [47]:
#filtering and sorting
#Find IT employees and sort them by salary from highest to lowest.
df[df["Department"]=="IT"].sort_values(
    "Salary",ascending=False)

    Name  Age Department  Salary  Experience  Salary_Rank
5  Sneha   29         IT   70000           6          1.0
2   Amit   30         IT   65000           7          2.0
0  Rahul   25         IT   50000           2          4.0

In [51]:
#Filter + Sort + Top N -Find the top 2 highest-paid IT employees.
df[df["Department"]=="IT"].sort_values("Salary",ascending=False).head(2)

    Name  Age Department  Salary  Experience  Salary_Rank
5  Sneha   29         IT   70000           6          1.0
2   Amit   30         IT   65000           7          2.0

In [55]:
#Find the top 3 HR employees by salary.
df[df["Department"]=="HR"].nlargest(3,"Salary")

    Name  Age Department  Salary  Experience  Salary_Rank
1  Priya   28         HR   45000           5          5.0
4  Rohit   24         HR   40000           1          6.0

In [57]:
import pandas as pd

data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit", "Sneha"],
    "Age": [25, 28, 30, 26, 24, 29],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [50000, 45000, 65000, 55000, 40000, 70000],
    "Experience": [2, 5, 7, 4, 1, 6]
}

d = pd.DataFrame(data)
d

    Name  Age Department  Salary  Experience
0  Rahul   25         IT   50000           2
1  Priya   28         HR   45000           5
2   Amit   30         IT   65000           7
3   Neha   26    Finance   55000           4
4  Rohit   24         HR   40000           1
5  Sneha   29         IT   70000           6

In [59]:
#Q1. Sort the DataFrame by Salary from lowest to highest.
d.sort_values("Salary",ascending=True)

    Name  Age Department  Salary  Experience
4  Rohit   24         HR   40000           1
1  Priya   28         HR   45000           5
0  Rahul   25         IT   50000           2
3   Neha   26    Finance   55000           4
2   Amit   30         IT   65000           7
5  Sneha   29         IT   70000           6

In [61]:
#Q2. Sort the DataFrame by Salary from highest to lowest.
d.sort_values("Salary",ascending=False)

    Name  Age Department  Salary  Experience
5  Sneha   29         IT   70000           6
2   Amit   30         IT   65000           7
3   Neha   26    Finance   55000           4
0  Rahul   25         IT   50000           2
1  Priya   28         HR   45000           5
4  Rohit   24         HR   40000           1

In [63]:
#Q3. Find the employee with the highest salary using sort_values().
d.sort_values("Salary",ascending=False)

    Name  Age Department  Salary  Experience
5  Sneha   29         IT   70000           6
2   Amit   30         IT   65000           7
3   Neha   26    Finance   55000           4
0  Rahul   25         IT   50000           2
1  Priya   28         HR   45000           5
4  Rohit   24         HR   40000           1

In [65]:
#Q4. Find the employee with the lowest salary.
d.sort_values("Salary",ascending=True)

    Name  Age Department  Salary  Experience
4  Rohit   24         HR   40000           1
1  Priya   28         HR   45000           5
0  Rahul   25         IT   50000           2
3   Neha   26    Finance   55000           4
2   Amit   30         IT   65000           7
5  Sneha   29         IT   70000           6

In [67]:
#Q5. Find the top 3 highest-paid employees using nlargest().
d.nlargest(3,"Salary")

    Name  Age Department  Salary  Experience
5  Sneha   29         IT   70000           6
2   Amit   30         IT   65000           7
3   Neha   26    Finance   55000           4

In [69]:
#Q6. Find the bottom 2 employees by salary using nsmallest().
d.nsmallest(2,"Salary")

    Name  Age Department  Salary  Experience
4  Rohit   24         HR   40000           1
1  Priya   28         HR   45000           5

In [71]:
#Q7. Sort employees by Age from youngest to oldest.
d.sort_values("Age",ascending=True)

    Name  Age Department  Salary  Experience
4  Rohit   24         HR   40000           1
0  Rahul   25         IT   50000           2
3   Neha   26    Finance   55000           4
1  Priya   28         HR   45000           5
5  Sneha   29         IT   70000           6
2   Amit   30         IT   65000           7

In [73]:
#Q8.Sort employees by Experience from highest to lowest.
d.sort_values("Experience",ascending=False)

    Name  Age Department  Salary  Experience
2   Amit   30         IT   65000           7
5  Sneha   29         IT   70000           6
1  Priya   28         HR   45000           5
3   Neha   26    Finance   55000           4
0  Rahul   25         IT   50000           2
4  Rohit   24         HR   40000           1

In [75]:
#Q9. Sort by Department ascending and Salary descending.
d.sort_values(by=["Department","Salary"],ascending=[True,False])

    Name  Age Department  Salary  Experience
3   Neha   26    Finance   55000           4
1  Priya   28         HR   45000           5
4  Rohit   24         HR   40000           1
5  Sneha   29         IT   70000           6
2   Amit   30         IT   65000           7
0  Rahul   25         IT   50000           2

In [77]:
#Q10. Find the top 2 highest-paid employees in the IT department.
d[d["Department"]=="IT"].nlargest(2,"Salary")

    Name  Age Department  Salary  Experience
5  Sneha   29         IT   70000           6
2   Amit   30         IT   65000           7

In [79]:
#Q11. Find the bottom 2 lowest-paid employees in the HR department.
d[d["Department"]=="HR"].nsmallest(2,"Salary")

    Name  Age Department  Salary  Experience
4  Rohit   24         HR   40000           1
1  Priya   28         HR   45000           5

In [81]:
#Q12. Find employees whose salary is greater than 45000, then sort them by salary descending.
d[d["Salary"]>45000].sort_values("Salary",ascending=False)

    Name  Age Department  Salary  Experience
5  Sneha   29         IT   70000           6
2   Amit   30         IT   65000           7
3   Neha   26    Finance   55000           4
0  Rahul   25         IT   50000           2

In [94]:
#Q13. Create a new column called Salary_Rank where the highest salary gets rank 1.
d["Salary_Rank"]=d["Salary"].rank(ascending=False)
d

    Name  Age Department  Salary  Experience  Salary_Rank
0  Rahul   25         IT   50000           2          4.0
1  Priya   28         HR   45000           5          5.0
2   Amit   30         IT   65000           7          2.0
3   Neha   26    Finance   55000           4          3.0
4  Rohit   24         HR   40000           1          6.0
5  Sneha   29         IT   70000           6          1.0

In [96]:
#Q14. Find the top 3 employees based on Experience.
d.nlargest(3,"Experience")

    Name  Age Department  Salary  Experience  Salary_Rank
2   Amit   30         IT   65000           7          2.0
5  Sneha   29         IT   70000           6          1.0
1  Priya   28         HR   45000           5          5.0

In [100]:
#Q15. Find the highest-paid employee in the IT department.
d[d["Department"]=="IT"].sort_values("Salary",ascending=False)

    Name  Age Department  Salary  Experience  Salary_Rank
5  Sneha   29         IT   70000           6          1.0
2   Amit   30         IT   65000           7          2.0
0  Rahul   25         IT   50000           2          4.0

In [102]:
#Q16. Find the second-highest salary.
d.nlargest(2,"Salary")

    Name  Age Department  Salary  Experience  Salary_Rank
5  Sneha   29         IT   70000           6          1.0
2   Amit   30         IT   65000           7          2.0

In [104]:
#Q17. Find the second-highest-paid employee.
d.nlargest(2,"Salary")

    Name  Age Department  Salary  Experience  Salary_Rank
5  Sneha   29         IT   70000           6          1.0
2   Amit   30         IT   65000           7          2.0

In [106]:
#Q18. Find the top 2 employees by salary among employees with more than 3 years of experience.
d[d["Experience"] >3].nlargest(2,"Salary")

    Name  Age Department  Salary  Experience  Salary_Rank
5  Sneha   29         IT   70000           6          1.0
2   Amit   30         IT   65000           7          2.0

In [108]:
#Q19. Sort employees by Department ascending, and within each department sort Experience from highest to lowest.
d.sort_values(by=["Department","Experience"],ascending=[True,False])

    Name  Age Department  Salary  Experience  Salary_Rank
3   Neha   26    Finance   55000           4          3.0
1  Priya   28         HR   45000           5          5.0
4  Rohit   24         HR   40000           1          6.0
2   Amit   30         IT   65000           7          2.0
5  Sneha   29         IT   70000           6          1.0
0  Rahul   25         IT   50000           2          4.0

In [112]:
#Q20. 🔥 Interview Problem:Find the top 2 highest-paid employees from each department.
d.groupby("Department").apply(lambda x:x.nlargest(2,"Salary"))

C:\Users\santo\AppData\Local\Temp\ipykernel_20544\3003595235.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  d.groupby("Department").apply(lambda x:x.nlargest(2,"Salary"))

               Name  Age Department  Salary  Experience  Salary_Rank
Department
Finance    3   Neha   26    Finance   55000           4          3.0
HR         1  Priya   28         HR   45000           5          5.0
           4  Rohit   24         HR   40000           1          6.0
IT         5  Sneha   29         IT   70000           6          1.0
           2   Amit   30         IT   65000           7          2.0

In [114]:
#Q21 🔥Find the top 2 most experienced employees from each department.
d.groupby("Department").apply(lambda x:x.nlargest(2,"Experience"))

C:\Users\santo\AppData\Local\Temp\ipykernel_20544\2843883104.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  d.groupby("Department").apply(lambda x:x.nlargest(2,"Experience"))

               Name  Age Department  Salary  Experience  Salary_Rank
Department
Finance    3   Neha   26    Finance   55000           4          3.0
HR         1  Priya   28         HR   45000           5          5.0
           4  Rohit   24         HR   40000           1          6.0
IT         2   Amit   30         IT   65000           7          2.0
           5  Sneha   29         IT   70000           6          1.0