In [1]:
import pandas as pd

data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit"],
    "Age": [25, None, 30, 26, None],
    "Salary": [50000, 45000, None, 55000, 40000],
    "Department": ["IT", "HR", "IT", "Finance", None]
}

df = pd.DataFrame(data)
df

    Name   Age   Salary Department
0  Rahul  25.0  50000.0         IT
1  Priya   NaN  45000.0         HR
2   Amit  30.0      NaN         IT
3   Neha  26.0  55000.0    Finance
4  Rohit   NaN  40000.0       None

In [3]:
#isna()
df.isna()

    Name    Age  Salary  Department
0  False  False   False       False
1  False   True   False       False
2  False  False    True       False
3  False  False   False       False
4  False   True   False        True

In [7]:
#count missing values-isna().sum()
df.isna().sum()

Name          0
Age           2
Salary        1
Department    1
dtype: int64

In [11]:
df.isnull().sum()

Name          0
Age           2
Salary        1
Department    1
dtype: int64

In [13]:
#find rows conatining missing values
df[df["Age"].isna()]

    Name  Age   Salary Department
1  Priya  NaN  45000.0         HR
4  Rohit  NaN  40000.0       None

In [15]:
#notna()->mot mising
df[df["Age"].notna()]

    Name   Age   Salary Department
0  Rahul  25.0  50000.0         IT
2   Amit  30.0      NaN         IT
3   Neha  26.0  55000.0    Finance

In [17]:
#dropna()
df.dropna()

    Name   Age   Salary Department
0  Rahul  25.0  50000.0         IT
3   Neha  26.0  55000.0    Finance

In [19]:
df

    Name   Age   Salary Department
0  Rahul  25.0  50000.0         IT
1  Priya   NaN  45000.0         HR
2   Amit  30.0      NaN         IT
3   Neha  26.0  55000.0    Finance
4  Rohit   NaN  40000.0       None

In [21]:
df.dropna(subset=["Salary"])

    Name   Age   Salary Department
0  Rahul  25.0  50000.0         IT
1  Priya   NaN  45000.0         HR
3   Neha  26.0  55000.0    Finance
4  Rohit   NaN  40000.0       None

In [37]:
#fillna()
df["Age"].fillna(0)

0    25.0
1     0.0
2    30.0
3    26.0
4     0.0
Name: Age, dtype: float64

In [51]:
#fillna() with mean
df["Age"].fillna(df["Age"].mean())

0    25.0
1    27.0
2    30.0
3    26.0
4    27.0
Name: Age, dtype: float64

In [53]:
#fillna()w ith median
df["Age"].fillna(df["Age"].median())

0    25.0
1    26.0
2    30.0
3    26.0
4    26.0
Name: Age, dtype: float64

In [55]:
#categorical 
df["Department"].fillna("Unknown")

0         IT
1         HR
2         IT
3    Finance
4    Unknown
Name: Department, dtype: object

In [59]:
data = {
    "Name": ["Rahul", "Priya", "Rahul", "Amit"],
    "Salary": [50000, 45000, 50000, 65000]
}

df = pd.DataFrame(data)
df

    Name  Salary
0  Rahul   50000
1  Priya   45000
2  Rahul   50000
3   Amit   65000

In [61]:
df.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [63]:
df.drop_duplicates()

    Name  Salary
0  Rahul   50000
1  Priya   45000
3   Amit   65000

In [65]:
df.duplicated(subset=["Name"])

0    False
1    False
2     True
3    False
dtype: bool

In [69]:
df.drop_duplicates(subset=["Name"])

    Name  Salary
0  Rahul   50000
1  Priya   45000
3   Amit   65000

In [73]:
import pandas as pd

data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit"],
    "Age": [25, None, 30, 26, None],
    "Salary": [50000, 45000, None, 55000, 40000],
    "Department": ["it", "hr", "IT", "Finance", None]
}

df = pd.DataFrame(data)
df

    Name   Age   Salary Department
0  Rahul  25.0  50000.0         it
1  Priya   NaN  45000.0         hr
2   Amit  30.0      NaN         IT
3   Neha  26.0  55000.0    Finance
4  Rohit   NaN  40000.0       None

In [79]:
df["Department"]=df["Department"].replace({
    "it":"IT",
    "hr":"HR"
})
df

    Name   Age   Salary Department
0  Rahul  25.0  50000.0         IT
1  Priya   NaN  45000.0         HR
2   Amit  30.0      NaN         IT
3   Neha  26.0  55000.0    Finance
4  Rohit   NaN  40000.0       None

In [81]:
data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit", "Rahul"],
    "Age": [25, None, 30, 26, None, 25],
    "Department": ["IT", "HR", "IT", "Finance", None, "IT"],
    "Salary": [50000, 45000, None, 55000, 40000, 50000]
}

df = pd.DataFrame(data)
df

    Name   Age Department   Salary
0  Rahul  25.0         IT  50000.0
1  Priya   NaN         HR  45000.0
2   Amit  30.0         IT      NaN
3   Neha  26.0    Finance  55000.0
4  Rohit   NaN       None  40000.0
5  Rahul  25.0         IT  50000.0

In [83]:
#Q1. Find the number of missing values in each column.
df.isna().sum()

Name          0
Age           2
Department    1
Salary        1
dtype: int64

In [85]:
#Q2. Find all rows where Age is missing.
df["Age"].isna()

0    False
1     True
2    False
3    False
4     True
5    False
Name: Age, dtype: bool

In [87]:
#Q3. Find all rows where Salary is missing.
df["Salary"].isna()

0    False
1    False
2     True
3    False
4    False
5    False
Name: Salary, dtype: bool

In [89]:
#Q4. Find rows where Department is not missing.
df["Department"].notna()

0     True
1     True
2     True
3     True
4    False
5     True
Name: Department, dtype: bool

In [93]:
#Q5. Count the total number of duplicate rows.
df.duplicated().sum()

1

In [97]:
#Q6. Remove all rows containing any missing value.
df.dropna()

    Name   Age Department   Salary
0  Rahul  25.0         IT  50000.0
3   Neha  26.0    Finance  55000.0
5  Rahul  25.0         IT  50000.0

In [99]:
#Q7. Remove rows where only Salary is missing.
df.dropna(subset=["Salary"])

    Name   Age Department   Salary
0  Rahul  25.0         IT  50000.0
1  Priya   NaN         HR  45000.0
3   Neha  26.0    Finance  55000.0
4  Rohit   NaN       None  40000.0
5  Rahul  25.0         IT  50000.0

In [107]:
#Q8. Fill missing Age values with the mean age.
df.fillna(df["Age"].mean())

    Name   Age Department   Salary
0  Rahul  25.0         IT  50000.0
1  Priya  26.5         HR  45000.0
2   Amit  30.0         IT     26.5
3   Neha  26.0    Finance  55000.0
4  Rohit  26.5       26.5  40000.0
5  Rahul  25.0         IT  50000.0

In [109]:
#Q9. Fill missing Department values with "Unknown".
df.fillna("Unknown")

    Name      Age Department   Salary
0  Rahul     25.0         IT  50000.0
1  Priya  Unknown         HR  45000.0
2   Amit     30.0         IT  Unknown
3   Neha     26.0    Finance  55000.0
4  Rohit  Unknown    Unknown  40000.0
5  Rahul     25.0         IT  50000.0

In [113]:
#Q10. Remove exact duplicate rows
df.drop_duplicates()

    Name   Age Department   Salary
0  Rahul  25.0         IT  50000.0
1  Priya   NaN         HR  45000.0
2   Amit  30.0         IT      NaN
3   Neha  26.0    Finance  55000.0
4  Rohit   NaN       None  40000.0

In [115]:
#Q11. Find duplicate records based only on Name
df.duplicated(subset=["Name"])

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [117]:
#Q12. Remove duplicate records based on Name.
df.drop_duplicates(subset=["Name"])

    Name   Age Department   Salary
0  Rahul  25.0         IT  50000.0
1  Priya   NaN         HR  45000.0
2   Amit  30.0         IT      NaN
3   Neha  26.0    Finance  55000.0
4  Rohit   NaN       None  40000.0

In [121]:
#Q13. Fill missing Salary with the median salary.
df.fillna(df["Salary"].median())

    Name      Age Department   Salary
0  Rahul     25.0         IT  50000.0
1  Priya  50000.0         HR  45000.0
2   Amit     30.0         IT  50000.0
3   Neha     26.0    Finance  55000.0
4  Rohit  50000.0    50000.0  40000.0
5  Rahul     25.0         IT  50000.0

In [143]:
#Q14. Find the number of missing values after filling missing Age with its median.
df["Age"]=df["Age"].fillna(df["Age"].median())
df.isna().sum()

Name          0
Age           0
Department    1
Salary        1
dtype: int64

In [147]:
#Q15. Find the number of duplicate rows after removing duplicates.
df.drop_duplicates()
df.duplicated().sum()

1

In [151]:
#Q16.A dataset has missing salaries. You don't want to delete those employees.

#Fill missing salaries with the median salary.

df.fillna(df["Salary"].median())

    Name   Age Department   Salary
0  Rahul  25.0         IT  50000.0
1  Priya  25.5         HR  45000.0
2   Amit  30.0         IT  50000.0
3   Neha  26.0    Finance  55000.0
4  Rohit  25.5    50000.0  40000.0
5  Rahul  25.0         IT  50000.0

In [165]:
#Q17.Find all employees who have:
'''
Find all employees who have:
Age > 25
AND
Salary is not missing'''
df[(df["Age"]>25)& (df["Salary"].notna())]

    Name   Age Department   Salary
1  Priya  25.5         HR  45000.0
3   Neha  26.0    Finance  55000.0
4  Rohit  25.5       None  40000.0

In [167]:
#Q18.Find all employees who:
'''
Find all employees who:
Department == "IT"
AND
Salary is missing'''


df[(df["Department"]=="IT") & (df["Salary"].isna())]

   Name   Age Department  Salary
2  Amit  30.0         IT     NaN

In [169]:
'''Q19. 🔥

Clean the dataset so that:

Exact duplicate rows are removed.
Missing Age is filled with the median Age.
Missing Department is filled with "Unknown".
Missing Salary is filled with the median Salary.'''

df.drop_duplicates()
df.fillna(df["Age"].median())
df.fillna("Unknown")
df.fillna(df["Salary"].median())

    Name   Age Department   Salary
0  Rahul  25.0         IT  50000.0
1  Priya  25.5         HR  45000.0
2   Amit  30.0         IT  50000.0
3   Neha  26.0    Finance  55000.0
4  Rohit  25.5    50000.0  40000.0
5  Rahul  25.0         IT  50000.0

In [171]:
data = {
    "Name": ["Rahul", "rahul", "Priya", "Amit", "Amit", "Neha"],
    "Age": [25, 25, None, 30, 30, 26],
    "Department": ["IT", "it", "HR", "IT", "IT", None],
    "Salary": [50000, 50000, 45000, None, None, 55000]
}

df = pd.DataFrame(data)
df

    Name   Age Department   Salary
0  Rahul  25.0         IT  50000.0
1  rahul  25.0         it  50000.0
2  Priya   NaN         HR  45000.0
3   Amit  30.0         IT      NaN
4   Amit  30.0         IT      NaN
5   Neha  26.0       None  55000.0

In [179]:
'''Your task:

Clean this dataset and explain what you changed.

💡 You will need to think about:

Case inconsistency (IT vs it)
Missing values
Duplicate records
Appropriate replacement values'''

df["Department"]=df["Department"].replace({
    "it":"IT",
    
})
df

    Name   Age Department   Salary
0  Rahul  25.0         IT  50000.0
1  rahul  25.0         IT  50000.0
2  Priya   NaN         HR  45000.0
3   Amit  30.0         IT      NaN
4   Amit  30.0         IT      NaN
5   Neha  26.0       None  55000.0

In [181]:
df.isna().sum()

Name          0
Age           1
Department    1
Salary        2
dtype: int64

In [183]:
df.duplicated().sum()

1