In [1]:
import pandas as pd

data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit", "Sneha"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [50000, 45000, 65000, 55000, 40000, 70000],
    "Experience": [2, 5, 7, 4, 1, 6]
}

df = pd.DataFrame(data)
df

    Name Department  Salary  Experience
0  Rahul         IT   50000           2
1  Priya         HR   45000           5
2   Amit         IT   65000           7
3   Neha    Finance   55000           4
4  Rohit         HR   40000           1
5  Sneha         IT   70000           6

In [3]:
df.groupby("Department")["Salary"].mean()

Department
Finance    55000.000000
HR         42500.000000
IT         61666.666667
Name: Salary, dtype: float64

In [5]:
#Question:What is the total salary paid by each department?
df.groupby("Department")["Salary"].sum()

Department
Finance     55000
HR          85000
IT         185000
Name: Salary, dtype: int64

In [7]:
#max() min()  Highest salary in each department
df.groupby("Department")["Salary"].max()

Department
Finance    55000
HR         45000
IT         70000
Name: Salary, dtype: int64

In [9]:
df.groupby("Department")["Salary"].min()

Department
Finance    55000
HR         40000
IT         50000
Name: Salary, dtype: int64

In [11]:
#Highest experience in each department
df.groupby("Department")["Experience"].max()

Department
Finance    4
HR         5
IT         7
Name: Experience, dtype: int64

In [13]:
#count()How many employees are there in each department?
df.groupby("Department")["Name"].count()

Department
Finance    1
HR         2
IT         3
Name: Name, dtype: int64

In [15]:
#nunique() How many unique employees are there in each department?
df.groupby("Department")["Name"].nunique()

Department
Finance    1
HR         2
IT         3
Name: Name, dtype: int64

In [23]:
df["Department"].nunique()

3

In [31]:
#Multiple Aggregations with agg() -> For each department, find minimum salary, maximum salary, and average salary.
df.groupby("Department")["Salary"].agg(
    ["min","max","mean"]
)

              min    max          mean
Department
Finance     55000  55000  55000.000000
HR          40000  45000  42500.000000
IT          50000  70000  61666.666667

In [35]:
#Different Aggregations for Different Columns
'''Question:

For each department, find:

average salary
maximum salary
average experience
number of employees'''


df.groupby("Department").agg({
    "Salary" :"mean",
    "Salary" : "max",
    "Experience" :"mean",
    "Name":"count"
})

            Salary  Experience  Name
Department
Finance      55000         4.0     1
HR           45000         3.0     2
IT           70000         5.0     3

In [39]:
df.groupby("Department").agg(
    Average_Salary=("Salary","mean"),
    Maximum_Salary=("Salary","max"),
    Average_Experience=("Experience","mean"),
    Number_Of_Employees=("Name","count")
    
    
    
)

,Average_Salary,Maximum_Salary,Average_Experience,Number_Of_Employees
Department,,,,
Finance,55000.000000,55000,4.0,1
HR,42500.000000,45000,3.0,2
IT,61666.666667,70000,5.0,3

In [41]:
import pandas as pd

data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit", "Sneha", "Vikas", "Pooja"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT", "Finance", "HR"],
    "Salary": [50000, 45000, 65000, 55000, 40000, 70000, 60000, 50000],
    "Experience": [2, 5, 7, 4, 1, 6, 5, 3]
}

df = pd.DataFrame(data)
df

    Name Department  Salary  Experience
0  Rahul         IT   50000           2
1  Priya         HR   45000           5
2   Amit         IT   65000           7
3   Neha    Finance   55000           4
4  Rohit         HR   40000           1
5  Sneha         IT   70000           6
6  Vikas    Finance   60000           5
7  Pooja         HR   50000           3

In [43]:
#Q1. Find the total salary for each department.
df.groupby("Department")["Salary"].sum()

Department
Finance    115000
HR         135000
IT         185000
Name: Salary, dtype: int64

In [45]:
#Q2. Find the average salary for each department.
df.groupby("Department")["Salary"].mean()

Department
Finance    57500.000000
HR         45000.000000
IT         61666.666667
Name: Salary, dtype: float64

In [47]:
#Q3. Find the maximum salary for each department.
df.groupby("Department")["Salary"].max()

Department
Finance    60000
HR         50000
IT         70000
Name: Salary, dtype: int64

In [51]:
#Q4. Find the minimum salary for each department.
df.groupby("Department")["Salary"].min()

Department
Finance    55000
HR         40000
IT         50000
Name: Salary, dtype: int64

In [53]:
#Q5. Find the average experience for each department.
df.groupby("Department")["Experience"].mean()

Department
Finance    4.5
HR         3.0
IT         5.0
Name: Experience, dtype: float64

In [55]:
#Q6. Count the number of employees in each department.
df.groupby("Department")["Name"].count()

Department
Finance    2
HR         3
IT         3
Name: Name, dtype: int64

In [57]:
#Q7. Find the number of unique employees in each department.
df.groupby("Department")["Name"].nunique()

Department
Finance    2
HR         3
IT         3
Name: Name, dtype: int64

In [ ]:
Q8. Find the total salary and average salary for each department.

Q9. Find minimum, maximum and average salary for each department.

Q10. Find average salary and average experience for each department.

Q11. Find employee count and total salary for each department.

Q12. Find all of these for each department:

Employee count
Total salary
Average salary
Maximum salary
Average experience

Use one groupby().agg().

In [59]:
#Q8. Find the total salary and average salary for each department.
df.groupby("Department")["Salary"].agg(
    ["sum","mean"]
)

               sum          mean
Department
Finance     115000  57500.000000
HR          135000  45000.000000
IT          185000  61666.666667

In [61]:
#Q9. Find minimum, maximum and average salary for each department.
df.groupby("Department")["Salary"].agg(
    ["min","max","mean"]
)

              min    max          mean
Department
Finance     55000  60000  57500.000000
HR          40000  50000  45000.000000
IT          50000  70000  61666.666667

In [71]:
#Q10. Find average salary and average experience for each department.
df.groupby("Department").agg(
    Average_Salary=("Salary","mean"),
    Average_Experience=("Experience","mean")
    
    
)

            Average_Salary  Average_Experience
Department
Finance       57500.000000                 4.5
HR            45000.000000                 3.0
IT            61666.666667                 5.0

In [73]:
#Q11. Find employee count and total salary for each department.
df.groupby("Department").agg(
    Employee_Count=("Name","count"),
    Total_Salary=("Salary","sum") 
    
    
)

            Employee_Count  Total_Salary
Department
Finance                  2        115000
HR                       3        135000
IT                       3        185000

In [75]:

'''Q12. Find all of these for each department:

Employee count
Total salary
Average salary
Maximum salary
Average experience

Use one groupby().agg().'''

df.groupby("Department").agg(
    Employee_Count=("Name","count"),
    Total_Salary=("Salary","sum"),
    Average_Salary=("Salary","mean"),
    Maximum_Salary=("Salary","max"),
    Average_Experience=("Experience","mean")
    
    
    
    
    
)

,Employee_Count,Total_Salary,Average_Salary,Maximum_Salary,Average_Experience
Department,,,,,
Finance,2,115000,57500.000000,60000,4.5
HR,3,135000,45000.000000,50000,3.0
IT,3,185000,61666.666667,70000,5.0

In [ ]:
Q13. Which department has the highest total salary?

Hint:

GROUPBY
→ SUM
→ MAX

Q14. Which department has the highest average salary?

Q15. Which department has the lowest average salary?

Q16. Find the department where employees have the highest average experience.

Q17. Find departments having more than 2 employees.
Q19.

Find the department whose total salary expense is highest.

Q20.

Find the department whose average salary is greater than 55,000.

In [77]:
#13. Which department has the highest total salary?
df.groupby("Department")["Salary"].agg(
    ["max","sum"]
)

              max     sum
Department
Finance     60000  115000
HR          50000  135000
IT          70000  185000

In [79]:
#Q14. Which department has the highest average salary?
df.groupby("Department")["Salary"].agg(
    ["max","mean"]
)

              max          mean
Department
Finance     60000  57500.000000
HR          50000  45000.000000
IT          70000  61666.666667

In [81]:
#Q15. Which department has the lowest average salary?
df.groupby("Department")["Salary"].agg(
    ["min","mean"]
)

              min          mean
Department
Finance     55000  57500.000000
HR          40000  45000.000000
IT          50000  61666.666667

In [83]:
#Q16. Find the department where employees have the highest average experience.
df.groupby("Department")["Experience"].agg(
    ["max","mean"]
)

            max  mean
Department
Finance       5   4.5
HR            5   3.0
IT            7   5.0

In [105]:
#Q17. Find departments having more than 2 employees.
df["Department"].value_counts() > 2

Department
IT          True
HR          True
Finance    False
Name: count, dtype: bool

In [109]:
#Q19.Find the department whose total salary expense is highest.
df.groupby("Department")["Salary"].sum().idxmax()

'IT'

In [111]:
#Q20.Find the department whose average salary is greater than 55,000.
df.groupby("Department")["Salary"].mean()>55000

Department
Finance     True
HR         False
IT          True
Name: Salary, dtype: bool