In [3]:
import pandas as pd

data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit", "Sneha", "Vikas", "Pooja"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT", "Finance", "HR"],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female"],
    "Salary": [50000, 45000, 65000, 55000, 40000, 70000, 60000, 50000],
    "Experience": [2, 5, 7, 4, 1, 6, 5, 3]
}

df = pd.DataFrame(data)
df

    Name Department  Gender  Salary  Experience
0  Rahul         IT    Male   50000           2
1  Priya         HR  Female   45000           5
2   Amit         IT    Male   65000           7
3   Neha    Finance  Female   55000           4
4  Rohit         HR    Male   40000           1
5  Sneha         IT  Female   70000           6
6  Vikas    Finance    Male   60000           5
7  Pooja         HR  Female   50000           3

In [7]:
#What is the average salary for each Department and Gender?
df.groupby(["Department","Gender"])["Salary"].mean()

Department  Gender
Finance     Female    55000.0
            Male      60000.0
HR          Female    47500.0
            Male      40000.0
IT          Female    70000.0
            Male      57500.0
Name: Salary, dtype: float64

In [17]:
#Show departments from highest average salary to lowest. Sorting Grouped Results
result=(
    df.groupby("Department")["Salary"].mean().reset_index().sort_values("Salary",ascending=False)
)
result

  Department        Salary
2         IT  61666.666667
0    Finance  57500.000000
1         HR  45000.000000

In [31]:
#Filtering Groups .Find departments where average salary is greater than 50,000.
avg_sal=df.groupby("Department")["Salary"].mean()
avg_sal[avg_sal>50000]

Department
Finance    57500.000000
IT         61666.666667
Name: Salary, dtype: float64

In [33]:
#groupby().filter() -Keep only departments having more than 2 employees.
df.groupby("Department").filter(
    lambda x:len(x) > 2
)

    Name Department  Gender  Salary  Experience
0  Rahul         IT    Male   50000           2
1  Priya         HR  Female   45000           5
2   Amit         IT    Male   65000           7
4  Rohit         HR    Male   40000           1
5  Sneha         IT  Female   70000           6
7  Pooja         HR  Female   50000           3

In [63]:
#transform()-Add the average salary of each employee's department.
df["avg_sal_transform"]=df.groupby("Department")["Salary"].transform("mean")


df

,Name,Department,Gender,Salary,Experience,61666.666667,45000.0,57500.0,avg_sal_transform
0,Rahul,IT,Male,50000,2,61666.666667,45000.0,57500.0,61666.666667
1,Priya,HR,Female,45000,5,61666.666667,45000.0,57500.0,45000.000000
2,Amit,IT,Male,65000,7,61666.666667,45000.0,57500.0,61666.666667
3,Neha,Finance,Female,55000,4,61666.666667,45000.0,57500.0,57500.000000
4,Rohit,HR,Male,40000,1,61666.666667,45000.0,57500.0,45000.000000
5,Sneha,IT,Female,70000,6,61666.666667,45000.0,57500.0,61666.666667
6,Vikas,Finance,Male,60000,5,61666.666667,45000.0,57500.0,57500.000000
7,Pooja,HR,Female,50000,3,61666.666667,45000.0,57500.0,45000.000000

In [67]:
#Compare Employee Salary With Department Average
#Which employees earn more than their department's average salary?

df["avg_sal_dep"]=df.groupby("Department")["Salary"].transform("mean")
df[df["Salary"] > df["avg_sal_dep"]]

,Name,Department,Gender,Salary,Experience,61666.666667,45000.0,57500.0,avg_sal_transform,avg_sal_dep
2,Amit,IT,Male,65000,7,61666.666667,45000.0,57500.0,61666.666667,61666.666667
5,Sneha,IT,Female,70000,6,61666.666667,45000.0,57500.0,61666.666667,61666.666667
6,Vikas,Finance,Male,60000,5,61666.666667,45000.0,57500.0,57500.000000,57500.000000
7,Pooja,HR,Female,50000,3,61666.666667,45000.0,57500.0,45000.000000,45000.000000

In [71]:
#Calculate Salary Difference
df["salary_diff"]=df["Salary"]- df["avg_sal_dep"]
df

,Name,Department,Gender,Salary,Experience,61666.666667,45000.0,57500.0,avg_sal_transform,avg_sal_dep,salary_diff
0,Rahul,IT,Male,50000,2,61666.666667,45000.0,57500.0,61666.666667,61666.666667,-11666.666667
1,Priya,HR,Female,45000,5,61666.666667,45000.0,57500.0,45000.000000,45000.000000,0.000000
2,Amit,IT,Male,65000,7,61666.666667,45000.0,57500.0,61666.666667,61666.666667,3333.333333
3,Neha,Finance,Female,55000,4,61666.666667,45000.0,57500.0,57500.000000,57500.000000,-2500.000000
4,Rohit,HR,Male,40000,1,61666.666667,45000.0,57500.0,45000.000000,45000.000000,-5000.000000
5,Sneha,IT,Female,70000,6,61666.666667,45000.0,57500.0,61666.666667,61666.666667,8333.333333
6,Vikas,Finance,Male,60000,5,61666.666667,45000.0,57500.0,57500.000000,57500.000000,2500.000000
7,Pooja,HR,Female,50000,3,61666.666667,45000.0,57500.0,45000.000000,45000.000000,5000.000000

In [79]:
#Percentage Difference
df["per_diff"]=(df["Salary"]-df["avg_sal_dep"]) / df["avg_sal_dep"]*100
df

,Name,Department,Gender,Salary,Experience,61666.666667,45000.0,57500.0,avg_sal_transform,avg_sal_dep,salary_diff,per_diff
0,Rahul,IT,Male,50000,2,61666.666667,45000.0,57500.0,61666.666667,61666.666667,-11666.666667,-18.918919
1,Priya,HR,Female,45000,5,61666.666667,45000.0,57500.0,45000.000000,45000.000000,0.000000,0.000000
2,Amit,IT,Male,65000,7,61666.666667,45000.0,57500.0,61666.666667,61666.666667,3333.333333,5.405405
3,Neha,Finance,Female,55000,4,61666.666667,45000.0,57500.0,57500.000000,57500.000000,-2500.000000,-4.347826
4,Rohit,HR,Male,40000,1,61666.666667,45000.0,57500.0,45000.000000,45000.000000,-5000.000000,-11.111111
5,Sneha,IT,Female,70000,6,61666.666667,45000.0,57500.0,61666.666667,61666.666667,8333.333333,13.513514
6,Vikas,Finance,Male,60000,5,61666.666667,45000.0,57500.0,57500.000000,57500.000000,2500.000000,4.347826
7,Pooja,HR,Female,50000,3,61666.666667,45000.0,57500.0,45000.000000,45000.000000,5000.000000,11.111111

In [87]:
#Find Highest-Paid Employee in Each Department
idx=df.loc[df.groupby("Department")["Salary"].idxmax()]
idx

,Name,Department,Gender,Salary,Experience,61666.666667,45000.0,57500.0,avg_sal_transform,avg_sal_dep,salary_diff,per_diff
6,Vikas,Finance,Male,60000,5,61666.666667,45000.0,57500.0,57500.000000,57500.000000,2500.000000,4.347826
7,Pooja,HR,Female,50000,3,61666.666667,45000.0,57500.0,45000.000000,45000.000000,5000.000000,11.111111
5,Sneha,IT,Female,70000,6,61666.666667,45000.0,57500.0,61666.666667,61666.666667,8333.333333,13.513514

In [93]:
#Group-Wise Ranking - rank employees within their department.
df["department_rank_emp"]=df.groupby("Department")["Salary"].rank(ascending=False)
df

,Name,Department,Gender,Salary,Experience,61666.666667,45000.0,57500.0,avg_sal_transform,avg_sal_dep,salary_diff,per_diff,department_rank_emp
0,Rahul,IT,Male,50000,2,61666.666667,45000.0,57500.0,61666.666667,61666.666667,-11666.666667,-18.918919,3.0
1,Priya,HR,Female,45000,5,61666.666667,45000.0,57500.0,45000.000000,45000.000000,0.000000,0.000000,2.0
2,Amit,IT,Male,65000,7,61666.666667,45000.0,57500.0,61666.666667,61666.666667,3333.333333,5.405405,2.0
3,Neha,Finance,Female,55000,4,61666.666667,45000.0,57500.0,57500.000000,57500.000000,-2500.000000,-4.347826,2.0
4,Rohit,HR,Male,40000,1,61666.666667,45000.0,57500.0,45000.000000,45000.000000,-5000.000000,-11.111111,3.0
5,Sneha,IT,Female,70000,6,61666.666667,45000.0,57500.0,61666.666667,61666.666667,8333.333333,13.513514,1.0
6,Vikas,Finance,Male,60000,5,61666.666667,45000.0,57500.0,57500.000000,57500.000000,2500.000000,4.347826,1.0
7,Pooja,HR,Female,50000,3,61666.666667,45000.0,57500.0,45000.000000,45000.000000,5000.000000,11.111111,1.0

In [95]:
import pandas as pd

data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit", "Sneha", "Vikas", "Pooja"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT", "Finance", "HR"],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female"],
    "Salary": [50000, 45000, 65000, 55000, 40000, 70000, 60000, 50000],
    "Experience": [2, 5, 7, 4, 1, 6, 5, 3]
}

df = pd.DataFrame(data)
df

    Name Department  Gender  Salary  Experience
0  Rahul         IT    Male   50000           2
1  Priya         HR  Female   45000           5
2   Amit         IT    Male   65000           7
3   Neha    Finance  Female   55000           4
4  Rohit         HR    Male   40000           1
5  Sneha         IT  Female   70000           6
6  Vikas    Finance    Male   60000           5
7  Pooja         HR  Female   50000           3

In [ ]:
Q1. Find average salary for each Department + Gender.

Q2. Find maximum salary for each Department + Gender.

Q3. Find employee count for each Department + Gender.

Q4. Find total salary for each department.

Q5. Sort departments by average salary from highest to lowest.

In [97]:
#Q1. Find average salary for each Department + Gender.
df.groupby(["Department","Gender"])["Salary"].mean()

Department  Gender
Finance     Female    55000.0
            Male      60000.0
HR          Female    47500.0
            Male      40000.0
IT          Female    70000.0
            Male      57500.0
Name: Salary, dtype: float64

In [99]:
#Q2. Find maximum salary for each Department + Gender.
df.groupby(["Department","Gender"])["Salary"].max()

Department  Gender
Finance     Female    55000
            Male      60000
HR          Female    50000
            Male      40000
IT          Female    70000
            Male      65000
Name: Salary, dtype: int64

In [101]:
#Q3. Find employee count for each Department + Gender.
df.groupby(["Department","Gender"])["Name"].count()

Department  Gender
Finance     Female    1
            Male      1
HR          Female    2
            Male      1
IT          Female    1
            Male      2
Name: Name, dtype: int64

In [103]:
#Q4. Find total salary for each department.
df.groupby("Department")["Salary"].sum()

Department
Finance    115000
HR         135000
IT         185000
Name: Salary, dtype: int64

In [122]:
#Q5. Sort departments by average salary from highest to lowest.
df.groupby("Department")["Salary"].mean().reset_index().sort_values(by="Salary",ascending=False)

  Department        Salary
2         IT  61666.666667
0    Finance  57500.000000
1         HR  45000.000000

In [ ]:
Q6. Find departments having more than 2 employees.

Q7. Find departments whose average salary is greater than 50,000.

Q8. Find departments whose total salary is greater than 100,000.

Q9. Find employees belonging to departments with more than 2 employees.

Q10. Find employees whose salary is greater than their department's average salary.

In [124]:
#Q6. Find departments having more than 2 employees.
df.groupby("Department").filter(
    lambda x :len(x)>2
)

    Name Department  Gender  Salary  Experience
0  Rahul         IT    Male   50000           2
1  Priya         HR  Female   45000           5
2   Amit         IT    Male   65000           7
4  Rohit         HR    Male   40000           1
5  Sneha         IT  Female   70000           6
7  Pooja         HR  Female   50000           3

In [144]:
#Q7. Find departments whose average salary is greater than 50,000.
#avg_sal=df.groupby("Department")["Salary"].mean()
#avg_sal[avg_sal>50000]
#or

filterr=df.groupby("Department").filter(
    lambda x :x["Salary"].mean()>50000
)
filterr

    Name Department  Gender  Salary  Experience
0  Rahul         IT    Male   50000           2
2   Amit         IT    Male   65000           7
3   Neha    Finance  Female   55000           4
5  Sneha         IT  Female   70000           6
6  Vikas    Finance    Male   60000           5

In [148]:
#Q8. Find departments whose total salary is greater than 100,000.
df.groupby("Department").filter(
    lambda x:x["Salary"].sum()>100000
)

    Name Department  Gender  Salary  Experience
0  Rahul         IT    Male   50000           2
1  Priya         HR  Female   45000           5
2   Amit         IT    Male   65000           7
3   Neha    Finance  Female   55000           4
4  Rohit         HR    Male   40000           1
5  Sneha         IT  Female   70000           6
6  Vikas    Finance    Male   60000           5
7  Pooja         HR  Female   50000           3

In [156]:
#Q9. Find employees belonging to departments with more than 2 employees.
df.groupby("Department").filter(
    lambda x :len(x) > 2
)

    Name Department  Gender  Salary  Experience
0  Rahul         IT    Male   50000           2
1  Priya         HR  Female   45000           5
2   Amit         IT    Male   65000           7
4  Rohit         HR    Male   40000           1
5  Sneha         IT  Female   70000           6
7  Pooja         HR  Female   50000           3

In [168]:
#Q10. Find employees whose salary is greater than their department's average salary.
df["avg_sal"]=df.groupby("Department")["Salary"].transform("mean")
df[df["Salary"]>df["avg_sal"]]

    Name Department  Gender  Salary  Experience       avg_sal
2   Amit         IT    Male   65000           7  61666.666667
5  Sneha         IT  Female   70000           6  61666.666667
6  Vikas    Finance    Male   60000           5  57500.000000
7  Pooja         HR  Female   50000           3  45000.000000

In [ ]:
Q11. Create a column:

Department_Avg_Salary

Q12. Create:

Salary_Difference

Q13. Create:

Salary_Difference_Percent

Q14. Find employees earning below their department average.

Q15. Find employees earning more than 10% above their department average.

In [172]:
#Q11. Create a column: Department_Avg_Salary
df["Department_Avg_Salary"]=df.groupby("Department")["Salary"].transform("mean")
df

,Name,Department,Gender,Salary,Experience,avg_sal,Department_Avg_Salary
0,Rahul,IT,Male,50000,2,61666.666667,61666.666667
1,Priya,HR,Female,45000,5,45000.000000,45000.000000
2,Amit,IT,Male,65000,7,61666.666667,61666.666667
3,Neha,Finance,Female,55000,4,57500.000000,57500.000000
4,Rohit,HR,Male,40000,1,45000.000000,45000.000000
5,Sneha,IT,Female,70000,6,61666.666667,61666.666667
6,Vikas,Finance,Male,60000,5,57500.000000,57500.000000
7,Pooja,HR,Female,50000,3,45000.000000,45000.000000

In [180]:
#Q12. Create:Salary_Difference
df["Salary_Difference"]=df["Salary"]-df["Department_Avg_Salary"]
df

,Name,Department,Gender,Salary,Experience,avg_sal,Department_Avg_Salary,Salary_Difference
0,Rahul,IT,Male,50000,2,61666.666667,61666.666667,-11666.666667
1,Priya,HR,Female,45000,5,45000.000000,45000.000000,0.000000
2,Amit,IT,Male,65000,7,61666.666667,61666.666667,3333.333333
3,Neha,Finance,Female,55000,4,57500.000000,57500.000000,-2500.000000
4,Rohit,HR,Male,40000,1,45000.000000,45000.000000,-5000.000000
5,Sneha,IT,Female,70000,6,61666.666667,61666.666667,8333.333333
6,Vikas,Finance,Male,60000,5,57500.000000,57500.000000,2500.000000
7,Pooja,HR,Female,50000,3,45000.000000,45000.000000,5000.000000

In [186]:
#Q13. Create:Salary_Difference_Percentage
df["Salary_Difference_Percentage"]=df["Salary"]-df["Department_Avg_Salary"]/df["Department_Avg_Salary"]
df

,Name,Department,Gender,Salary,Experience,avg_sal,Department_Avg_Salary,Salary_Difference,Salary_Difference_Percentage
0,Rahul,IT,Male,50000,2,61666.666667,61666.666667,-11666.666667,49999.0
1,Priya,HR,Female,45000,5,45000.000000,45000.000000,0.000000,44999.0
2,Amit,IT,Male,65000,7,61666.666667,61666.666667,3333.333333,64999.0
3,Neha,Finance,Female,55000,4,57500.000000,57500.000000,-2500.000000,54999.0
4,Rohit,HR,Male,40000,1,45000.000000,45000.000000,-5000.000000,39999.0
5,Sneha,IT,Female,70000,6,61666.666667,61666.666667,8333.333333,69999.0
6,Vikas,Finance,Male,60000,5,57500.000000,57500.000000,2500.000000,59999.0
7,Pooja,HR,Female,50000,3,45000.000000,45000.000000,5000.000000,49999.0

In [192]:
#Q14. Find employees earning below their department average.
df["dept_avg"]=df.groupby("Department")["Salary"].transform("mean")
df[df["Salary"] < df["dept_avg"]]

,Name,Department,Gender,Salary,Experience,avg_sal,Department_Avg_Salary,Salary_Difference,Salary_Difference_Percentage,dept_avg
0,Rahul,IT,Male,50000,2,61666.666667,61666.666667,-11666.666667,49999.0,61666.666667
3,Neha,Finance,Female,55000,4,57500.000000,57500.000000,-2500.000000,54999.0,57500.000000
4,Rohit,HR,Male,40000,1,45000.000000,45000.000000,-5000.000000,39999.0,45000.000000

In [198]:
#Q15. Find employees earning more than 10% above their department average.
df["dept_avg"]=df.groupby("Department")["Salary"].transform("mean")
df[df["Salary"]>df["dept_avg"]*0.10]

,Name,Department,Gender,Salary,Experience,avg_sal,Department_Avg_Salary,Salary_Difference,Salary_Difference_Percentage,dept_avg
0,Rahul,IT,Male,50000,2,61666.666667,61666.666667,-11666.666667,49999.0,61666.666667
1,Priya,HR,Female,45000,5,45000.000000,45000.000000,0.000000,44999.0,45000.000000
2,Amit,IT,Male,65000,7,61666.666667,61666.666667,3333.333333,64999.0,61666.666667
3,Neha,Finance,Female,55000,4,57500.000000,57500.000000,-2500.000000,54999.0,57500.000000
4,Rohit,HR,Male,40000,1,45000.000000,45000.000000,-5000.000000,39999.0,45000.000000
5,Sneha,IT,Female,70000,6,61666.666667,61666.666667,8333.333333,69999.0,61666.666667
6,Vikas,Finance,Male,60000,5,57500.000000,57500.000000,2500.000000,59999.0,57500.000000
7,Pooja,HR,Female,50000,3,45000.000000,45000.000000,5000.000000,49999.0,45000.000000

In [ ]:
#Q16. Find the highest-paid employee from each department.

Q17. Find the lowest-paid employee from each department.

Q18. Rank employees by salary within their department.

Q19. Find the top 2 highest-paid employees from each department.

Q20. Find the employee with the highest experience in each department.

In [202]:
#Q16. Find the highest-paid employee from each department.
idx=df.loc[df.groupby("Department")["Salary"].idxmax()]
idx

,Name,Department,Gender,Salary,Experience,avg_sal,Department_Avg_Salary,Salary_Difference,Salary_Difference_Percentage,dept_avg
6,Vikas,Finance,Male,60000,5,57500.000000,57500.000000,2500.000000,59999.0,57500.000000
7,Pooja,HR,Female,50000,3,45000.000000,45000.000000,5000.000000,49999.0,45000.000000
5,Sneha,IT,Female,70000,6,61666.666667,61666.666667,8333.333333,69999.0,61666.666667

In [206]:
#Q17. Find the lowest-paid employee from each department.
idx_min=df.loc[df.groupby("Department")["Salary"].idxmin()]
idx_min

,Name,Department,Gender,Salary,Experience,avg_sal,Department_Avg_Salary,Salary_Difference,Salary_Difference_Percentage,dept_avg
3,Neha,Finance,Female,55000,4,57500.000000,57500.000000,-2500.000000,54999.0,57500.000000
4,Rohit,HR,Male,40000,1,45000.000000,45000.000000,-5000.000000,39999.0,45000.000000
0,Rahul,IT,Male,50000,2,61666.666667,61666.666667,-11666.666667,49999.0,61666.666667

In [212]:
#Q18. Rank employees by salary within their department.
df["rank"]=df.groupby("Department")["Salary"].rank()
df

,Name,Department,Gender,Salary,Experience,avg_sal,Department_Avg_Salary,Salary_Difference,Salary_Difference_Percentage,dept_avg,rank
0,Rahul,IT,Male,50000,2,61666.666667,61666.666667,-11666.666667,49999.0,61666.666667,1.0
1,Priya,HR,Female,45000,5,45000.000000,45000.000000,0.000000,44999.0,45000.000000,2.0
2,Amit,IT,Male,65000,7,61666.666667,61666.666667,3333.333333,64999.0,61666.666667,2.0
3,Neha,Finance,Female,55000,4,57500.000000,57500.000000,-2500.000000,54999.0,57500.000000,1.0
4,Rohit,HR,Male,40000,1,45000.000000,45000.000000,-5000.000000,39999.0,45000.000000,1.0
5,Sneha,IT,Female,70000,6,61666.666667,61666.666667,8333.333333,69999.0,61666.666667,3.0
6,Vikas,Finance,Male,60000,5,57500.000000,57500.000000,2500.000000,59999.0,57500.000000,2.0
7,Pooja,HR,Female,50000,3,45000.000000,45000.000000,5000.000000,49999.0,45000.000000,3.0

In [226]:
#Q19. Find the top 2 highest-paid employees from each department.
df.groupby("Department")["Salary"].nlargest(2)

Department
Finance     6    60000
            3    55000
HR          7    50000
            1    45000
IT          5    70000
            2    65000
Name: Salary, dtype: int64

In [234]:
#Q20. Find the employee with the highest experience in each department.
df.loc[df.groupby("Department")["Experience"].idxmax()]

,Name,Department,Gender,Salary,Experience,avg_sal,Department_Avg_Salary,Salary_Difference,Salary_Difference_Percentage,dept_avg,rank
6,Vikas,Finance,Male,60000,5,57500.000000,57500.000000,2500.000000,59999.0,57500.000000,2.0
1,Priya,HR,Female,45000,5,45000.000000,45000.000000,0.000000,44999.0,45000.000000,2.0
2,Amit,IT,Male,65000,7,61666.666667,61666.666667,3333.333333,64999.0,61666.666667,2.0

In [246]:
#21Find the department with the highest average salary.
df.groupby("Department")["Salary"].mean().idxmax()

'IT'

In [250]:
#22Find the department with the highest total salary expenditure.
df.groupby("Department")["Salary"].sum().idxmax()

'IT'