In [182]:
import pandas as pd
employees = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit"],
    "Department_ID": [1, 2, 1, 3, 4],
    "Salary": [50000, 45000, 65000, 55000, 40000]
})

departments = pd.DataFrame({
    "Department_ID": [1, 2, 3],
    "Department": ["IT", "HR", "Finance"]
})

sales = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005],
    "Customer_ID": [1, 2, 1, 3, 5],
    "Amount": [500, 700, 300, 900, 400]
})#

customers = pd.DataFrame({
    "Customer_ID": [1, 2, 3, 4],
    "Customer_Name": ["Rahul", "Priya", "Amit", "Neha"]
})
orders = pd.DataFrame({
    "Order_ID": [101, 102, 103, 104, 105],
    "Customer_ID": [1, 2, 1, 3, 5],
    "Amount": [500, 700, 300, 900, 400]
})
salary = pd.DataFrame({
    "Salary": [50000, 45000, 65000]
}, index=[101, 102, 103])

In [10]:
employees

   Employee_ID   Name  Department_ID  Salary
0          101  Rahul              1   50000
1          102  Priya              2   45000
2          103   Amit              1   65000
3          104   Neha              3   55000
4          105  Rohit              4   40000

In [12]:
departments

   Department_ID Department
0              1         IT
1              2         HR
2              3    Finance

In [14]:
sales

   Order_ID  Customer_ID  Amount
0      1001            1     500
1      1002            2     700
2      1003            1     300
3      1004            3     900
4      1005            5     400

In [16]:
customers

   Customer_ID Customer_Name
0            1         Rahul
1            2         Priya
2            3          Amit
3            4          Neha

In [ ]:
Q1. Concatenate two DataFrames vertically.

Q2. Concatenate two DataFrames horizontally.

Q3. Merge employees and departments using Department_ID.

Q4. Perform an inner join.

Q5. Perform a left join.

In [26]:
#Q1. Concatenate two DataFrames vertically.
pd.concat([employees,departments],axis=0)

   Employee_ID   Name  Department_ID   Salary Department
0        101.0  Rahul              1  50000.0        NaN
1        102.0  Priya              2  45000.0        NaN
2        103.0   Amit              1  65000.0        NaN
3        104.0   Neha              3  55000.0        NaN
4        105.0  Rohit              4  40000.0        NaN
0          NaN    NaN              1      NaN         IT
1          NaN    NaN              2      NaN         HR
2          NaN    NaN              3      NaN    Finance

In [24]:
#Q2. Concatenate two DataFrames horizontally.
pd.concat([employees,departments],axis=1)

   Employee_ID   Name  Department_ID  Salary  Department_ID Department
0          101  Rahul              1   50000            1.0         IT
1          102  Priya              2   45000            2.0         HR
2          103   Amit              1   65000            3.0    Finance
3          104   Neha              3   55000            NaN        NaN
4          105  Rohit              4   40000            NaN        NaN

In [30]:
#Q3. Merge employees and departments using Department_ID.
pd.merge(employees ,departments,on="Department_ID")

   Employee_ID   Name  Department_ID  Salary Department
0          101  Rahul              1   50000         IT
1          102  Priya              2   45000         HR
2          103   Amit              1   65000         IT
3          104   Neha              3   55000    Finance

In [32]:
#Q4. Perform an inner join.
pd.merge(employees ,departments,on="Department_ID",how="inner")

   Employee_ID   Name  Department_ID  Salary Department
0          101  Rahul              1   50000         IT
1          102  Priya              2   45000         HR
2          103   Amit              1   65000         IT
3          104   Neha              3   55000    Finance

In [34]:
#Q5. Perform a left join.
pd.merge(employees ,departments,on="Department_ID",how="left")

   Employee_ID   Name  Department_ID  Salary Department
0          101  Rahul              1   50000         IT
1          102  Priya              2   45000         HR
2          103   Amit              1   65000         IT
3          104   Neha              3   55000    Finance
4          105  Rohit              4   40000        NaN

In [ ]:
Q6. Perform a right join.

Q7. Perform an outer join.

Q8. Merge sales and customers.

Q9. Keep all sales records while adding customer names.

Q10. Find sales records where the customer does not exist in the customer table.

In [36]:
#Q6. Perform a right join.
pd.merge(employees ,departments,on="Department_ID",how="right")

   Employee_ID   Name  Department_ID  Salary Department
0          101  Rahul              1   50000         IT
1          103   Amit              1   65000         IT
2          102  Priya              2   45000         HR
3          104   Neha              3   55000    Finance

In [38]:
#Q7. Perform an outer join.
pd.merge(employees ,departments,on="Department_ID",how="outer")

   Employee_ID   Name  Department_ID  Salary Department
0          101  Rahul              1   50000         IT
1          103   Amit              1   65000         IT
2          102  Priya              2   45000         HR
3          104   Neha              3   55000    Finance
4          105  Rohit              4   40000        NaN

In [40]:
#Q8. Merge sales and customers.
pd.merge(sales,customers)

   Order_ID  Customer_ID  Amount Customer_Name
0      1001            1     500         Rahul
1      1002            2     700         Priya
2      1003            1     300         Rahul
3      1004            3     900          Amit

In [42]:
#Q9. Keep all sales records while adding customer names.
pd.merge(sales,customers,on="Customer_ID",how="left")

   Order_ID  Customer_ID  Amount Customer_Name
0      1001            1     500         Rahul
1      1002            2     700         Priya
2      1003            1     300         Rahul
3      1004            3     900          Amit
4      1005            5     400           NaN

In [58]:
#Q10. Find sales records where the customer does not exist in the customer table.
miss_cust=pd.merge(sales,customers,on="Customer_ID",how="left",indicator=True)
res=miss_cust[miss_cust["_merge"]=="left_only"]
res

   Order_ID  Customer_ID  Amount Customer_Name     _merge
4      1005            5     400           NaN  left_only

In [62]:
departments2 = pd.DataFrame({
    "Dept_ID": [1, 2, 3],
    "Department": ["IT", "HR", "Finance"]
})
departments2

   Dept_ID Department
0        1         IT
1        2         HR
2        3    Finance

In [ ]:
Q11. Merge employees with departments2 using Department_ID and Dept_ID.

Q12. Keep all employees.

Q13. Keep all departments.

In [66]:
#Q11. Merge employees with departments2 using Department_ID and Dept_ID.
pd.merge( employees, departments2 ,
        left_on="Department_ID" ,
        right_on="Dept_ID")

   Employee_ID   Name  Department_ID  Salary  Dept_ID Department
0          101  Rahul              1   50000        1         IT
1          102  Priya              2   45000        2         HR
2          103   Amit              1   65000        1         IT
3          104   Neha              3   55000        3    Finance

In [68]:
#Q12. Keep all employees
pd.merge(employees, departments2 ,
        left_on="Department_ID" ,
        right_on="Dept_ID",
        how="left")

   Employee_ID   Name  Department_ID  Salary  Dept_ID Department
0          101  Rahul              1   50000      1.0         IT
1          102  Priya              2   45000      2.0         HR
2          103   Amit              1   65000      1.0         IT
3          104   Neha              3   55000      3.0    Finance
4          105  Rohit              4   40000      NaN        NaN

In [70]:
#Q13. Keep all departments.
pd.merge(employees, departments2 ,
        left_on="Department_ID" ,
        right_on="Dept_ID",
        how="right")

   Employee_ID   Name  Department_ID  Salary  Dept_ID Department
0          101  Rahul              1   50000        1         IT
1          103   Amit              1   65000        1         IT
2          102  Priya              2   45000        2         HR
3          104   Neha              3   55000        3    Finance

In [ ]:
Q14. Find employees whose department information is missing.

Q15. Find departments that have no employees.

Q16. Create a final employee dataset containing:

Employee_ID
Name
Department
Salary

Q17. Calculate average salary by department using the merged dataset.

Q18. Find the department with the highest average salary.

Q19. Find employees whose department is missing.

Q20. Find customers who have never placed an order.

In [86]:
#Q14. Find employees whose department information is missing.
missing_department=pd.merge(employees,
        departments,
        on="Department_ID",
        how="left",indicator=True)
res=missing_department[missing_department["_merge"]=="left_only"]

res

   Employee_ID   Name  Department_ID  Salary Department     _merge
4          105  Rohit              4   40000        NaN  left_only

In [100]:
#Q15. Find departments that have no employees
missing_emp=pd.merge(
        departments,employees,
        on="Department_ID",
        how="left",
indicator=True)

res=missing_emp[missing_emp["_merge"]=="left_only"]
res

Empty DataFrame
Columns: [Department_ID, Department, Employee_ID, Name, Salary, _merge]
Index: []

In [108]:
#Q16. Create a final employee dataset containing:

'''Q16. Create a final employee dataset containing:

Employee_ID
Name
Department
Salary'''

final_res=pd.merge(employees,departments,on="Department_ID",how="left")
res=final_res[["Employee_ID","Name","Department","Salary"]]
res

   Employee_ID   Name Department  Salary
0          101  Rahul         IT   50000
1          102  Priya         HR   45000
2          103   Amit         IT   65000
3          104   Neha    Finance   55000
4          105  Rohit        NaN   40000

In [134]:
#Q17. Calculate average salary by department using the merged dataset.
avg_sal=pd.merge(employees,departments,on="Department_ID",how="left")
res=avg_sal.groupby("Department")["Salary"].mean().reset_index()
res

  Department   Salary
0    Finance  55000.0
1         HR  45000.0
2         IT  57500.0

In [136]:
#Q18. Find the department with the highest average salary.
high_avg_sal=pd.merge(employees,departments,on="Department_ID",how="left")
high_avg_sal.groupby("Department")["Salary"].mean().idxmax()

'IT'

In [144]:
#Q19. Find employees whose department is missing.
missing_Dept=pd.merge(employees,departments,on="Department_ID",how="left",indicator=True)
res=missing_Dept[missing_Dept["_merge"]=="left_only"]
res

   Employee_ID   Name  Department_ID  Salary Department     _merge
4          105  Rohit              4   40000        NaN  left_only

In [162]:
#Q20. Find customers who have never placed an order.
result=pd.merge(customers,sales,on="Customer_ID",how="left",indicator=True)
result[result["_merge"]=="left_only"]

   Customer_ID Customer_Name  Order_ID  Amount     _merge
4            4          Neha       NaN     NaN  left_only

In [164]:

'''Q21.

Find unmatched employees after joining employees with departments.'''

result=pd.merge(employees,departments,on="Department_ID",how="left",indicator=True)
result[result["_merge"]=="left_only"]

   Employee_ID   Name  Department_ID  Salary Department     _merge
4          105  Rohit              4   40000        NaN  left_only

In [176]:
#Find unmatched departments after joining departments with employees.
res=pd.merge(employees,departments,on="Department_ID",how="right",indicator=True)
res[res["_merge"]=="right_only"]

Empty DataFrame
Columns: [Employee_ID, Name, Department_ID, Salary, Department, _merge]
Index: []

In [180]:
'''You have an orders table and a customers table.
You must preserve every order, even if customer information is missing. 
Which join would you use and why?'''
res=pd.merge(orders,customers,on="Customer_ID",how="left",indicator=True)
res[res["_merge"]=="left_only"]

   Order_ID  Customer_ID  Amount Customer_Name     _merge
4       105            5     400           NaN  left_only

In [186]:
#Q25. 🔥🔥 Real Business Problem
'''Which employees have missing department information?
1.What is the average salary by department?
2.Which department has the highest total salary?
3.How many employees are in each department?
4.Which employees have salary above their department average?''' 

res=pd.merge(employees,departments,on="Department_ID",how="left",indicator=True)
res[res["_merge"]=="left_only"]

   Employee_ID   Name  Department_ID  Salary Department     _merge
4          105  Rohit              4   40000        NaN  left_only

In [190]:
#Q2
res=pd.merge(employees,departments,on="Department_ID",how="left")
res.groupby("Department")["Salary"].mean().reset_index()

  Department   Salary
0    Finance  55000.0
1         HR  45000.0
2         IT  57500.0

In [194]:
#Q3
res=pd.merge(employees,departments,on="Department_ID",how="left")
res.groupby("Department")["Employee_ID"].count().reset_index()

  Department  Employee_ID
0    Finance            1
1         HR            1
2         IT            2

In [200]:
res=pd.merge(employees,departments,on="Department_ID",how="left")
res["avg_sal"]=res.groupby("Department")["Salary"].transform("mean")
res[res["Salary"] > res["avg_sal"]]

   Employee_ID  Name  Department_ID  Salary Department  avg_sal
2          103  Amit              1   65000         IT  57500.0