In [324]:
import pandas as pd

data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit"],
    "Order_Date": [
        "2025-01-15",
        "2025-02-20",
        "2025-03-10",
        "2025-03-25",
        "2025-04-05"
    ],
    "Sales": [5000, 7000, 4500, 9000, 6000]
}

df = pd.DataFrame(data)
df

    Name  Order_Date  Sales
0  Rahul  2025-01-15   5000
1  Priya  2025-02-20   7000
2   Amit  2025-03-10   4500
3   Neha  2025-03-25   9000
4  Rohit  2025-04-05   6000

In [325]:
df.dtypes

Name          object
Order_Date    object
Sales          int64
dtype: object

In [326]:
#pd.to_datetime()
df["Order_Date"]=pd.to_datetime(df["Order_Date"])
df

    Name Order_Date  Sales
0  Rahul 2025-01-15   5000
1  Priya 2025-02-20   7000
2   Amit 2025-03-10   4500
3   Neha 2025-03-25   9000
4  Rohit 2025-04-05   6000

In [327]:
df.dtypes

Name                  object
Order_Date    datetime64[ns]
Sales                  int64
dtype: object

In [328]:
#extract year
df["Year"]=df["Order_Date"].dt.year
df

    Name Order_Date  Sales  Year
0  Rahul 2025-01-15   5000  2025
1  Priya 2025-02-20   7000  2025
2   Amit 2025-03-10   4500  2025
3   Neha 2025-03-25   9000  2025
4  Rohit 2025-04-05   6000  2025

In [329]:
#extract month
df["Month"]=df["Order_Date"].dt.month
df

    Name Order_Date  Sales  Year  Month
0  Rahul 2025-01-15   5000  2025      1
1  Priya 2025-02-20   7000  2025      2
2   Amit 2025-03-10   4500  2025      3
3   Neha 2025-03-25   9000  2025      3
4  Rohit 2025-04-05   6000  2025      4

In [330]:
#month name
df["Month_Name"]=df["Order_Date"].dt.month_name()
df

    Name Order_Date  Sales  Year  Month Month_Name
0  Rahul 2025-01-15   5000  2025      1    January
1  Priya 2025-02-20   7000  2025      2   February
2   Amit 2025-03-10   4500  2025      3      March
3   Neha 2025-03-25   9000  2025      3      March
4  Rohit 2025-04-05   6000  2025      4      April

In [331]:
#extract day
df["Day"]=df["Order_Date"].dt.day
df

    Name Order_Date  Sales  Year  Month Month_Name  Day
0  Rahul 2025-01-15   5000  2025      1    January   15
1  Priya 2025-02-20   7000  2025      2   February   20
2   Amit 2025-03-10   4500  2025      3      March   10
3   Neha 2025-03-25   9000  2025      3      March   25
4  Rohit 2025-04-05   6000  2025      4      April    5

In [332]:
#day of the week
df["Day_Name"]=df["Order_Date"].dt.day_name()
df

    Name Order_Date  Sales  Year  Month Month_Name  Day   Day_Name
0  Rahul 2025-01-15   5000  2025      1    January   15  Wednesday
1  Priya 2025-02-20   7000  2025      2   February   20   Thursday
2   Amit 2025-03-10   4500  2025      3      March   10     Monday
3   Neha 2025-03-25   9000  2025      3      March   25    Tuesday
4  Rohit 2025-04-05   6000  2025      4      April    5   Saturday

In [333]:
#weekday
df["Weekday"]=df["Order_Date"].dt.weekday
df

    Name Order_Date  Sales  Year  Month Month_Name  Day   Day_Name  Weekday
0  Rahul 2025-01-15   5000  2025      1    January   15  Wednesday        2
1  Priya 2025-02-20   7000  2025      2   February   20   Thursday        3
2   Amit 2025-03-10   4500  2025      3      March   10     Monday        0
3   Neha 2025-03-25   9000  2025      3      March   25    Tuesday        1
4  Rohit 2025-04-05   6000  2025      4      April    5   Saturday        5

In [334]:
#quarter
df["Quarter"]=df["Order_Date"].dt.quarter
df

,Name,Order_Date,Sales,Year,Month,Month_Name,Day,Day_Name,Weekday,Quarter
0,Rahul,2025-01-15,5000,2025,1,January,15,Wednesday,2,1
1,Priya,2025-02-20,7000,2025,2,February,20,Thursday,3,1
2,Amit,2025-03-10,4500,2025,3,March,10,Monday,0,1
3,Neha,2025-03-25,9000,2025,3,March,25,Tuesday,1,1
4,Rohit,2025-04-05,6000,2025,4,April,5,Saturday,5,2

In [335]:
#start/end of the month 
df["Month_Start"]=df["Order_Date"].dt.to_period("M").dt.start_time
df

,Name,Order_Date,Sales,Year,Month,Month_Name,Day,Day_Name,Weekday,Quarter,Month_Start
0,Rahul,2025-01-15,5000,2025,1,January,15,Wednesday,2,1,2025-01-01
1,Priya,2025-02-20,7000,2025,2,February,20,Thursday,3,1,2025-02-01
2,Amit,2025-03-10,4500,2025,3,March,10,Monday,0,1,2025-03-01
3,Neha,2025-03-25,9000,2025,3,March,25,Tuesday,1,1,2025-03-01
4,Rohit,2025-04-05,6000,2025,4,April,5,Saturday,5,2,2025-04-01

In [336]:
df["Month_End"] = df["Order_Date"].dt.to_period("M").dt.end_time
df

,Name,Order_Date,Sales,Year,Month,Month_Name,Day,Day_Name,Weekday,Quarter,Month_Start,Month_End
0,Rahul,2025-01-15,5000,2025,1,January,15,Wednesday,2,1,2025-01-01,2025-01-31 23:59:59.999999999
1,Priya,2025-02-20,7000,2025,2,February,20,Thursday,3,1,2025-02-01,2025-02-28 23:59:59.999999999
2,Amit,2025-03-10,4500,2025,3,March,10,Monday,0,1,2025-03-01,2025-03-31 23:59:59.999999999
3,Neha,2025-03-25,9000,2025,3,March,25,Tuesday,1,1,2025-03-01,2025-03-31 23:59:59.999999999
4,Rohit,2025-04-05,6000,2025,4,April,5,Saturday,5,2,2025-04-01,2025-04-30 23:59:59.999999999

In [337]:
#Find orders after March 1, 2025.
df[df["Order_Date"] > "2025-03-01"]

,Name,Order_Date,Sales,Year,Month,Month_Name,Day,Day_Name,Weekday,Quarter,Month_Start,Month_End
2,Amit,2025-03-10,4500,2025,3,March,10,Monday,0,1,2025-03-01,2025-03-31 23:59:59.999999999
3,Neha,2025-03-25,9000,2025,3,March,25,Tuesday,1,1,2025-03-01,2025-03-31 23:59:59.999999999
4,Rohit,2025-04-05,6000,2025,4,April,5,Saturday,5,2,2025-04-01,2025-04-30 23:59:59.999999999

In [338]:
#Find orders between March 1 and March 31.
df[
(df["Order_Date"]>="2025-03-01") &
(df["Order_Date"]<="2025-03-31")
]

,Name,Order_Date,Sales,Year,Month,Month_Name,Day,Day_Name,Weekday,Quarter,Month_Start,Month_End
2,Amit,2025-03-10,4500,2025,3,March,10,Monday,0,1,2025-03-01,2025-03-31 23:59:59.999999999
3,Neha,2025-03-25,9000,2025,3,March,25,Tuesday,1,1,2025-03-01,2025-03-31 23:59:59.999999999

In [339]:
#.between()
df[
df["Order_Date"].between(
    "2025-03-01",
    "2025-03-31"
)]

,Name,Order_Date,Sales,Year,Month,Month_Name,Day,Day_Name,Weekday,Quarter,Month_Start,Month_End
2,Amit,2025-03-10,4500,2025,3,March,10,Monday,0,1,2025-03-01,2025-03-31 23:59:59.999999999
3,Neha,2025-03-25,9000,2025,3,March,25,Tuesday,1,1,2025-03-01,2025-03-31 23:59:59.999999999

In [340]:
#Date difference
data = {
    "Employee": ["Rahul", "Priya", "Amit"],
    "Joining_Date": [
        "2020-01-10",
        "2021-06-15",
        "2019-03-20"
    ]
}

employees = pd.DataFrame(data)

employees["Joining_Date"] = pd.to_datetime(
    employees["Joining_Date"]
)
employees

  Employee Joining_Date
0    Rahul   2020-01-10
1    Priya   2021-06-15
2     Amit   2019-03-20

In [341]:
employees.dtypes

Employee                object
Joining_Date    datetime64[ns]
dtype: object

In [342]:
'''How long has each employee been with the company?

We can subtract dates.'''

today=pd.Timestamp("2025-09-23")

employees["Day_Worked"]=(today-employees["Joining_Date"])
employees

  Employee Joining_Date Day_Worked
0    Rahul   2020-01-10  2083 days
1    Priya   2021-06-15  1561 days
2     Amit   2019-03-20  2379 days

In [343]:
employees["Day_Worked"]=(
    today-employees["Joining_Date"]).dt.days
employees

  Employee Joining_Date  Day_Worked
0    Rahul   2020-01-10        2083
1    Priya   2021-06-15        1561
2     Amit   2019-03-20        2379

In [344]:
#Calculate Approximate Years
employees["Years_Worked"]=(
    employees["Day_Worked"]/365
)
employees

  Employee Joining_Date  Day_Worked  Years_Worked
0    Rahul   2020-01-10        2083      5.706849
1    Priya   2021-06-15        1561      4.276712
2     Amit   2019-03-20        2379      6.517808

In [345]:
#Difference Between Two Date Column
data = {
    "Order_Date": [
        "2025-01-01",
        "2025-02-10",
        "2025-03-05"
    ],
    "Delivery_Date": [
        "2025-01-05",
        "2025-02-15",
        "2025-03-12"
    ]
}

orders = pd.DataFrame(data)

orders["Order_Date"] = pd.to_datetime(orders["Order_Date"])
orders["Delivery_Date"] = pd.to_datetime(orders["Delivery_Date"])

In [346]:
#How many days did each order take to deliver?
orders["Delhivery_time"]=(orders["Delivery_Date"]-orders["Order_Date"]).dt.days
orders

  Order_Date Delivery_Date  Delhivery_time
0 2025-01-01    2025-01-05               4
1 2025-02-10    2025-02-15               5
2 2025-03-05    2025-03-12               7

In [347]:
#timedelta -represents a duration 
pd.Timedelta(days=10)

Timedelta('10 days 00:00:00')

In [348]:
#How much did we sell in each month?
df["Year"]=df["Order_Date"].dt.year
df["Month"]=df["Order_Date"].dt.month
df.groupby(["Year","Month"])["Sales"].sum()

Year  Month
2025  1         5000
      2         7000
      3        13500
      4         6000
Name: Sales, dtype: int64

In [349]:
#Find total sales by month.
df.groupby(
    df["Order_Date"].dt.month
)["Sales"].sum()

Order_Date
1     5000
2     7000
3    13500
4     6000
Name: Sales, dtype: int64

In [350]:
#resample()
df.set_index("Order_Date")

,Name,Sales,Year,Month,Month_Name,Day,Day_Name,Weekday,Quarter,Month_Start,Month_End
Order_Date,,,,,,,,,,,
2025-01-15,Rahul,5000,2025,1,January,15,Wednesday,2,1,2025-01-01,2025-01-31 23:59:59.999999999
2025-02-20,Priya,7000,2025,2,February,20,Thursday,3,1,2025-02-01,2025-02-28 23:59:59.999999999
2025-03-10,Amit,4500,2025,3,March,10,Monday,0,1,2025-03-01,2025-03-31 23:59:59.999999999
2025-03-25,Neha,9000,2025,3,March,25,Tuesday,1,1,2025-03-01,2025-03-31 23:59:59.999999999
2025-04-05,Rohit,6000,2025,4,April,5,Saturday,5,2,2025-04-01,2025-04-30 23:59:59.999999999

In [351]:
import pandas as pd

data = {
    "Order_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Customer": [
        "Rahul", "Priya", "Amit", "Neha", "Rohit",
        "Sneha", "Vikas", "Pooja", "Karan", "Anjali"
    ],
    "Order_Date": [
        "2025-01-15",
        "2025-01-20",
        "2025-02-10",
        "2025-02-25",
        "2025-03-05",
        "2025-03-18",
        "2025-04-10",
        "2025-04-22",
        "2025-05-15",
        "2025-05-28"
    ],
    "Sales": [
        5000, 7000, 4500, 9000, 6000,
        8000, 5500, 7500, 6500, 8500
    ]
}

df = pd.DataFrame(data)
df

   Order_ID Customer  Order_Date  Sales
0       101    Rahul  2025-01-15   5000
1       102    Priya  2025-01-20   7000
2       103     Amit  2025-02-10   4500
3       104     Neha  2025-02-25   9000
4       105    Rohit  2025-03-05   6000
5       106    Sneha  2025-03-18   8000
6       107    Vikas  2025-04-10   5500
7       108    Pooja  2025-04-22   7500
8       109    Karan  2025-05-15   6500
9       110   Anjali  2025-05-28   8500

In [352]:
df.dtypes

Order_ID       int64
Customer      object
Order_Date    object
Sales          int64
dtype: object

In [353]:
df["Order_Date"]=pd.to_datetime(df["Order_Date"])

In [354]:
df

   Order_ID Customer Order_Date  Sales
0       101    Rahul 2025-01-15   5000
1       102    Priya 2025-01-20   7000
2       103     Amit 2025-02-10   4500
3       104     Neha 2025-02-25   9000
4       105    Rohit 2025-03-05   6000
5       106    Sneha 2025-03-18   8000
6       107    Vikas 2025-04-10   5500
7       108    Pooja 2025-04-22   7500
8       109    Karan 2025-05-15   6500
9       110   Anjali 2025-05-28   8500

In [355]:
df.dtypes

Order_ID               int64
Customer              object
Order_Date    datetime64[ns]
Sales                  int64
dtype: object

In [357]:
#Q1. Extract the year from Order_Date.
df["Year"]=df["Order_Date"].dt.year
df

   Order_ID Customer Order_Date  Sales  Year
0       101    Rahul 2025-01-15   5000  2025
1       102    Priya 2025-01-20   7000  2025
2       103     Amit 2025-02-10   4500  2025
3       104     Neha 2025-02-25   9000  2025
4       105    Rohit 2025-03-05   6000  2025
5       106    Sneha 2025-03-18   8000  2025
6       107    Vikas 2025-04-10   5500  2025
7       108    Pooja 2025-04-22   7500  2025
8       109    Karan 2025-05-15   6500  2025
9       110   Anjali 2025-05-28   8500  2025

In [359]:
#Q2. Extract the month number.
df["Month"]=df["Order_Date"].dt.month
df

   Order_ID Customer Order_Date  Sales  Year  Month
0       101    Rahul 2025-01-15   5000  2025      1
1       102    Priya 2025-01-20   7000  2025      1
2       103     Amit 2025-02-10   4500  2025      2
3       104     Neha 2025-02-25   9000  2025      2
4       105    Rohit 2025-03-05   6000  2025      3
5       106    Sneha 2025-03-18   8000  2025      3
6       107    Vikas 2025-04-10   5500  2025      4
7       108    Pooja 2025-04-22   7500  2025      4
8       109    Karan 2025-05-15   6500  2025      5
9       110   Anjali 2025-05-28   8500  2025      5

In [ ]:
Q1. Extract the year from Order_Date.

Q2. Extract the month number.

Q3. Extract the month name.

Q4. Extract the day.

Q5. Extract the day name.

Q6. Extract the quarter.

Q7. Find all orders placed after 2025-03-01.

In [363]:
#Q4. Extract the day
df["Day"]=df["Order_Date"].dt.day
df

   Order_ID Customer Order_Date  Sales  Year  Month  Day
0       101    Rahul 2025-01-15   5000  2025      1   15
1       102    Priya 2025-01-20   7000  2025      1   20
2       103     Amit 2025-02-10   4500  2025      2   10
3       104     Neha 2025-02-25   9000  2025      2   25
4       105    Rohit 2025-03-05   6000  2025      3    5
5       106    Sneha 2025-03-18   8000  2025      3   18
6       107    Vikas 2025-04-10   5500  2025      4   10
7       108    Pooja 2025-04-22   7500  2025      4   22
8       109    Karan 2025-05-15   6500  2025      5   15
9       110   Anjali 2025-05-28   8500  2025      5   28

In [371]:
#Q5. Extract the day name.
df["Day_Name"]=df["Order_Date"].dt.day_name()
df

   Order_ID Customer Order_Date  Sales  Year  Month  Day   Day_Name
0       101    Rahul 2025-01-15   5000  2025      1   15  Wednesday
1       102    Priya 2025-01-20   7000  2025      1   20     Monday
2       103     Amit 2025-02-10   4500  2025      2   10     Monday
3       104     Neha 2025-02-25   9000  2025      2   25    Tuesday
4       105    Rohit 2025-03-05   6000  2025      3    5  Wednesday
5       106    Sneha 2025-03-18   8000  2025      3   18    Tuesday
6       107    Vikas 2025-04-10   5500  2025      4   10   Thursday
7       108    Pooja 2025-04-22   7500  2025      4   22    Tuesday
8       109    Karan 2025-05-15   6500  2025      5   15   Thursday
9       110   Anjali 2025-05-28   8500  2025      5   28  Wednesday

In [375]:
#Q6. Extract the quarter.
df["Quarter"]=df["Order_Date"].dt.quarter
df

   Order_ID Customer Order_Date  Sales  Year  Month  Day   Day_Name  Quarter
0       101    Rahul 2025-01-15   5000  2025      1   15  Wednesday        1
1       102    Priya 2025-01-20   7000  2025      1   20     Monday        1
2       103     Amit 2025-02-10   4500  2025      2   10     Monday        1
3       104     Neha 2025-02-25   9000  2025      2   25    Tuesday        1
4       105    Rohit 2025-03-05   6000  2025      3    5  Wednesday        1
5       106    Sneha 2025-03-18   8000  2025      3   18    Tuesday        1
6       107    Vikas 2025-04-10   5500  2025      4   10   Thursday        2
7       108    Pooja 2025-04-22   7500  2025      4   22    Tuesday        2
8       109    Karan 2025-05-15   6500  2025      5   15   Thursday        2
9       110   Anjali 2025-05-28   8500  2025      5   28  Wednesday        2

In [389]:
#Q7. Find all orders placed after 2025-03-01.
df[df["Order_Date"] >="2025-03-01"]

,Order_ID,Customer,Order_Date,Sales,Year,Month,Day,Day_Name,Quarter,order_placed
4,105,Rohit,2025-03-05,6000,2025,3,5,Wednesday,1,True
5,106,Sneha,2025-03-18,8000,2025,3,18,Tuesday,1,True
6,107,Vikas,2025-04-10,5500,2025,4,10,Thursday,2,True
7,108,Pooja,2025-04-22,7500,2025,4,22,Tuesday,2,True
8,109,Karan,2025-05-15,6500,2025,5,15,Thursday,2,True
9,110,Anjali,2025-05-28,8500,2025,5,28,Wednesday,2,True

In [ ]:
Q8. Find all orders placed during March 2025.

Q9. Find total sales for each month.

Q10. Find total sales for each year.

Q11. Find average sales for each month.

Q12. Find the month with the highest total sales.

Q13. Find the month with the lowest total sales.

Q14. Find total sales for each quarter.

In [397]:
#Q8. Find all orders placed during March 2025.
df[df["Order_Date"].between(
    "2025-03-01",
    "2025-03-31"
)]

,Order_ID,Customer,Order_Date,Sales,Year,Month,Day,Day_Name,Quarter,order_placed
4,105,Rohit,2025-03-05,6000,2025,3,5,Wednesday,1,True
5,106,Sneha,2025-03-18,8000,2025,3,18,Tuesday,1,True

In [407]:
#Q9. Find total sales for each month.
df.groupby(
    df["Order_Date"].dt.month
)["Sales"].sum()

Order_Date
1    12000
2    13500
3    14000
4    13000
5    15000
Name: Sales, dtype: int64

In [409]:
#Q11. Find average sales for each month.
df.groupby(
    df["Order_Date"].dt.month
)["Sales"].mean()

Order_Date
1    6000.0
2    6750.0
3    7000.0
4    6500.0
5    7500.0
Name: Sales, dtype: float64

In [411]:
#Q12. Find the month with the highest total sales.
df.groupby(
    df["Order_Date"].dt.month
)["Sales"].sum().sort_values(ascending=False)

Order_Date
5    15000
3    14000
2    13500
4    13000
1    12000
Name: Sales, dtype: int64

In [413]:
#Q13. Find the month with the lowest total sales.
df.groupby(
    df["Order_Date"].dt.month
)["Sales"].sum().sort_values(ascending=True)

Order_Date
1    12000
4    13000
2    13500
3    14000
5    15000
Name: Sales, dtype: int64

In [415]:
#Q14. Find total sales for each quarter.
df.groupby(
    df["Order_Date"].dt.quarter
)["Sales"].sum()

Order_Date
1    39500
2    28000
Name: Sales, dtype: int64

In [419]:
deliveries = pd.DataFrame({
    "Order_ID": [101, 102, 103, 104, 105],
    "Order_Date": [
        "2025-01-01",
        "2025-01-10",
        "2025-02-05",
        "2025-02-20",
        "2025-03-01"
    ],
    "Delivery_Date": [
        "2025-01-05",
        "2025-01-15",
        "2025-02-08",
        "2025-02-25",
        "2025-03-10"
    ]
})
deliveries

   Order_ID  Order_Date Delivery_Date
0       101  2025-01-01    2025-01-05
1       102  2025-01-10    2025-01-15
2       103  2025-02-05    2025-02-08
3       104  2025-02-20    2025-02-25
4       105  2025-03-01    2025-03-10

In [421]:
deliveries.dtypes

Order_ID          int64
Order_Date       object
Delivery_Date    object
dtype: object

In [ ]:
Q15. Convert both columns to datetime.

Q16. Calculate Delivery_Days.

Q17. Find the average delivery time.

Q18. Find the order with the longest delivery time.

Q19. Find orders delivered within 5 days.

In [437]:
#Q15. Convert both columns to datetime.
deliveries["Order_Date"]=pd.to_datetime(deliveries["Order_Date"])
deliveries["Delivery_Date"]=pd.to_datetime(deliveries["Delivery_Date"])

In [439]:
deliveries

   Order_ID Order_Date Delivery_Date
0       101 2025-01-01    2025-01-05
1       102 2025-01-10    2025-01-15
2       103 2025-02-05    2025-02-08
3       104 2025-02-20    2025-02-25
4       105 2025-03-01    2025-03-10

In [441]:
deliveries.dtypes

Order_ID                  int64
Order_Date       datetime64[ns]
Delivery_Date    datetime64[ns]
dtype: object

In [451]:
#Q16. Calculate Delivery_Days.
deliveries["Delivery_time"]=deliveries["Delivery_Date"]-deliveries["Order_Date"]
deliveries

   Order_ID Order_Date Delivery_Date Delivery_time
0       101 2025-01-01    2025-01-05        4 days
1       102 2025-01-10    2025-01-15        5 days
2       103 2025-02-05    2025-02-08        3 days
3       104 2025-02-20    2025-02-25        5 days
4       105 2025-03-01    2025-03-10        9 days

In [463]:
#Q17. Find the average delivery time.

deliveries["AVG_Delivery"]=deliveries["Delivery_time"].mean()
deliveries

   Order_ID Order_Date Delivery_Date Delivery_time    AVG_Delivery
0       101 2025-01-01    2025-01-05        4 days 5 days 04:48:00
1       102 2025-01-10    2025-01-15        5 days 5 days 04:48:00
2       103 2025-02-05    2025-02-08        3 days 5 days 04:48:00
3       104 2025-02-20    2025-02-25        5 days 5 days 04:48:00
4       105 2025-03-01    2025-03-10        9 days 5 days 04:48:00

In [469]:
#Q18. Find the order with the longest delivery time.
deliveries["Longest_delivery_time"]=deliveries["Delivery_time"].max()
deliveries

,Order_ID,Order_Date,Delivery_Date,Delivery_time,AVG_Delivery,Longest_delivery_time
0,101,2025-01-01,2025-01-05,4 days,5 days 04:48:00,9 days
1,102,2025-01-10,2025-01-15,5 days,5 days 04:48:00,9 days
2,103,2025-02-05,2025-02-08,3 days,5 days 04:48:00,9 days
3,104,2025-02-20,2025-02-25,5 days,5 days 04:48:00,9 days
4,105,2025-03-01,2025-03-10,9 days,5 days 04:48:00,9 days

In [473]:
#Q19. Find orders delivered within 5 days.
len(deliveries[deliveries["Delivery_time"] <=pd.Timedelta(days=5)])

4

In [ ]:
Q20. Find total sales by Year + Month.

Q21. Find the month having the highest total sales.

Q22. Find average sales by quarter.

Q23. Find the day of the week generating the highest total sales.

Q24. Find the top 3 highest-sales orders placed after March 1, 2025.

In [477]:
#Q20. Find total sales by Year + Month.
df.groupby(["Year","Month"])["Sales"].sum()

Year  Month
2025  1        12000
      2        13500
      3        14000
      4        13000
      5        15000
Name: Sales, dtype: int64

In [479]:
#Q21. Find the month having the highest total sales.
df.groupby(
    df["Order_Date"].dt.month
)["Sales"].sum().max()

15000

In [481]:
#Q22. Find average sales by quarter.
df.groupby(
    df["Order_Date"].dt.quarter
)["Sales"].mean()

Order_Date
1    6583.333333
2    7000.000000
Name: Sales, dtype: float64

In [493]:
#23. Find the day of the week generating the highest total sales.
df.groupby(
    df["Order_Date"].dt.day_name()
)["Sales"].sum().idxmax()

'Tuesday'

In [523]:
#Q24. Find the top 3 highest-sales orders placed after March 1, 2025.
march_filter=df[df["Order_Date"]>"2025-03-01"]
top3=march_filter.sort_values(by="Sales",ascending=False).head(3)
top3

,Order_ID,Customer,Order_Date,Sales,Year,Month,Day,Day_Name,Quarter,order_placed
9,110,Anjali,2025-05-28,8500,2025,5,28,Wednesday,2,True
5,106,Sneha,2025-03-18,8000,2025,3,18,Tuesday,1,True
7,108,Pooja,2025-04-22,7500,2025,4,22,Tuesday,2,True