In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit", "Neha"],
    "Age": [25, 32, 28, 41],
    "Salary": [50000, 65000, 45000, 80000]
})
df

    Name  Age  Salary
0  Rahul   25   50000
1  Priya   32   65000
2   Amit   28   45000
3   Neha   41   80000

In [15]:
#map()
df["Age_Catagory"]=df["Age"].map(
    lambda x :"Young"if x<30 else "Adult"
)
df

    Name  Age  Salary Age_Category Age_Catagory
0  Rahul   25   50000        Young        Young
1  Priya   32   65000        Adult        Adult
2   Amit   28   45000        Young        Young
3   Neha   41   80000        Adult        Adult

In [19]:
#map() with dictionary
df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit", "Neha"],
    "Department": ["IT", "HR", "IT", "Finance"]
})
df

    Name Department
0  Rahul         IT
1  Priya         HR
2   Amit         IT
3   Neha    Finance

In [23]:
dept_code = {
    "IT": 101,
    "HR": 102,
    "Finance": 103
}
dept_code

{'IT': 101, 'HR': 102, 'Finance': 103}

In [27]:
df["Department_Code"]=df["Department"].map(dept_code)
df

    Name Department  Department_Code
0  Rahul         IT              101
1  Priya         HR              102
2   Amit         IT              101
3   Neha    Finance              103

In [35]:
#map() with a function
df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit", "Neha"],
    "Age": [25, 32, 28, 41],
    "Salary": [50000, 65000, 45000, 80000]
})
def salary_category(salary):
    if salary>=70000:
        return "High"
    elif salary >=50000:
        return "Medium"
    else:
        return "Low"

In [39]:
df["Salary_Category"]=df["Salary"].map(salary_category)
df

    Name  Age  Salary Salary_Category
0  Rahul   25   50000          Medium
1  Priya   32   65000          Medium
2   Amit   28   45000             Low
3   Neha   41   80000            High

In [41]:
#apply()
def salary_category(salary):
    if salary>=70000:
        return "High"
    elif salary>=50000:
        return "Medium"
    else:
        return "Low"

In [45]:
df["Salary_Category"]=df["Salary"].apply(salary_category)
df

    Name  Age  Salary Salary_Category
0  Rahul   25   50000          Medium
1  Priya   32   65000          Medium
2   Amit   28   45000             Low
3   Neha   41   80000            High

In [47]:
df["Salary"].apply(
    lambda x :"High"if x>=70000 else "Low"
)

0     Low
1     Low
2     Low
3    High
Name: Salary, dtype: object

In [53]:
#Vectorization
df["Salary_Doubled"]=df["Salary"]*2
df

    Name  Age  Salary Salary_Category  Salary_Doubled
0  Rahul   25   50000          Medium          100000
1  Priya   32   65000          Medium          130000
2   Amit   28   45000             Low           90000
3   Neha   41   80000            High          160000

In [59]:
#conditional transformations
import numpy as np
df["Salary_cat"]=np.where(
    df["Salary"]>=60000,
    "High",
    "Low"
)
df

    Name  Age  Salary Salary_Category  Salary_Doubled Salary_cat
0  Rahul   25   50000          Medium          100000        Low
1  Priya   32   65000          Medium          130000       High
2   Amit   28   45000             Low           90000        Low
3   Neha   41   80000            High          160000       High

In [65]:
#multiple conditions 
'''Age < 30       → Young
30–39          → Adult
40+            → Senior'''

def age_cat(age):
    if age<30:
        return "Young"
    elif age<40:
        return "Adult"
    else:
        return "Senior"

In [67]:
df["Age"].apply(age_cat)

0     Young
1     Adult
2     Young
3    Senior
Name: Age, dtype: object

In [69]:
#apply() on rows
df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit"],
    "Salary": [50000, 60000, 70000],
    "Experience": [2, 5, 7]
})
df

    Name  Salary  Experience
0  Rahul   50000           2
1  Priya   60000           5
2   Amit   70000           7

In [71]:
def sal_bonus(row):
    if row["Experience"]>=5:
        return row["Salary"]*0.10
    else:
        return row["Salary"]*0.05

In [79]:
df["Salary_bonus"]=df.apply(sal_bonus,axis=1)
df

    Name  Salary  Experience  Salary_bonus
0  Rahul   50000           2        2500.0
1  Priya   60000           5        6000.0
2   Amit   70000           7        7000.0

In [81]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Rahul", "Priya", "Amit", "Neha", "Rohit",
             "Sneha", "Vikas", "Pooja"],
    
    "Age": [25, 32, 28, 41, 24, 35, 29, 45],
    
    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "IT", "Finance", "HR"
    ],
    
    "Salary": [
        50000, 65000, 45000, 80000,
        40000, 70000, 60000, 55000
    ],
    
    "Experience": [
        2, 6, 3, 10,
        1, 7, 5, 8
    ]
}

df = pd.DataFrame(data)
df

    Name  Age Department  Salary  Experience
0  Rahul   25         IT   50000           2
1  Priya   32         HR   65000           6
2   Amit   28         IT   45000           3
3   Neha   41    Finance   80000          10
4  Rohit   24         HR   40000           1
5  Sneha   35         IT   70000           7
6  Vikas   29    Finance   60000           5
7  Pooja   45         HR   55000           8

In [ ]:
Q1

Create a Salary_Double column by multiplying Salary by 2.

Q2

Create an Annual_Salary column.

Assume Salary is monthly.

Annual Salary = Salary × 12
Q3

Create an Experience_Months column.

Experience × 12
Q4

Create an Age_Next_Year column.

Age + 1
Q5

Create a Department_Code using:

IT       → 101
HR       → 102
Finance  → 103

Use .map().

In [87]:
#Q1 Create a Salary_Double column by multiplying Salary by 2
df["Salary_Doubled"]=df["Salary"]*2
df

    Name  Age Department  Salary  Experience  Salary_Doubled
0  Rahul   25         IT   50000           2          100000
1  Priya   32         HR   65000           6          130000
2   Amit   28         IT   45000           3           90000
3   Neha   41    Finance   80000          10          160000
4  Rohit   24         HR   40000           1           80000
5  Sneha   35         IT   70000           7          140000
6  Vikas   29    Finance   60000           5          120000
7  Pooja   45         HR   55000           8          110000

In [91]:
'''Q2

Create an Annual_Salary column.

Assume Salary is monthly.

Annual Salary = Salary × 12'''

df["Annual_Salary"]=df["Salary"]*12
df

    Name  Age Department  Salary  Experience  Salary_Doubled  Annual_Salary
0  Rahul   25         IT   50000           2          100000         600000
1  Priya   32         HR   65000           6          130000         780000
2   Amit   28         IT   45000           3           90000         540000
3   Neha   41    Finance   80000          10          160000         960000
4  Rohit   24         HR   40000           1           80000         480000
5  Sneha   35         IT   70000           7          140000         840000
6  Vikas   29    Finance   60000           5          120000         720000
7  Pooja   45         HR   55000           8          110000         660000

In [95]:
'''Q3

Create an Experience_Months column.

Experience × 12'''

df["Experience_Months"]=df["Experience"]*12
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months
0,Rahul,25,IT,50000,2,100000,600000,24
1,Priya,32,HR,65000,6,130000,780000,72
2,Amit,28,IT,45000,3,90000,540000,36
3,Neha,41,Finance,80000,10,160000,960000,120
4,Rohit,24,HR,40000,1,80000,480000,12
5,Sneha,35,IT,70000,7,140000,840000,84
6,Vikas,29,Finance,60000,5,120000,720000,60
7,Pooja,45,HR,55000,8,110000,660000,96

In [99]:
'''Q4

Create an Age_Next_Year column.

Age + 1'''
df["Age_Next_Year"]=df["Age"]+1
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year
0,Rahul,25,IT,50000,2,100000,600000,24,26
1,Priya,32,HR,65000,6,130000,780000,72,33
2,Amit,28,IT,45000,3,90000,540000,36,29
3,Neha,41,Finance,80000,10,160000,960000,120,42
4,Rohit,24,HR,40000,1,80000,480000,12,25
5,Sneha,35,IT,70000,7,140000,840000,84,36
6,Vikas,29,Finance,60000,5,120000,720000,60,30
7,Pooja,45,HR,55000,8,110000,660000,96,46

In [113]:
'''Q5

Create a Department_Code using:

IT       → 101
HR       → 102
Finance  → 103'''

data={
    "IT":101,
    "HR":102,
    "Finance":103
}
df["Department_Code"]=df["Department"].map(data)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code
0,Rahul,25,IT,50000,2,100000,600000,24,26,101
1,Priya,32,HR,65000,6,130000,780000,72,33,102
2,Amit,28,IT,45000,3,90000,540000,36,29,101
3,Neha,41,Finance,80000,10,160000,960000,120,42,103
4,Rohit,24,HR,40000,1,80000,480000,12,25,102
5,Sneha,35,IT,70000,7,140000,840000,84,36,101
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103
7,Pooja,45,HR,55000,8,110000,660000,96,46,102

In [ ]:
Q6

Create Age_Group:

Age < 30       → Young
30–39          → Adult
40+            → Senior

Use .apply().

Q7

Create Salary_Category:

Salary < 50000      → Low
50000–69999         → Medium
70000+              → High
Q8

Create Experience_Level:

Experience < 3      → Beginner
3–6                 → Intermediate
7+                  → Experienced
Q9

Create a Tax column:

Salary >= 70000 → 20% tax
Salary < 70000  → 10% tax
Q10

Create:

Salary_After_Tax

In [121]:
'''Q6

Create Age_Group:

Age < 30       → Young
30–39          → Adult
40+            → Senior'''

def age_cat(age):
    if age<30:
        return "Young"
    elif age <40:
        return "Adult"
    else:
        return "Senior"

In [125]:
df["Age_Group"]=df["Age"].apply(age_cat)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,Age_Group
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,Young
1,Priya,32,HR,65000,6,130000,780000,72,33,102,Adult
2,Amit,28,IT,45000,3,90000,540000,36,29,101,Young
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,Senior
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,Young
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,Adult
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,Young
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,Senior

In [133]:
'''Q7

Create Salary_Category:

Salary < 50000      → Low
50000–69999         → Medium
70000+              → High'''

def sal_cat(salary):
    if salary<50000:
        return "Low"
    elif salary<70000:
        return "Medium"
    else:
        return "High"

In [135]:
df["Salary_Category"]=df["Salary"].apply(sal_cat)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,Age_Group,Salary_Category
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,Young,Medium
1,Priya,32,HR,65000,6,130000,780000,72,33,102,Adult,Medium
2,Amit,28,IT,45000,3,90000,540000,36,29,101,Young,Low
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,Senior,High
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,Young,Low
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,Adult,High
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,Young,Medium
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,Senior,Medium

In [137]:
'''Q8

Create Experience_Level:

Experience < 3      → Beginner
3–6                 → Intermediate
7+                  → Experienced'''

def exp_level(exp):
    if exp<3:
        return "Beiginner"
    elif exp<7:
        return "Intermediate"
    else:
        return "Experienced"

In [141]:
df["Experience_Level"]=df["Experience"].apply(exp_level)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,Age_Group,Salary_Category,Experience_Level
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,Young,Medium,Beiginner
1,Priya,32,HR,65000,6,130000,780000,72,33,102,Adult,Medium,Intermediate
2,Amit,28,IT,45000,3,90000,540000,36,29,101,Young,Low,Intermediate
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,Senior,High,Experienced
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,Young,Low,Beiginner
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,Adult,High,Experienced
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,Young,Medium,Intermediate
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,Senior,Medium,Experienced

In [186]:
'''Q9

Create a Tax column:

Salary >= 70000 → 20% tax
Salary < 70000  → 10% tax'''
import numpy as np

df["Tax"]=df["Salary"]* np.where(df["Salary"]>=70000 ,0.20,0.10)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,Age_Group,Salary_Category,Experience_Level,Tax
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,Young,Medium,Beiginner,5000.0
1,Priya,32,HR,65000,6,130000,780000,72,33,102,Adult,Medium,Intermediate,6500.0
2,Amit,28,IT,45000,3,90000,540000,36,29,101,Young,Low,Intermediate,4500.0
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,Senior,High,Experienced,16000.0
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,Young,Low,Beiginner,4000.0
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,Adult,High,Experienced,14000.0
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,Young,Medium,Intermediate,6000.0
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,Senior,Medium,Experienced,5500.0

In [207]:
'''Create:

Salary_After_Tax'''

tax=np.where(
    df["Salary"]>=70000 ,0.10,0.20
)
df["Salary_After_Tax"]=df["Salary"] *(1-tax)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,Age_Group,Salary_Category,Experience_Level,Tax,Salary_After_Tax
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,Young,Medium,Beiginner,5000.0,40000.0
1,Priya,32,HR,65000,6,130000,780000,72,33,102,Adult,Medium,Intermediate,6500.0,52000.0
2,Amit,28,IT,45000,3,90000,540000,36,29,101,Young,Low,Intermediate,4500.0,36000.0
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,Senior,High,Experienced,16000.0,72000.0
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,Young,Low,Beiginner,4000.0,32000.0
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,Adult,High,Experienced,14000.0,63000.0
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,Young,Medium,Intermediate,6000.0,48000.0
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,Senior,Medium,Experienced,5500.0,44000.0

In [ ]:
Q11

Give everyone a 10% salary increment.

Create:

New_Salary

Prefer vectorization.

Q12

Create:

Bonus

Rules:

Experience >= 7 → 15% of Salary
Experience < 7  → 10% of Salary
Q13

Create:

Promotion_Eligible

Rules:

Experience >= 5 → Yes
Otherwise       → No
Q14

Create:

Senior_Employee

Rules:

Age >= 35 → Yes
Otherwise → No
Q15

Create:

High_Earner

Rules:

Salary >= 70000 → Yes
Otherwise → No

In [215]:
'''Q11

Give everyone a 10% salary increment.

Create:

New_Salary

Prefer vectorization.'''

df["New_Salary"]=df["Salary"]*0.10
df["New_Salary"]=df["Salary"]+df["Salary"]*0.10
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,Age_Group,Salary_Category,Experience_Level,Tax,Salary_After_Tax,New_Salary
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,Young,Medium,Beiginner,5000.0,40000.0,55000.0
1,Priya,32,HR,65000,6,130000,780000,72,33,102,Adult,Medium,Intermediate,6500.0,52000.0,71500.0
2,Amit,28,IT,45000,3,90000,540000,36,29,101,Young,Low,Intermediate,4500.0,36000.0,49500.0
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,Senior,High,Experienced,16000.0,72000.0,88000.0
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,Young,Low,Beiginner,4000.0,32000.0,44000.0
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,Adult,High,Experienced,14000.0,63000.0,77000.0
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,Young,Medium,Intermediate,6000.0,48000.0,66000.0
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,Senior,Medium,Experienced,5500.0,44000.0,60500.0

In [217]:
'''Q12

Create:

Bonus

Rules:

Experience >= 7 → 15% of Salary
Experience < 7  → 10% of Salary'''

def bonus(row):
    if row["Experience"]>7:
        return row["Salary"]*0.10
    else:
        return row["Salary"]*0.20

In [223]:
df["Bonus"]=df.apply(bonus,axis=1)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,Age_Group,Salary_Category,Experience_Level,Tax,Salary_After_Tax,New_Salary,Bonus
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,Young,Medium,Beiginner,5000.0,40000.0,55000.0,10000.0
1,Priya,32,HR,65000,6,130000,780000,72,33,102,Adult,Medium,Intermediate,6500.0,52000.0,71500.0,13000.0
2,Amit,28,IT,45000,3,90000,540000,36,29,101,Young,Low,Intermediate,4500.0,36000.0,49500.0,9000.0
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,Senior,High,Experienced,16000.0,72000.0,88000.0,8000.0
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,Young,Low,Beiginner,4000.0,32000.0,44000.0,8000.0
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,Adult,High,Experienced,14000.0,63000.0,77000.0,14000.0
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,Young,Medium,Intermediate,6000.0,48000.0,66000.0,12000.0
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,Senior,Medium,Experienced,5500.0,44000.0,60500.0,5500.0

In [229]:
'''Q13

Create:

Promotion_Eligible

Rules:

Experience >= 5 → Yes
Otherwise       → No'''

def promo_eli(exp):
    if exp>=5:
        return "Yes"
    else:
        return "No"

In [233]:
df["Promotion_Eligible"]=df["Experience"].apply(promo_eli)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,Age_Group,Salary_Category,Experience_Level,Tax,Salary_After_Tax,New_Salary,Bonus,Promotion_Eligible
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,Young,Medium,Beiginner,5000.0,40000.0,55000.0,10000.0,No
1,Priya,32,HR,65000,6,130000,780000,72,33,102,Adult,Medium,Intermediate,6500.0,52000.0,71500.0,13000.0,Yes
2,Amit,28,IT,45000,3,90000,540000,36,29,101,Young,Low,Intermediate,4500.0,36000.0,49500.0,9000.0,No
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,Senior,High,Experienced,16000.0,72000.0,88000.0,8000.0,Yes
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,Young,Low,Beiginner,4000.0,32000.0,44000.0,8000.0,No
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,Adult,High,Experienced,14000.0,63000.0,77000.0,14000.0,Yes
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,Young,Medium,Intermediate,6000.0,48000.0,66000.0,12000.0,Yes
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,Senior,Medium,Experienced,5500.0,44000.0,60500.0,5500.0,Yes

In [237]:
'''Create:

Senior_Employee

Rules:

Age >= 35 → Yes
Otherwise → No'''
def senior_emp(sal):
    if sal>=35:
        return "Yes"
    else:
        return "No"

In [241]:
df["Senior_Employee"]=df["Age"].apply(senior_emp)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,Age_Group,Salary_Category,Experience_Level,Tax,Salary_After_Tax,New_Salary,Bonus,Promotion_Eligible,Senior_Employee
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,Young,Medium,Beiginner,5000.0,40000.0,55000.0,10000.0,No,No
1,Priya,32,HR,65000,6,130000,780000,72,33,102,Adult,Medium,Intermediate,6500.0,52000.0,71500.0,13000.0,Yes,No
2,Amit,28,IT,45000,3,90000,540000,36,29,101,Young,Low,Intermediate,4500.0,36000.0,49500.0,9000.0,No,No
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,Senior,High,Experienced,16000.0,72000.0,88000.0,8000.0,Yes,Yes
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,Young,Low,Beiginner,4000.0,32000.0,44000.0,8000.0,No,No
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,Adult,High,Experienced,14000.0,63000.0,77000.0,14000.0,Yes,Yes
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,Young,Medium,Intermediate,6000.0,48000.0,66000.0,12000.0,Yes,No
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,Senior,Medium,Experienced,5500.0,44000.0,60500.0,5500.0,Yes,Yes

In [243]:
'''Q15

Create:

High_Earner

Rules:

Salary >= 70000 → Yes
Otherwise → No'''

def high_earner(sal):
    if sal>=70000:
        return "Yes"
    else:
        "No"

In [247]:
df["High_Earner"]=df["Salary"].apply(high_earner)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,Age_Group,Salary_Category,Experience_Level,Tax,Salary_After_Tax,New_Salary,Bonus,Promotion_Eligible,Senior_Employee,High_Earner
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,Young,Medium,Beiginner,5000.0,40000.0,55000.0,10000.0,No,No,None
1,Priya,32,HR,65000,6,130000,780000,72,33,102,Adult,Medium,Intermediate,6500.0,52000.0,71500.0,13000.0,Yes,No,None
2,Amit,28,IT,45000,3,90000,540000,36,29,101,Young,Low,Intermediate,4500.0,36000.0,49500.0,9000.0,No,No,None
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,Senior,High,Experienced,16000.0,72000.0,88000.0,8000.0,Yes,Yes,Yes
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,Young,Low,Beiginner,4000.0,32000.0,44000.0,8000.0,No,No,None
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,Adult,High,Experienced,14000.0,63000.0,77000.0,14000.0,Yes,Yes,Yes
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,Young,Medium,Intermediate,6000.0,48000.0,66000.0,12000.0,Yes,No,None
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,Senior,Medium,Experienced,5500.0,44000.0,60500.0,5500.0,Yes,Yes,None

In [ ]:
Q16.Create Bonus using this rule:

Experience >= 5 AND Salary >= 60000
        → 15% bonus

Otherwise
        → 5% bonus

Use:

df.apply(..., axis=1)
Q17

Create Employee_Level:

Experience >= 7 → Senior
Experience >= 3 → Mid
Otherwise        → Junior
Q18

Create Risk_Category.

Rules:

Age > 40 AND Salary < 60000
    → High Risk

Age > 30 AND Salary < 60000
    → Medium Risk

Otherwise
    → Low Risk
Q19

Create:

Salary_Per_Year_Experience

Formula:

Salary / Experience

Handle the possibility of Experience = 0.

Q20

Create:

Employee_Score

Formula:

Salary / 10000 + Experience

In [285]:
'''Q16.Create Bonus using this rule:

Experience >= 5 AND Salary >= 60000
        → 15% bonus

Otherwise
        → 5% bonus'''

def bonus(row):
    if row["Experience"]>=5 and row["Salary"]>=60000:
        return row["Salary"]*0.15
    else:    
        return row["Salary"]*0.05

In [287]:
df["Bonus"]=df.apply(bonus,axis=1)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,Age_Group,Salary_Category,Experience_Level,Tax,Salary_After_Tax,New_Salary,Bonus,Promotion_Eligible,Senior_Employee,High_Earner
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,Young,Medium,Beiginner,5000.0,40000.0,55000.0,2500.0,No,No,None
1,Priya,32,HR,65000,6,130000,780000,72,33,102,Adult,Medium,Intermediate,6500.0,52000.0,71500.0,9750.0,Yes,No,None
2,Amit,28,IT,45000,3,90000,540000,36,29,101,Young,Low,Intermediate,4500.0,36000.0,49500.0,2250.0,No,No,None
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,Senior,High,Experienced,16000.0,72000.0,88000.0,12000.0,Yes,Yes,Yes
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,Young,Low,Beiginner,4000.0,32000.0,44000.0,2000.0,No,No,None
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,Adult,High,Experienced,14000.0,63000.0,77000.0,10500.0,Yes,Yes,Yes
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,Young,Medium,Intermediate,6000.0,48000.0,66000.0,9000.0,Yes,No,None
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,Senior,Medium,Experienced,5500.0,44000.0,60500.0,2750.0,Yes,Yes,None

In [289]:
'''Q17

Create Employee_Level:

Experience >= 7 → Senior
Experience >= 3 → Mid
Otherwise        → Junior'''

def emp_level(emp):
    if emp>=7:
        return "Senior"
    elif emp>=3:
        return "Mid"
    else:
        return "Junior"

In [293]:
df["Employee_Level"]=df["Experience"].apply(emp_level)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,...,Salary_Category,Experience_Level,Tax,Salary_After_Tax,New_Salary,Bonus,Promotion_Eligible,Senior_Employee,High_Earner,Employee_Level
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,...,Medium,Beiginner,5000.0,40000.0,55000.0,2500.0,No,No,None,Junior
1,Priya,32,HR,65000,6,130000,780000,72,33,102,...,Medium,Intermediate,6500.0,52000.0,71500.0,9750.0,Yes,No,None,Mid
2,Amit,28,IT,45000,3,90000,540000,36,29,101,...,Low,Intermediate,4500.0,36000.0,49500.0,2250.0,No,No,None,Mid
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,...,High,Experienced,16000.0,72000.0,88000.0,12000.0,Yes,Yes,Yes,Senior
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,...,Low,Beiginner,4000.0,32000.0,44000.0,2000.0,No,No,None,Junior
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,...,High,Experienced,14000.0,63000.0,77000.0,10500.0,Yes,Yes,Yes,Senior
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,...,Medium,Intermediate,6000.0,48000.0,66000.0,9000.0,Yes,No,None,Mid
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,...,Medium,Experienced,5500.0,44000.0,60500.0,2750.0,Yes,Yes,None,Senior

In [299]:
'''Q18

Create Risk_Category.

Rules:

Age > 40 AND Salary < 60000
    → High Risk

Age > 30 AND Salary < 60000
    → Medium Risk

Otherwise
    → Low Risk'''

def risk_category(age):
    if age["Age"]>40 and age["Salary"]<60000:
        return "High Risk"
    elif age["Age"]>30 and age["Salary"]<60000:
        return "Medium Risk"
    else:
        "Low Risk"

In [309]:
df["Risk_Category"]=df.apply(risk_category,axis=1)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,...,Experience_Level,Tax,Salary_After_Tax,New_Salary,Bonus,Promotion_Eligible,Senior_Employee,High_Earner,Employee_Level,Risk_Category
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,...,Beiginner,5000.0,40000.0,55000.0,2500.0,No,No,None,Junior,None
1,Priya,32,HR,65000,6,130000,780000,72,33,102,...,Intermediate,6500.0,52000.0,71500.0,9750.0,Yes,No,None,Mid,None
2,Amit,28,IT,45000,3,90000,540000,36,29,101,...,Intermediate,4500.0,36000.0,49500.0,2250.0,No,No,None,Mid,None
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,...,Experienced,16000.0,72000.0,88000.0,12000.0,Yes,Yes,Yes,Senior,None
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,...,Beiginner,4000.0,32000.0,44000.0,2000.0,No,No,None,Junior,None
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,...,Experienced,14000.0,63000.0,77000.0,10500.0,Yes,Yes,Yes,Senior,None
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,...,Intermediate,6000.0,48000.0,66000.0,9000.0,Yes,No,None,Mid,None
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,...,Experienced,5500.0,44000.0,60500.0,2750.0,Yes,Yes,None,Senior,High Risk

In [315]:
'''Q19

Create:

Salary_Per_Year_Experience

Formula:

Salary / Experience

Handle the possibility of Experience = 0.

'''

df["Salary_Per_Year_Experience"]=df["Salary"]/df["Experience"].replace(0,np.nan)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,...,Tax,Salary_After_Tax,New_Salary,Bonus,Promotion_Eligible,Senior_Employee,High_Earner,Employee_Level,Risk_Category,Salary_Per_Year_Experience
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,...,5000.0,40000.0,55000.0,2500.0,No,No,None,Junior,None,25000.000000
1,Priya,32,HR,65000,6,130000,780000,72,33,102,...,6500.0,52000.0,71500.0,9750.0,Yes,No,None,Mid,None,10833.333333
2,Amit,28,IT,45000,3,90000,540000,36,29,101,...,4500.0,36000.0,49500.0,2250.0,No,No,None,Mid,None,15000.000000
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,...,16000.0,72000.0,88000.0,12000.0,Yes,Yes,Yes,Senior,None,8000.000000
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,...,4000.0,32000.0,44000.0,2000.0,No,No,None,Junior,None,40000.000000
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,...,14000.0,63000.0,77000.0,10500.0,Yes,Yes,Yes,Senior,None,10000.000000
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,...,6000.0,48000.0,66000.0,9000.0,Yes,No,None,Mid,None,12000.000000
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,...,5500.0,44000.0,60500.0,2750.0,Yes,Yes,None,Senior,High Risk,6875.000000

In [319]:
'''Q20

Create:

Employee_Score

Formula:

Salary / 10000 + Experience'''

df["Employee_Score"]=df["Salary"]/1000+df["Experience"]
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,...,Salary_After_Tax,New_Salary,Bonus,Promotion_Eligible,Senior_Employee,High_Earner,Employee_Level,Risk_Category,Salary_Per_Year_Experience,Employee_Score
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,...,40000.0,55000.0,2500.0,No,No,None,Junior,None,25000.000000,52.0
1,Priya,32,HR,65000,6,130000,780000,72,33,102,...,52000.0,71500.0,9750.0,Yes,No,None,Mid,None,10833.333333,71.0
2,Amit,28,IT,45000,3,90000,540000,36,29,101,...,36000.0,49500.0,2250.0,No,No,None,Mid,None,15000.000000,48.0
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,...,72000.0,88000.0,12000.0,Yes,Yes,Yes,Senior,None,8000.000000,90.0
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,...,32000.0,44000.0,2000.0,No,No,None,Junior,None,40000.000000,41.0
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,...,63000.0,77000.0,10500.0,Yes,Yes,Yes,Senior,None,10000.000000,77.0
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,...,48000.0,66000.0,9000.0,Yes,No,None,Mid,None,12000.000000,65.0
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,...,44000.0,60500.0,2750.0,Yes,Yes,None,Senior,High Risk,6875.000000,63.0

In [329]:
'''Q24 — Interview Problem 💼

A company wants to identify employees eligible for a special bonus.

Conditions:

Experience >= 5
AND
Salary >= 60000
AND
Department == "IT"

Create:

Special_Bonus

Rules:

Eligible     → 20000
Not Eligible → 0'''

def special_bonus(row):
    if row["Experience"]>=5 and row["Salary"] >=60000 and row["Department"]=="IT":
        return 20000
    else:
        return 0


df["Special_Bonus"]=df.apply(special_bonus,axis=1)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,...,New_Salary,Bonus,Promotion_Eligible,Senior_Employee,High_Earner,Employee_Level,Risk_Category,Salary_Per_Year_Experience,Employee_Score,Special_Bonus
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,...,55000.0,2500.0,No,No,None,Junior,None,25000.000000,52.0,0
1,Priya,32,HR,65000,6,130000,780000,72,33,102,...,71500.0,9750.0,Yes,No,None,Mid,None,10833.333333,71.0,0
2,Amit,28,IT,45000,3,90000,540000,36,29,101,...,49500.0,2250.0,No,No,None,Mid,None,15000.000000,48.0,0
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,...,88000.0,12000.0,Yes,Yes,Yes,Senior,None,8000.000000,90.0,0
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,...,44000.0,2000.0,No,No,None,Junior,None,40000.000000,41.0,0
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,...,77000.0,10500.0,Yes,Yes,Yes,Senior,None,10000.000000,77.0,20000
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,...,66000.0,9000.0,Yes,No,None,Mid,None,12000.000000,65.0,0
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,...,60500.0,2750.0,Yes,Yes,None,Senior,High Risk,6875.000000,63.0,0

In [337]:
'''Q22

Create:

Promotion_Status

Rules:

Experience >= 7 AND Salary >= 60000
        → Promote

Experience >= 5
        → Review

Otherwise
        → Not Ready'''


def promo(row):
    if row["Experience"]>=7 and row["Salary"]>=60000:
        return "Promote"
    elif row["Experience"] >=5:
        return "Review"
    else:
        "Not Ready"
df["Promotion_Status"]=df.apply(promo,axis=1)        
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,...,Bonus,Promotion_Eligible,Senior_Employee,High_Earner,Employee_Level,Risk_Category,Salary_Per_Year_Experience,Employee_Score,Special_Bonus,Promotion_Status
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,...,2500.0,No,No,None,Junior,None,25000.000000,52.0,0,None
1,Priya,32,HR,65000,6,130000,780000,72,33,102,...,9750.0,Yes,No,None,Mid,None,10833.333333,71.0,0,Review
2,Amit,28,IT,45000,3,90000,540000,36,29,101,...,2250.0,No,No,None,Mid,None,15000.000000,48.0,0,None
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,...,12000.0,Yes,Yes,Yes,Senior,None,8000.000000,90.0,0,Promote
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,...,2000.0,No,No,None,Junior,None,40000.000000,41.0,0,None
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,...,10500.0,Yes,Yes,Yes,Senior,None,10000.000000,77.0,20000,Promote
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,...,9000.0,Yes,No,None,Mid,None,12000.000000,65.0,0,Review
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,...,2750.0,Yes,Yes,None,Senior,High Risk,6875.000000,63.0,0,Review

In [345]:
'''Q21

Create:

Employee_Category

Rules:

Salary >= 70000 AND Experience >= 7
        → Top Performer

Salary >= 50000 AND Experience >= 3
        → Good Performer

Otherwise
        → Developing'''

def emp_cat(row):
    if row["Salary"]>=70000 and row["Experience"]>=7:
        return "Top Performer"
    elif row["Salary"]>=50000 and row["Experience"]>=3:
        return "Good Performer"
    else:
        "Developing"
df["Employee_Category"]=df.apply(emp_cat,axis=1)    
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,...,Promotion_Eligible,Senior_Employee,High_Earner,Employee_Level,Risk_Category,Salary_Per_Year_Experience,Employee_Score,Special_Bonus,Promotion_Status,Employee_Category
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,...,No,No,None,Junior,None,25000.000000,52.0,0,None,None
1,Priya,32,HR,65000,6,130000,780000,72,33,102,...,Yes,No,None,Mid,None,10833.333333,71.0,0,Review,Good Performer
2,Amit,28,IT,45000,3,90000,540000,36,29,101,...,No,No,None,Mid,None,15000.000000,48.0,0,None,None
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,...,Yes,Yes,Yes,Senior,None,8000.000000,90.0,0,Promote,Top Performer
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,...,No,No,None,Junior,None,40000.000000,41.0,0,None,None
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,...,Yes,Yes,Yes,Senior,None,10000.000000,77.0,20000,Promote,Top Performer
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,...,Yes,No,None,Mid,None,12000.000000,65.0,0,Review,Good Performer
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,...,Yes,Yes,None,Senior,High Risk,6875.000000,63.0,0,Review,Good Performer

In [353]:
'''Q23

Create:

Employee_Profile

Format:

Rahul - IT - 50000
Priya - HR - 65000
...

Hint:

You need multiple columns.'''

df["Employee_Profile"]=df.apply(
    lambda row:f"{row["Name"]} - {row["Department"]} - {row["Salary"]}",axis=1
)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,...,Senior_Employee,High_Earner,Employee_Level,Risk_Category,Salary_Per_Year_Experience,Employee_Score,Special_Bonus,Promotion_Status,Employee_Category,Employee_Profile
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,...,No,None,Junior,None,25000.000000,52.0,0,None,None,Rahul - IT - 50000
1,Priya,32,HR,65000,6,130000,780000,72,33,102,...,No,None,Mid,None,10833.333333,71.0,0,Review,Good Performer,Priya - HR - 65000
2,Amit,28,IT,45000,3,90000,540000,36,29,101,...,No,None,Mid,None,15000.000000,48.0,0,None,None,Amit - IT - 45000
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,...,Yes,Yes,Senior,None,8000.000000,90.0,0,Promote,Top Performer,Neha - Finance - 80000
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,...,No,None,Junior,None,40000.000000,41.0,0,None,None,Rohit - HR - 40000
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,...,Yes,Yes,Senior,None,10000.000000,77.0,20000,Promote,Top Performer,Sneha - IT - 70000
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,...,No,None,Mid,None,12000.000000,65.0,0,Review,Good Performer,Vikas - Finance - 60000
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,...,Yes,None,Senior,High Risk,6875.000000,63.0,0,Review,Good Performer,Pooja - HR - 55000

In [ ]:
'''Create a new column:

Employee_Segment

Rules:

Top
Salary >= 70000
AND
Experience >= 7
Mid
Salary >= 50000
AND
Experience >= 3
Entry

Everything else.

Then answer:

How many employees belong to each segment?'''

In [363]:
def emp_seg(row):
    if row["Salary"]>=70000 and row["Experience"]>=7:
        return "Top"
    elif row["Salary"]>=50000 and row["Experience"]>=3:
        return "Mid"
    else:
        return "Entry"

df["Employee_Segment"]=df.apply(emp_seg,axis=1)
df

,Name,Age,Department,Salary,Experience,Salary_Doubled,Annual_Salary,Experience_Months,Age_Next_Year,Department_Code,...,High_Earner,Employee_Level,Risk_Category,Salary_Per_Year_Experience,Employee_Score,Special_Bonus,Promotion_Status,Employee_Category,Employee_Profile,Employee_Segment
0,Rahul,25,IT,50000,2,100000,600000,24,26,101,...,None,Junior,None,25000.000000,52.0,0,None,None,Rahul - IT - 50000,Entry
1,Priya,32,HR,65000,6,130000,780000,72,33,102,...,None,Mid,None,10833.333333,71.0,0,Review,Good Performer,Priya - HR - 65000,Mid
2,Amit,28,IT,45000,3,90000,540000,36,29,101,...,None,Mid,None,15000.000000,48.0,0,None,None,Amit - IT - 45000,Entry
3,Neha,41,Finance,80000,10,160000,960000,120,42,103,...,Yes,Senior,None,8000.000000,90.0,0,Promote,Top Performer,Neha - Finance - 80000,Top
4,Rohit,24,HR,40000,1,80000,480000,12,25,102,...,None,Junior,None,40000.000000,41.0,0,None,None,Rohit - HR - 40000,Entry
5,Sneha,35,IT,70000,7,140000,840000,84,36,101,...,Yes,Senior,None,10000.000000,77.0,20000,Promote,Top Performer,Sneha - IT - 70000,Top
6,Vikas,29,Finance,60000,5,120000,720000,60,30,103,...,None,Mid,None,12000.000000,65.0,0,Review,Good Performer,Vikas - Finance - 60000,Mid
7,Pooja,45,HR,55000,8,110000,660000,96,46,102,...,None,Senior,High Risk,6875.000000,63.0,0,Review,Good Performer,Pooja - HR - 55000,Mid